using gAPI.AutoApi.Client.Generators.Clients;
using gAPI.AutoApi.Client.Models;

namespace gAPI.AutoApi.Client.Generators.Startup;

public class AddAutoApiSseClientExtensionGenerator : _BaseGenerator
{
    public AddAutoApiSseClientExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AutoApiSseClientExtension";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }
    public ApiClientGenerator[] Clients => Context.Clients;
    public SharedReference ClientConnection => Context.ClientConnection;
    public SharedReference IClientConnection => Context.SharedReferences.ISseClientConnection;
    public SharedReference SseManagerCollection => Context.SharedReferences.SseManagerCollection;

    public SharedReference IUriNavigationManager => Context.SharedReferences.IUriNavigationManager;
    public SharedReference DefaultNavigationManager => Context.SharedReferences.DefaultNavigationManager;
    public SharedReference StaticNavigationManager => Context.SharedReferences.StaticNavigationManager;
    public SharedReference WithCookiesHandler => Context.SharedReferences.WithCookiesHandler;


    public SharedReference? IClientAuthenticatedHttpClientImplementation => Context.SharedReferences.IClientAuthenticatedHttpClientImplementation;
    public SharedReference AuthenticatedHttpClient => Context.AuthenticatedHttpClient;
    public SharedReference IAuthenticatedHttpClient => Context.IAuthenticatedHttpClient;

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.DependencyInjection.Extensions");
        Reg("Microsoft.AspNetCore.Components");
        Reg("Microsoft.AspNetCore.Components.Authorization");
        Reg(ClientConnection);
        Reg(IClientConnection);
        Reg(SseManagerCollection);
        Reg(DefaultNavigationManager);
        Reg(StaticNavigationManager);
        Reg(WithCookiesHandler);

        var propertiesCode = "";
        foreach (var client in Clients)
        {
            var @interface = client.Interface;
            Reg(@interface);
            Reg(client);
            propertiesCode += $"\r\n        services.AddScoped<{@interface.Name}, {client.Name}>();";
        }

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
namespace {Namespace};

public static class {Name}
{{
    public static void AddAutoApiSseClient(this IServiceCollection services, string apiUrl)
    {{{propertiesCode}
        services.AddScoped<{ClientConnection}>();
        services.AddScoped<{IClientConnection}>(sp => sp.GetRequiredService<{ClientConnection}>());

        var sseManagerCollection = new {SseManagerCollection}();
        services.AddSingleton(sseManagerCollection);

        // Het kan helaas niet anders
        services.AddScoped<{IUriNavigationManager}>(sp =>
        {{
            var navigationManager = sp.GetService<NavigationManager>();
            if (navigationManager != null)
            {{
                return new {DefaultNavigationManager}(navigationManager);
            }}
            else
            {{
                return new {StaticNavigationManager}();
            }}
        }});

        // Register the cookie handler
        services.AddScoped<{WithCookiesHandler}>();

{(IClientAuthenticatedHttpClientImplementation == null ? $@"

        // Register global client authentication service
        services.AddScoped<{AuthenticatedHttpClient}>();
        services.AddScoped<{IAuthenticatedHttpClient}>(sp => sp.GetRequiredService<{AuthenticatedHttpClient}>());
        services.AddScoped<gAPI.Core.Client.Interfaces.IClientAuthenticatedHttpClient>(sp => sp.GetRequiredService<{AuthenticatedHttpClient}>());
        services.AddScoped<AuthenticationStateProvider>(sp => sp.GetRequiredService<{AuthenticatedHttpClient}>());
" : $@"

        // Register global client authentication service
        services.AddScoped<gAPI.Core.Client.Interfaces.IClientAuthenticatedHttpClient>(sp => sp.GetRequiredService<{IClientAuthenticatedHttpClientImplementation}>());
        services.AddScoped<AuthenticationStateProvider>(sp => sp.GetRequiredService<{IClientAuthenticatedHttpClientImplementation}>());
")}
    }}
}}";
    }
}