using gAPI.AutoSseServer.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoSseServer.Generators;

public class AddAutoSseExtention_Generator : BaseGenerator
{
    public AddAutoSseExtention_Generator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoSseExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public IEnumerable<ClientService_Generator> SseServices => Context.SseServices;
    public IClientContext_Generator IClientContext => Context.IClientContext;
    public ClientContext_Generator ClientContext => Context.ClientContext;
    public SharedReference SseHostCollection => Context.SharedReferences.SseHostCollection;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference SseHost => Context.SharedReferences.SseHost;
    public SharedReference WssSessionCache => Context.SharedReferences.WssSessionCache;

    public override void GenerateCode()
    {
        Reg(IClientContext);
        Reg(ClientContext);
        Reg(SseHostCollection);
        Reg(FabricClient);
        Reg(IServerAuthenticationService);
        Reg(ServiceId);
        Reg(UserId);
        Reg(SessionId);
        Reg(ServerConfig);
        Reg(SseHost);
        Reg(WssSessionCache);
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.Extensions.DependencyInjection");

        foreach (var item in Context.ClientContexts)
        {
            Reg(item);
            Reg(item.IClientContext);
        }

        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoSse(this IServiceCollection services, {ServerConfig} serverConfig)
    {{
        return AddAutoSse(services, serverConfig.FrontendUrl, serverConfig.FabricConnectionString);
    }}
    public static IServiceCollection AddAutoSse(this IServiceCollection services, string? frontendUrl, string? fabricConnectionString = null)
    {{
        services.AddHttpContextAccessor();
        services.AddCors(options =>
        {{
            options.AddPolicy(""AllowSpecificOrigin"", policy =>
            {{
                policy
                    .WithOrigins(frontendUrl)
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()
                    .WithExposedHeaders(""X-SessionId"", ""X-StateData"");
            }});
        }});

        services.AddSingleton(sp => new {FabricClient}(sp.GetRequiredService<ILoggerFactory>(), fabricConnectionString));

        var sseHostCollection = new {SseHostCollection}();
        services.AddSingleton(sseHostCollection);

        var sessionCache = new {WssSessionCache}();
        services.AddSingleton(sessionCache);

        services.AddScoped<{IClientContext}, {ClientContext}>();

{string.Join("", Context.ClientContexts.Select(a => $@"
        services.AddScoped<{a.IClientContext}, {a}>();"))}

        return services;
    }}
    public static WebApplication MapAutoSse(this WebApplication app)
    {{
        app.MapGet(""/ssehost/connect/{{serviceId}}"", async (
            string serviceId,
            [FromHeader(Name = ""X-SessionId"")] string sessionId,
            {IServerAuthenticationService} authenticationService,
            {SseHostCollection} sseHostCollection,
            {FabricClient} fabricClient,
            CancellationToken ct
        ) =>
        {{
            var sseHost = new {SseHost}(
                sseHostCollection,
                fabricClient,
                new {ServiceId}(serviceId),
                authenticationService.UserId,
                authenticationService.SessionId
            );

            return Results.ServerSentEvents(
                sseHost.ReadAllAsync(ct)
            );
        }});
        return app;
    }}
}}
";

    }
}