using System.Linq;
using System;
using gAPI.AutoSseServer.Models;

namespace gAPI.AutoSseServer.Generators;

public class ClientServiceContext_Generator : BaseGenerator
{
    public ClientServiceContext_Generator(
        Generator context,
        IClientServiceContext_Generator iClientContext)
    {
        Context = context;
        IClientContext = iClientContext;

        Directory = "";
        Namespace = iClientContext.Namespace;

        Name = Interface.CleanName + "Context";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public IClientServiceContext_Generator IClientContext { get; }

    public Interface Interface => IClientContext.Interface;
    public ServiceContext DataModel => Context.ServiceContext;
    public ClientService_Generator SseService => IClientContext.SseService;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference SessionId => Context.SharedReferences.SessionId;

    public override void GenerateCode()
    {
        Reg(IClientContext);
        Reg(Interface);
        Reg(SseService);
        Reg(FabricClient);
        Reg(UserId);
        Reg(SessionId);
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {FabricClient} fabricClient)
    : {IClientContext.Name}
{{
    public {Interface.Name} ToAll
        => new {SseService.Name}(fabricClient);
    public {Interface.Name} ToUser(string userId)
        => new {SseService.Name}(fabricClient, new {UserId}(userId));
    public {Interface.Name} ToSession(string sessionId)
        => new {SseService.Name}(fabricClient, null, new {SessionId}(sessionId));
}}
";
    }
}