using gAPI.AutoSseServer.Models;
using System.Linq;

namespace gAPI.AutoSseServer.Generators;

public class ClientContext_Generator : BaseGenerator
{
    public ClientContext_Generator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "ClientContext";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public ServiceContext DataModel => Context.ServiceContext;
    public ClientServiceContext_Generator[] ClientContexts => Context.ClientContexts;
    public IClientContext_Generator IClientContext => Context.IClientContext;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;

    public override void GenerateCode()
    {
        Reg(IClientContext);
        Reg(FabricClient);
        var properties = string.Join(
            "\r\n",
            ClientContexts
                .Select(a =>
                {
                    Reg(a);
                    Reg(a.IClientContext);
                    return $"    public {a.IClientContext.Name} {a.SseService.Interface.Title} {{ get; }} = new {a.Name}(fabricClient);";
                }));

        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {FabricClient} fabricClient)
    : {IClientContext}
{{
{properties}
}}
";
    }
}