using gAPI.AutoWss.Server.Helpers;
using gAPI.AutoWss.Server.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Endpoints;

public class MinimalApi_Generator : _BaseGenerator
{
    public MinimalApi_Generator(Generator context, Interface @interface)
    {
        Context = context;
        Interface = @interface;

        Directory = "";
        Namespace = Interface.Namespace;

        Name = $"{Interface.CleanName}EndpointsExtensions";
        FileName = $"Endpoints/{Name}.g.cs";
    }

    public Generator Context { get; }
    public Interface Interface { get; }
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference AuthenticationInitializeResult => Context.SharedReferences.AuthenticationInitializeResult;

    public override void GenerateCode()
    {
        foreach (var @interface in Context.ServiceContext.MinimalApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }

        Reg(Interface);
        Reg(IServerAuthenticationService);
        Reg(AuthenticationInitializeResult);
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.Extensions.Primitives");
        Reg("Microsoft.AspNetCore.Mvc.ModelBinding");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.AspNetCore.Routing");
        Reg("Microsoft.Extensions.Hosting");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("System.Net");

        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IEndpointRouteBuilder Map{Interface.CleanName}Endpoints(this IEndpointRouteBuilder app)
    {{{string.Join("", Interface.Methods.Select(method => $@"
        app.Map{Interface.CleanName}{method}();"))}
        return app;
    }}{string.Join("", Interface.Methods.Select(method =>
        {
            var isBaseModel = method.ResponseType.IsBaseResponse;
            var hasParameters = method.Arguments.Any(a => a.ParameterType.Name != "CancellationToken");
            var nameLower = $"/{Interface.CleanName.ToLower()}/{method.Name.ToLower()}";
            var crudArgument = method.Arguments
                .FirstOrDefault(a => a.ParameterType.Name != "CancellationToken")?
                .Name
                .ToCamelCase();
            var methodAttribute = method switch
            {
                { IsCreate: true } =>
                    $"MapPost(\"{nameLower}\", ",

                { IsRead: true } =>
                    crudArgument != null
                    ? $"MapGet(\"{nameLower}/{{{crudArgument}}}\", "
                    : throw new Exception("id argument not found"),

                { IsUpdate: true } =>
                    $"MapPut(\"{nameLower}\", ",

                { IsDelete: true } =>
                    crudArgument != null
                    ? $"MapDelete(\"{nameLower}/{{{crudArgument}}}\", "
                    : throw new Exception("id argument not found"),

                { IsList: true } =>
                    $"MapGet(\"{nameLower}\", ",

                { IsListBy: true } or { IsListNotBy: true } =>
                    crudArgument != null
                    ? $"MapGet(\"{nameLower}/{{{crudArgument}}}\", "
                    : throw new Exception("id argument not found"),

                { IsFileUpdate: true } =>
                    crudArgument != null
                    ? $"MapPut(\"{nameLower}/{{{crudArgument}}}\", "
                    : throw new Exception("id argument not found"),

                { IsFileDelete: true } => crudArgument != null
                    ? $"MapDelete(\"{nameLower}/{{{crudArgument}}}\", "
                    : throw new Exception("id argument not found"),

                _ when hasParameters =>
                    $"MapPost(\"{nameLower}\", ",

                _ =>
                    $"MapGet(\"{nameLower}\", "
            };
            var methodArguments = string.Join(", ",
            [
                ..method.Arguments.Select(arg =>
                    (method, arg) switch
                    {
                        // IFormFile is altijd body
                        (_, { IsIFormFile: true }) =>
                            $@"
            [FromBody]{arg.ParameterType.Name} {arg.Name}",

                        // CancellationToken nooit annoteren
                        (_, { ParameterType: { Name: "CancellationToken" } }) =>
                            $@"
            {arg.ParameterType.Name} {arg.Name}",

                        // File operations: id uit route
                        ({ IsFileUpdate: true } or { IsFileDelete: true }, _) =>
                            $@"
            [FromRoute] {arg.ParameterType.Name} {arg.Name}",

                        // List / filtering
                        ({ IsList: true } or { IsListBy: true } or { IsListNotBy: true }, _)
                            when arg.Name is "skip" or "take" or "orderby" =>
                                $@"
            [FromQuery] {arg.ParameterType.Name} {arg.Name}",

                        ({ IsList: true } or { IsListBy: true } or { IsListNotBy: true }, _) =>
                            $@"
            [FromRoute] {arg.ParameterType.Name} {arg.Name}",

                        // Read / Delete
                        ({ IsRead: true } or { IsDelete: true }, _) =>
                            $@"
            [FromRoute] {arg.ParameterType.Name} {arg.Name}",

                        // Default: form body
                        _ =>
                            $@"
            [FromForm] {arg.ParameterType.Name} {arg.Name}"
                    }),
                $@"
            [FromHeader(Name = ""X-SessionId"")] string ___sessionId",
                $@"
            [FromHeader(Name = ""X-StateData"")] string? ___stateData",
                $@"
            [FromServices] IServerAuthenticationService ___authentication",
                $@"
            HttpContext ___httpContext",
                $@"
            [FromServices] TimeProvider ___dateTime",
                $@"
            [FromServices] IHostEnvironment ___hostEnvironment",
                $@"
            [FromServices] {Interface} {Interface.CleanName.ToCamelCase()}"
            ]);
            var methodCallArguments = string.Join(", ", method.Arguments.Select(a => $"{a.Name}"));

            var underlaying = method.ResponseType.UnderlayingTypes.FirstOrDefault();

            var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);

            var responseType =
                underlaying == null
                ? "BaseResponse"
                : (underlaying.IsBaseResponse || underlaying.IsBaseResponseT || underlaying.IsBaseListResponseT)
                    ? underlaying.Name
                    : $"BaseResponseT<{underlaying.Name}>";

            return $@"
    public static IEndpointRouteBuilder Map{Interface.CleanName}{method}(this IEndpointRouteBuilder app)
    {{
        app.{methodAttribute}async ({methodArguments}) =>
        {{{(underlaying == null
            ? $@"
            await {Interface.CleanName.ToCamelCase()}.{method.Name}({methodCallArguments});
            return Results.Ok(new {responseType}() {{ Success = true }});"
            : underlaying.IsBaseResponse ||
                underlaying.IsBaseResponseT ||
                underlaying.IsBaseListResponseT
                ? $@"
            var response = await {Interface.CleanName.ToCamelCase()}.{method.Name}({methodCallArguments});
            return Results.Ok(response);"
                : $@"
            var response = await {Interface.CleanName.ToCamelCase()}.{method.Name}({methodCallArguments});
            return Results.Ok(new {responseType}() {{ Success = true, Response = response }});")}
        }}){(method.IsAuthorized ? $@"
        .RequireAuthorization()" : $@"
        .AllowAnonymous()")}
        .DisableAntiforgery();
        return app;
    }}";
        }))}
}}";
    }

}