
//// <auto-generated />
//#nullable enable
//using gAPI.Core.Server.Fabric;

//namespace gAPI.Generated;

//public class ServerContext(
//    ICameraApiContext cameraApiContext)
//    : IServerContext
//{
//    public ICameraApiContext CameraApi { get; } = cameraApiContext;
//}