using gAPI.AutoApiServer.Models;
using System.Linq;

namespace gAPI.AutoApiServer.Generators;


public class AddAutoApiServicesExtensionGenerator : BaseGenerator
{
    public AddAutoApiServicesExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoApiServicesExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");
        var propertiesCode = "";
        foreach (var controller in Context.Apis.Where(a => a.Interface.FullName != "gAPI.Interfaces.IAccountService"))
        {
            var service = controller.Service;
            var @interface = controller.Interface;
            Reg(service);
            Reg(@interface);
            propertiesCode += $"        services.AddScoped<{@interface.Name}, {service.Name}>();\r\n";
        }

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
namespace {Namespace};

public static class {Name}
{{
    public static void AddAutoApiServices(this IServiceCollection services)
    {{
{propertiesCode}    }}
}}";

    }
}