
using gAPI.AutoApiServer.Models;
using System.Linq;

namespace gAPI.AutoApiServer.Generators;

public class AddAutoApiExtensionGenerator : BaseGenerator
{
    public AddAutoApiExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoApiExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public AddAutoApiServicesExtensionGenerator AddAutoApiServices => Context.AddAutoApiServices;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SseHostCollection => Context.SharedReferences.SseHostCollection;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference? Middleware => Context.SharedReferences.AuthServer_Middleware;

    public override void GenerateCode()
    {
        Reg("Microsoft.AspNetCore.Authentication");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("System.Reflection");
        Reg("System.Globalization");
        Reg(AddAutoApiServices);
        Reg(ServerConfig);
        Reg(FabricClient);
        Reg(SseHostCollection);
        foreach (var api in Context.MinimalApis)
        {
            Reg(api);
            Reg(api.Interface);
            Reg(api.Interface.Service);
            foreach (var method in api.Interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoApi(this IServiceCollection services, {ServerConfig} serverConfig)
    {{
        return AddAutoApi(services, serverConfig.FrontendUrl, serverConfig.FabricConnectionString);
    }}
    public static IServiceCollection AddAutoApi(this IServiceCollection services, string frontendUrl, string? fabricConnectionString)
    {{
        CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;

        services.AddHttpContextAccessor();
        services.AddCors(options =>
        {{
            options.AddPolicy(""AllowSpecificOrigin"", policy =>
            {{
                policy
                    .WithOrigins(frontendUrl)
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()
                    .WithExposedHeaders(""X-SessionId"", ""X-StateData"");
            }});
        }});

        services.AddSingleton(sp => new {FabricClient}(sp.GetRequiredService<ILoggerFactory>(), fabricConnectionString));

        var sseHostCollection = new {SseHostCollection}();
        services.AddSingleton(sseHostCollection);

        services.AddAutoApiServices();
        services.AddAuthorization();
        services.AddControllers();

        return services;
    }}

    public static WebApplication MapAutoApi<TMiddleware>(this WebApplication app)
    {{
        app.UseForwardedHeaders(new ForwardedHeadersOptions
        {{
            ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
        }});

        app.UseCors(""AllowSpecificOrigin"");

        app.UseMiddleware<TMiddleware>();
        app.UseAuthentication();
        app.UseAuthorization();

        // 🔥 State handshake endpoint
        app.MapGet(""/__state"", ([FromHeader(Name = ""X-SessionId"")] string sessionId) => {{ }}).AllowAnonymous();

{(string.Join("", Context.MinimalApis.Select(Interface => $@"
        app.Map{Interface.Interface.CleanName}Endpoints();")))}

        app.MapControllers();

        return app;
    }}
}}

";

































//        Code = $@"{GetNamespacesCode()}
//namespace {Namespace};

//public static class {Name}
//{{
//    public static void AddAutoApi<TInterface, TImplementation>(this IServiceCollection services, string frontendUrl, params Assembly[] assembliesToScan)
//        where TInterface : class, gAPI.Interfaces.IServerAuthenticationService
//        where TImplementation : class, gAPI.Interfaces.IServerAuthenticationService, TInterface
//    {{
//        // JSON standaard op invariant zetten
//        services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options =>
//        {{
//            options.SerializerOptions.Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping;
//            options.SerializerOptions.PropertyNamingPolicy = null;
//            options.SerializerOptions.WriteIndented = false;
//        }});

//        // Add normal asp.net core controllers
//        services.AddControllers();

//        // Http context accessor for gAPI
//        services.AddHttpContextAccessor();

//        // Remaining services
//        services.AddAutoApiServices();

//        // Add Cors
//        services.AddCors(options =>
//        {{
//            options.AddPolicy(""AllowSpecificOrigin"", policy =>
//            {{
//                policy.WithOrigins(frontendUrl)
//                      .AllowAnyMethod()
//                      .AllowAnyHeader()
//                      .AllowCredentials();
//            }});
//        }});

//        // Add gAPI server authentication 
//        services.AddScoped<TImplementation>() ;
//        services.AddScoped<TInterface>(sp => sp.GetRequiredService<TImplementation>())   ;
//        services.AddScoped<gAPI.Interfaces.IServerAuthenticationService>(sp => sp.GetRequiredService<TImplementation>());
//        services.AddAuthentication(""gAPI"")
//                        .AddScheme<AuthenticationSchemeOptions, BSD.Core.Authentication.ServerAuthenticationHandler>(""gAPI"", _ => {{ }});
//        services.AddAuthorization();

//    }}

//    public static void MapAutoApi(this WebApplication app)
//    {{
//        app.UseForwardedHeaders(new ForwardedHeadersOptions
//        {{
//            ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
//        }});

//        app.UseCors(""AllowSpecificOrigin"");

//        app.MapControllers();

//        app.UseMiddleware<BSD.Core.Authentication.ServerAuthenticationMiddleware>();
//        app.UseAuthentication();
//        app.UseAuthorization();
//    }}
//}}
//";

    }
}