using gAPI.AutoApi.Helpers;
using gAPI.AutoApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApi.Generators;

internal class ControllerGenerator : BaseGenerator
{
    internal ControllerGenerator(ServiceContext dataModel, Service service)
    {
        DataModel = dataModel;
        Service = service;

        Directory = dataModel.Config.Controllers_Destination.Directory;
        Namespace = dataModel.Config.Controllers_Destination.Namespace;

        Name = service.Interface.Title + "Controller";
        FileName = $"{Name}.g.cs";
    }

    public ServiceContext DataModel { get; }
    public Service Service { get; }

    public void GenerateCode()
    {
        Reg(Service.Interface);
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("gAPI.Dtos");

        var synchroniousMethod = Service.Interface.Methods.FirstOrDefault(method => method.IsAsync == false);
        if (synchroniousMethod != null)
            throw new Exception($"We don't do synchonious code anymore, please change to async. {Name}.{synchroniousMethod.Name}");

        foreach (var method in Service.Interface.Methods)
        {
            RegRange(method.Arguments.SelectMany(b => b.ParameterType.Namespaces));
            RegRange(method.ResponseType.Namespaces);
        }

        UnReg("System.Threading.Tasks");

        Code = $@"{GetNamespacesCode()}
#nullable enable

// <auto-generated />
namespace {Namespace};

[ApiController]
[Route(""{Service.Interface.Title.ToLower()}"")]
public class {Name}(
    {Service.Interface.Name} {Service.Name.ToCamelCase()})
    : ControllerBase
{{{string.Join("", Service.Interface.Methods.Select(method =>
        {
            var isBaseModel = method.ResponseType.IsBaseResponse;
            var hasParameters = method.Arguments.Any(a => a.ParameterType.Name != "CancellationToken");
            var nameLower = method.Name.ToLower();
            var crudArgument = method.Arguments
                .FirstOrDefault(a => a.ParameterType.Name != "CancellationToken")?
                .Name
                .ToCamelCase();
            var methodAttribute = method switch
            {
                { IsCreate: true } =>
                    $"[HttpPost(\"{nameLower}\")]",

                { IsRead: true } =>
                    crudArgument != null
                    ? $"[HttpGet(\"{nameLower}/{{{crudArgument}}}\")]"
                    : throw new Exception("id argument not found"),

                { IsUpdate: true } =>
                    $"[HttpPut(\"{nameLower}\")]",

                { IsDelete: true } =>
                    crudArgument != null
                    ? $"[HttpDelete(\"{nameLower}/{{{crudArgument}}}\")]"
                    : throw new Exception("id argument not found"),

                { IsList: true } =>
                    $"[HttpGet(\"{nameLower}\")]",

                { IsListBy: true } or { IsListNotBy: true } =>
                    crudArgument != null
                    ? $"[HttpGet(\"{nameLower}/{{{crudArgument}}}\")]"
                    : throw new Exception("id argument not found"),

                { IsFileUpdate: true } =>
                    crudArgument != null
                    ? $"[HttpPut(\"{nameLower}/{{{crudArgument}}}\")]"
                    : throw new Exception("id argument not found"),

                { IsFileDelete: true } => crudArgument != null
                    ? $"[HttpDelete(\"{nameLower}/{{{crudArgument}}}\")]"
                    : throw new Exception("id argument not found"),

                _ when hasParameters =>
                    $"[HttpPost(\"{nameLower}\")]",

                _ =>
                    $"[HttpGet(\"{nameLower}\")]"
            };
            var methodArguments = string.Join(", ",
            [
                ..method.Arguments.Select(arg => (method, arg) switch
        {
            // IFormFile is altijd body
            (_, { IsIFormFile: true }) =>
                $"{arg.ParameterType.Name} {arg.Name}",

            // CancellationToken nooit annoteren
            (_, { ParameterType: { Name: "CancellationToken" } }) =>
                $"{arg.ParameterType.Name} {arg.Name}",

            // File operations: id uit route
            ({ IsFileUpdate: true } or { IsFileDelete: true }, _) =>
                $"[FromRoute] {arg.ParameterType.Name} {arg.Name}",

            // List / filtering
            ({ IsList: true } or { IsListBy: true } or { IsListNotBy: true }, _)
                when arg.Name is "skip" or "take" or "orderby" =>
                    $"[FromQuery] {arg.ParameterType.Name} {arg.Name}",

            ({ IsList: true } or { IsListBy: true } or { IsListNotBy: true }, _) =>
                $"[FromRoute] {arg.ParameterType.Name} {arg.Name}",

            // Read / Delete
            ({ IsRead: true } or { IsDelete: true }, _) =>
                $"[FromRoute] {arg.ParameterType.Name} {arg.Name}",

            // Default: form body
            _ =>
                $"[FromForm] {arg.ParameterType.Name} {arg.Name}"
        }),
        "[FromHeader(Name = \"X-SessionId\")] string sessionId"
            ]);
            var methodCallArguments = string.Join(", ", method.Arguments.Select(a => $"{a.Name}"));

            var underlaying = method.ResponseType.UnderlayingTypes.FirstOrDefault();

            var responseType =
                underlaying == null
                ? "BaseResponse"
                : (underlaying.IsBaseResponse || underlaying.IsBaseResponseT || underlaying.IsBaseListResponseT)
                    ? underlaying.Name
                    : $"BaseResponseT<{underlaying.Name}>";

            return $@"
    {methodAttribute}
    public async Task<ActionResult<{responseType}>> {method.Name}({methodArguments})
    {{
        if (!ModelState.IsValid) return BadRequest(ModelState);{(
        underlaying == null
        ? $@"
        await {Service.Name.ToCamelCase()}.{method.Name}({methodCallArguments});
        return Ok(new {responseType}() {{ Success = true }});"
        :   underlaying.IsBaseResponse || 
            underlaying.IsBaseResponseT || 
            underlaying.IsBaseListResponseT
            ? $@"
        var response = await {Service.Name.ToCamelCase()}.{method.Name}({methodCallArguments});
        return Ok(response);"
            : $@"
        var response = await {Service.Name.ToCamelCase()}.{method.Name}({methodCallArguments});
        return Ok(new {responseType}() {{ Success = true, Response = response }});")}
    }}";
        }))}
}}";
    }
}