using gAPI.AutoWss.Client.Models;
using System.Linq;

namespace gAPI.AutoWss.Client.Generators.Startup;

public class AddAutoWssClientExtensionGenerator : _BaseGenerator
{
    public AddAutoWssClientExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoWssClientExtension";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference ClientConnection => Context.ClientConnection;
    public SharedReference IClientConnection => Context.IClientConnection;
    public SharedReference IWssLoggerFactory => Context.SharedReferences.IWssLoggerFactory;
    public SharedReference IWssClientConnection => Context.SharedReferences.IWssClientConnection;
    public SharedReference ClientConfig => Context.SharedReferences.ClientConfig;

    public override void GenerateCode()
    {
        Reg("Microsoft.AspNetCore.Components");
        Reg("Microsoft.AspNetCore.Components.Authorization");
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.DependencyInjection.Extensions");
        Reg("Microsoft.Extensions.Configuration");
        Reg("gAPI.Core.Client");
        Reg("gAPI.Core.Client.Interfaces");
        Reg("gAPI.Core.Client.Extensions");
        Reg(ClientConnection);
        Reg(IClientConnection);
        Reg(IWssLoggerFactory);
        Reg(IWssClientConnection);
        Reg(ClientConfig);
        foreach (var api in Context.Apis)
        {
            Reg(api);
            Reg(api.Interface);
        }
        foreach (var api in Context.MinimalApis)
        {
            Reg(api);
            Reg(api.Interface);
        }


        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoWssClient(
        this IServiceCollection services,
        IConfigurationManager configuration,
        TimeProvider? dateTime = null)
    {{
        var config = configuration.CreateClientConfig();
        return AddAutoWssClient(services, config, dateTime);
    }}

    public static IServiceCollection AddAutoWssClient(
        this IServiceCollection services, 
        string apiAddress, 
        string wssAddress,
        TimeProvider? dateTime = null)
    {{
        var config = new {ClientConfig}(apiAddress, wssAddress);
        return AddAutoWssClient(services, config, dateTime);
    }}

    public static IServiceCollection AddAutoWssClient(
        this IServiceCollection services, 
        {ClientConfig} config,
        TimeProvider? dateTime = null)
    {{
        services.AddSingleton(dateTime ?? TimeProvider.System);
        services.AddSingleton(config);

        // Connection stuff
        services.AddScoped<{ClientConnection}>();
        services.AddScoped<{IClientConnection}>(sp => sp.GetRequiredService<{ClientConnection}>());
        services.AddScoped<{IWssLoggerFactory}>(sp => sp.GetRequiredService<{ClientConnection}>());
        
        // Api clients{string.Join("", Context.Apis.Select(api => $@"
        services.AddScoped<{api.Interface}>(sp => sp.GetRequiredService<{ClientConnection}>().{api});"))}
        
        // Minimal api clients{string.Join("", Context.MinimalApis.Select(api => $@"
        services.AddScoped<{api.Interface}, {api}>();"))}

        return services;
    }}
}}";
    }
}