using gAPI.AutoAuth.Client.Models;
using System.Linq;

namespace gAPI.AutoAuth.Client.Generators.Startup;

public class AddAutoAuthClientExtensionGenerator : _BaseGenerator
{
    public AddAutoAuthClientExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoAuthClientExtension";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference IWssLoggerFactory => Context.SharedReferences.IWssLoggerFactory;
    public SharedReference IWssClientConnection => Context.SharedReferences.IWssClientConnection;
    public SharedReference FrontendConfig => Context.SharedReferences.FrontendConfig;

    public SharedReference IUriNavigationManager => Context.SharedReferences.IUriNavigationManager;
    public SharedReference DefaultNavigationManager => Context.SharedReferences.DefaultNavigationManager;
    public SharedReference StaticNavigationManager => Context.SharedReferences.StaticNavigationManager;
    public SharedReference WithCookiesHandler => Context.SharedReferences.WithCookiesHandler;

    public SharedReference? IClientAuthenticatedHttpClientImplementation => Context.SharedReferences.IClientAuthenticatedHttpClientImplementation;
    public SharedReference AuthenticatedHttpClient => Context.AuthenticatedHttpClient;
    public SharedReference IAuthenticatedHttpClient => Context.IAuthenticatedHttpClient;

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.DependencyInjection.Extensions");
        Reg("Microsoft.AspNetCore.Components");
        Reg("Microsoft.AspNetCore.Components.Authorization");
        Reg("gAPI.Core.Client.Interfaces");
        Reg("gAPI.Core.Client");
        Reg(IWssLoggerFactory);
        Reg(IWssClientConnection);
        Reg(FrontendConfig);
        Reg(IUriNavigationManager);
        Reg(DefaultNavigationManager);
        Reg(StaticNavigationManager);
        Reg(WithCookiesHandler);
        Reg(AuthenticatedHttpClient);
        Reg(IAuthenticatedHttpClient);
        if (IClientAuthenticatedHttpClientImplementation != null)
            Reg(IClientAuthenticatedHttpClientImplementation);

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoAuthClient(this IServiceCollection services, {FrontendConfig} config)
    {{
        return AddAutoAuthClient(services, config.ApiBackendUrl);
    }}
    public static IServiceCollection AddAutoAuthClient(this IServiceCollection services, string apiAddress)
    {{
        // Het kan helaas niet anders
        services.AddScoped<{IUriNavigationManager}>(sp =>
        {{
            var navigationManager = sp.GetService<NavigationManager>();
            if (navigationManager != null)
            {{
                return new {DefaultNavigationManager}(navigationManager);
            }}
            else
            {{
                return new {StaticNavigationManager}();
            }}
        }});

        // Register the cookie handler
        services.AddScoped<{WithCookiesHandler}>();

        // Configure named client for WebAssembly with cookies
        services
            .AddHttpClient(""WithCookies"", opt => opt.BaseAddress = new Uri(apiAddress))
            .AddHttpMessageHandler<{WithCookiesHandler}>();{
(IClientAuthenticatedHttpClientImplementation == null ? $@"

        // Register global client authentication service
        services.AddScoped<{AuthenticatedHttpClient}>();
        services.AddScoped<{IAuthenticatedHttpClient}>(sp => sp.GetRequiredService<{AuthenticatedHttpClient}>());
        services.AddScoped<gAPI.Core.Client.Interfaces.IClientAuthenticatedHttpClient>(sp => sp.GetRequiredService<{AuthenticatedHttpClient}>());
        services.AddScoped<AuthenticationStateProvider>(sp => sp.GetRequiredService<{AuthenticatedHttpClient}>());
" : $@"

        // Register global client authentication service
        services.AddScoped<gAPI.Core.Client.Interfaces.IClientAuthenticatedHttpClient>(sp => sp.GetRequiredService<{IClientAuthenticatedHttpClientImplementation}>());
        services.AddScoped<AuthenticationStateProvider>(sp => sp.GetRequiredService<{IClientAuthenticatedHttpClientImplementation}>());
")}
        // Set up authorization core
        services.AddAuthorizationCore();

        return services;
    }}
}}";
    }
}