<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<Version>0.0.2-beta</Version>
		<Authors>Willem Beltman</Authors>
		<Company>Willem Beltman</Company>

		<PackageId>gAPI.AutoWss.Server</PackageId>
		<Description>gAPI AutoWss server source generator for automatic WebSocket API and Hub generation.</Description>
		<PackageTags>gapi;api;websocket;wss;rpc;roslyn;source-generator;analyzer;codegen;dotnet;aspnetcore</PackageTags>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/willembeltman/gAPI</PackageProjectUrl>
		<RepositoryUrl>https://github.com/willembeltman/gAPI</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README.md</PackageReadmeFile>

		<DevelopmentDependency>true</DevelopmentDependency>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

		<IncludeBuildOutput>false</IncludeBuildOutput>
		<NoPackageAnalysis>true</NoPackageAnalysis>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />

		<None Include="$(OutputPath)\$(AssemblyName).dll"
			  Pack="true"
			  PackagePath="analyzers/dotnet/cs"
			  Visible="false" />
	</ItemGroup>

</Project>