//using gAPI.Core.Dtos;
//using gAPI.Core.Server.Fabric;
//using gAPI.Core.Server.Interfaces;
//using System.Threading;

//// <auto-generated />
//#nullable enable
//namespace gAPI.Generated;

//public class ServiceRouter(
//    IServiceProvider serviceProvider)
//    : IServiceRouter
//{
//    public Task InvokeRequestAsync(FabricClient fabricClient, ServerInvokeRequestDto message, CancellationToken ct)
//    {
//        throw new NotImplementedException();
//    }

//    public Task InvokeRequestCancelled(FabricClient fabricClient, ServerInvokeRequestCancelledDto message, CancellationToken ct)
//    {
//        throw new NotImplementedException();
//    }

//    public Task SendRequestAsync(FabricClient fabricClient, ServerSendRequestDto message, CancellationToken ct)
//    {
//        throw new NotImplementedException();
//    }

//    public Task SendRequestCancelled(FabricClient fabricClient, ServerSendRequestCancelledDto message, CancellationToken ct)
//    {
//        throw new NotImplementedException();
//    }

//    public Task StreamingRequest(FabricClient fabricClient, ServerStreamingRequestDto message, CancellationToken ct)
//    {
//        throw new NotImplementedException();
//    }
//}