using gAPI.AutoWssServer.Models;
using System.Linq;

namespace gAPI.AutoWssServer.Generators;

public class AutoWssExtensionGenerator : _BaseGenerator
{
    public AutoWssExtensionGenerator(
        Generator context)
    {
        Context = context;

        if (AutoWssExtension != null)
        {
            Name = AutoWssExtension.Name;
            Namespace = AutoWssExtension.Namespace;
        }
        else
        {
            Name = "AutoWssExtension";
            Namespace = "gAPI.Generated";
        }

        Directory = "";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference? AutoWssExtension => Context.SharedReferences.AutoWssExtension;


    public WssHub_Generator WssHub => Context.WssHub;
    public ClientServiceContext_Generator[] ClientContexts => Context.ClientContexts;
    public IClientContext_Generator IClientContext => Context.IClientContext;
    public ClientContext_Generator ClientContext => Context.ClientContext;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SseHostCollection => Context.SharedReferences.SseHostCollection;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference WssConnectionCollection => Context.SharedReferences.WssConnectionCollection;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference WssSessionCache => Context.SharedReferences.WssSessionCache;
    public SharedReference ServerAuthenticationAccessor => Context.SharedReferences.ServerAuthenticationAccessor;
    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference AutoWssExtensionAttribute => Context.SharedReferences.AutoWssExtensionAttribute;
    public SharedReference AddAutoWssServicesExtension => Context.AddAutoWssServicesExtension;

    public override void GenerateCode()
    {
        if (AutoWssExtension != null)
        {
            return;
        }

        Reg(WssHub);
        Reg(IClientContext);
        Reg(ClientContext);
        Reg(FabricClient);
        Reg(ServerConfig);
        Reg(WssConnectionCollection);
        Reg(SseHostCollection);
        Reg(IServerAuthenticationService);
        Reg(WssSessionCache);
        Reg(ServerAuthenticationAccessor);
        Reg(SessionId);
        Reg(AddAutoWssServicesExtension);
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.Extensions.Primitives");
        Reg("System.Net");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.Logging");

        foreach (var mini in Context.MinimalApis)
        {
            Reg(mini);
        }

        foreach (var clientHandlerContext in ClientContexts)
        {
            Reg(clientHandlerContext);
            Reg(clientHandlerContext.IClientContext);
        }
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.MinimalApiInterfaces.Where(a => a.FullName != "gAPI.Core.Interfaces.IAccountService"))
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        foreach (var apiInterface in Context.ServiceContext.ApiInterfaces)
        {
            if (apiInterface.Service == null)
                throw new System.Exception($"Service of {Name} not implemented");
        }

        Reg(AutoWssExtensionAttribute);
        Reg(AddAutoWssServicesExtension);

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

[{AutoWssExtensionAttribute}]
public static class {Name}
{{
    public static IServiceCollection AddAutoWss(this IServiceCollection services, {ServerConfig} serverConfig)
    {{
        return AddAutoWss(services, serverConfig.FrontendUrl, serverConfig.FabricConnectionString);
    }}
    public static IServiceCollection AddAutoWss(this IServiceCollection services, string frontendUrl, string? fabricConnectionString)
    {{
        services.AddHttpContextAccessor();
        services.AddCors(options =>
        {{
            options.AddPolicy(""AllowSpecificOrigin"", policy =>
            {{
                policy
                    .WithOrigins(frontendUrl)
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()
                    .WithExposedHeaders(""X-SessionId"", ""X-StateData"");
            }});
        }});
        services.AddScoped<{WssHub}>();
        services.AddSingleton(sp => new {FabricClient}(sp.GetRequiredService<ILoggerFactory>(), fabricConnectionString));

        var connectionCollection = new {WssConnectionCollection}();
        services.AddSingleton(connectionCollection);

        var sseHostCollection = new {SseHostCollection}();
        services.AddSingleton(sseHostCollection);

        var sessionCache = new {WssSessionCache}();
        services.AddSingleton(sessionCache);

        _ = Task.Run(async () =>
        {{
            while (true)
            {{
                sessionCache.Cleanup();
                await Task.Delay(TimeSpan.FromMinutes(5));
            }}
        }});

        services.AddAutoWssServices();

        return services;
    }}

    public static WebApplication MapAutoWss(this WebApplication app)
    {{
        app.UseForwardedHeaders(new ForwardedHeadersOptions
        {{
            ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
        }});

        app.UseCors(""AllowSpecificOrigin"");
        app.UseRouting();

        app.MapWss();

{(string.Join("", Context.MinimalApis.Select(Interface => $@"
        app.Map{Interface.Interface.CleanName}Endpoints();")))}

        app.UseWebSockets();
        return app;
    }}

    public static WebApplication MapWss(this WebApplication app)
    {{
        app.UseWebSockets();
        app.MapGet(""/fabricr"", async (
            [FromQuery] string sessionId,
            [FromServices] {WssSessionCache} sessionCache,
            [FromServices] {WssHub} hub,
            [FromServices] ILoggerFactory loggerFactory,
            HttpContext httpContext,
            CancellationToken ct) =>
        {{
            if (!httpContext.WebSockets.IsWebSocketRequest || 
                !sessionCache.TryGet(new {SessionId}(sessionId), out var cookieData))
            {{
                httpContext.Response.StatusCode = 400;
                return;
            }}

            try
            {{
                var forwardedIpHeader = httpContext.Request.Headers[""X-Forwarded-For""];
                IPAddress? forwardedIp = null;
                if (forwardedIpHeader.Any())
                {{
                    var forwardedIpString = forwardedIpHeader.First();
                    if (forwardedIpString != null)
                        forwardedIp = IPAddress.Parse(forwardedIpString);
                }}

                using var socket = await httpContext.WebSockets.AcceptWebSocketAsync();
                await hub.RunAsync(
                    socket,
                    httpContext.Request.Path,
                    httpContext.Request.QueryString,
                    forwardedIp ?? httpContext.Connection.RemoteIpAddress,
                    sessionId,
                    cookieData,
                    ct);
            }}
            catch (Exception ex)
            {{
                var logger = loggerFactory.CreateLogger(""gAPI.Generated.WssEndpoint"");
                logger.LogError(""Exception occured: {{ex}}"", ex);
            }}
        }});
        return app;
    }}
}}";

    }
}