using gAPI.AutoWssServer.Models;
using System.Linq;

namespace gAPI.AutoWssServer.Generators;

public class AutoWssServicesExtensionGenerator : _BaseGenerator
{
    public AutoWssServicesExtensionGenerator(
        Generator context)
    {
        Context = context;

        if (AutoWssExtension != null)
        {
            Name = AutoWssExtension.Name;
            Namespace = AutoWssExtension.Namespace;
        }
        else
        {
            Name = "AutoWssServicesExtension";
            Namespace = "gAPI.Generated";
        }

        Directory = "";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference? AutoWssExtension => Context.SharedReferences.AutoWssExtension;


    public WssHub_Generator WssHub => Context.WssHub;
    public ClientServiceContext_Generator[] ClientContexts => Context.ClientContexts;
    public IClientContext_Generator IClientContext => Context.IClientContext;
    public ClientContext_Generator ClientContext => Context.ClientContext;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SseHostCollection => Context.SharedReferences.SseHostCollection;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference WssConnectionCollection => Context.SharedReferences.WssConnectionCollection;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference WssSessionCache => Context.SharedReferences.WssSessionCache;
    public SharedReference ServerAuthenticationAccessor => Context.SharedReferences.ServerAuthenticationAccessor;
    public SharedReference SessionId => Context.SharedReferences.SessionId;

    public SharedReference AutoWssExtensionAttribute => Context.SharedReferences.AutoWssExtensionAttribute;

    public override void GenerateCode()
    {
        if (AutoWssExtension != null)
        {
            return;
        }

        Reg(WssHub);
        Reg(IClientContext);
        Reg(ClientContext);
        Reg(FabricClient);
        Reg(ServerConfig);
        Reg(WssConnectionCollection);
        Reg(SseHostCollection);
        Reg(IServerAuthenticationService);
        Reg(WssSessionCache);
        Reg(ServerAuthenticationAccessor);
        Reg(SessionId);
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.Extensions.Primitives");
        Reg("Microsoft.Extensions.DependencyInjection");

        foreach (var mini in Context.MinimalApis)
        {
            Reg(mini);
        }

        foreach (var clientHandlerContext in ClientContexts)
        {
            Reg(clientHandlerContext);
            Reg(clientHandlerContext.IClientContext);
        }
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.MinimalApiInterfaces.Where(a => a.FullName != "gAPI.Interfaces.IAccountService"))
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        foreach (var apiInterface in Context.ServiceContext.ApiInterfaces)
        {
            if (apiInterface.Service == null)
                throw new System.Exception($"Service of {Name} not implemented");
        }

        Reg(AutoWssExtensionAttribute);

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

[{AutoWssExtensionAttribute}]
public static class {Name}
{{
    public static IServiceCollection AddAutoWssServices(this IServiceCollection services)
    {{
        // Hubs
        services.AddScoped<{IClientContext}, {ClientContext}>();{string.Join("", ClientContexts.Select(a => $@"
        services.AddScoped<{a.IClientContext.Name}, {a.Name}>();"))}

        // Apis{string.Join("", Context.ServiceContext.ApiInterfaces.Select(apiinterface => $@"
        services.AddScoped<{apiinterface.Name}, {apiinterface.Service.Name}>();"))}

        // Minimal Apis{string.Join("", Context.ServiceContext.MinimalApiInterfaces.Select(apiinterface => $@"
        services.AddScoped<{apiinterface.Name}, {apiinterface.Service.Name}>();"))}

        return services;
    }}
}}";

    }
}