using gAPI.AutoWssServer.Helpers;
using gAPI.AutoWssServer.Models;
using System.Linq;

namespace gAPI.AutoWssServer.Generators;

public class IClientContext_Generator : _BaseGenerator
{
    public IClientContext_Generator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "IClientContext";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public WssHub_Generator WssHub => Context.WssHub;
    public ClientServiceContext_Generator[] ClientHandlerContexts => Context.ClientContexts;

    public override void GenerateCode()
    {
        foreach (var a in Context.ClientContexts)
        {
            Reg(a);
            Reg(a.IClientContext);
        }
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name}
{{{string.Join("", Context.ClientContexts.Select(a => $@"    
    public {a.IClientContext.Name} {a.Client.Interface.CleanName} {{ get; }}"))}
}}";
    }
}