using gAPI.AutoSerializer;
using gAPI.AutoWssServer.Helpers;
using gAPI.AutoWssServer.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWssServer.Generators;

public class WssHub_Generator : _BaseGenerator
{
    public WssHub_Generator(Generator context)
    {
        Context = context;

        if (WssHub != null)
        {
            Name = WssHub.Name;
            Namespace = WssHub.Namespace;
        }
        else
        {
            Namespace = "gAPI.Generated";
            Name = "WssHub";
        }

        Directory = "";
        FileName = $"{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }
    public SharedReference? WssHub => Context.SharedReferences.WssHub;
    public SharedReference WssHubAttribute => Context.SharedReferences.WssHubAttribute;

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference SseHostCollection => Context.SharedReferences.SseHostCollection;
    public SharedReference WssConnectionCollection => Context.SharedReferences.WssConnectionCollection;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference ApiSendRequestDto => Context.SharedReferences.ApiSendRequestDto;
    public SharedReference ApiInvokeRequestDto => Context.SharedReferences.ApiInvokeRequestDto;
    public SharedReference ApiInvokeResponseDto => Context.SharedReferences.ApiInvokeResponseDto;
    public SharedReference ApiInvokeResponseDoneDto => Context.SharedReferences.ApiInvokeResponseDoneDto;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Attributes");
        Reg("gAPI.Serializers");
        Reg("gAPI.Collections");
        Reg("gAPI.Dtos");
        Reg("gAPI.Fabric.Server");
        Reg("gAPI.Wss");
        Reg("gAPI.Ids");
        Reg("gAPI.Interfaces");
        Reg("Microsoft.CodeAnalysis");
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        Reg(WssHubAttribute);

        var functions = string.Empty;
        Code = @$"
// <auto-generated />
#nullable enable

namespace {Namespace};

[{WssHubAttribute}]
public class {Name} : WssConnection
{{
    readonly ILogger ___logger;
    readonly {IServerAuthenticationService} ___authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
    readonly {@interface} {@interface.CleanName};")))}
    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];

    public {Name}(
        {IServerAuthenticationService} authenticationService,
        {SseHostCollection} sseHostCollection,
        {WssConnectionCollection} connections,
        {FabricClient} fabricClient,{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        {@interface} {@interface.CleanName.ToCamelCase()},")))}
        ILoggerFactory loggerFactory) 
        : base(authenticationService, sseHostCollection, connections, fabricClient, loggerFactory)
    {{
        this.___authenticationService = authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        this.{@interface.CleanName} = {@interface.CleanName.ToCamelCase()};")))}
        this.___logger = loggerFactory.CreateLogger<WssHub>();
    }}

    protected override Task SendRequestAsync({ApiSendRequestDto} ___sendRequest, CancellationToken ___ct)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___sendRequest.BinaryData);
        switch (___sendRequest.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___sendRequest.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask).Select(method =>
                {
                    return $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___sendRequest,{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
                            {PropertyHelper.GenerateSpanReadCode(arg.ParameterType.Type, false, ref functions)},"))}
                            ___ct);";
                })))}
                }}
                break;")))}
        }}
        throw new Exception($""Send {{___sendRequest.ServiceId.Value}}.{{___sendRequest.MethodId.Value}} not implemented"");
    }}
    protected override Task InvokeRequestAsync({ApiInvokeRequestDto} ___invokeRequest, CancellationToken ___ct)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___invokeRequest.BinaryData);
        switch (___invokeRequest.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask == false)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___invokeRequest.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask == false).Select(method => $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___invokeRequest,{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
                            {PropertyHelper.GenerateSpanReadCode(arg.ParameterType.Type, false, ref functions)},"))}
                            ___ct);")))}
                }}
                break;")))}
        }}
        throw new Exception($""Invoke {{___invokeRequest.ServiceId.Value}}.{{___invokeRequest.MethodId.Value}} not implemented"");
    }}
{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask).Select(method => $@"
    public async Task {@interface}_{method}(
        {ApiSendRequestDto} ___sendRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg},"))}
        CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {@interface}_{method}({{___sendRequest}})"", ___sendRequest);

        await {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});
    }}")))))}
{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTaskT).Select(method => $@"
    public async Task {@interface}_{method}(
        {ApiInvokeRequestDto} ___invokeRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg},"))}
        CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var response = await {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});

        await Send_InvokeResponse_ToClientAsync(new {ApiInvokeResponseDto}()
            {{
                RequestId = ___invokeRequest.RequestId,
                ServiceId = ___invokeRequest.ServiceId,
                MethodId = ___invokeRequest.MethodId,
                SessionData = ___authenticationService.SessionData,
                StateData = ___authenticationService.IsStateChanged() ? await ___authenticationService.GetStateDataAsync(___ct) : null,
                BinaryData = {@interface}_{method}_Serializer(response)
            }}, ___ct);

        await Send_InvokeResponseDone_ToClientAsync(new {ApiInvokeResponseDoneDto}()
            {{
                RequestId = ___invokeRequest.RequestId,
                ServiceId = ___invokeRequest.ServiceId,
                MethodId = ___invokeRequest.MethodId,
                SessionData = ___authenticationService.SessionData,
                StateData = ___authenticationService.IsStateChanged() ? await ___authenticationService.GetStateDataAsync(___ct) : null
            }}, ___ct);
    }}")))))}
{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable).Select(method => $@"
    public async Task {@interface}_{method}(
        {ApiInvokeRequestDto} ___invokeRequest,{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg},"))}
        CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var responses = {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});

        await foreach (var response in responses)
        {{
            await Send_InvokeResponse_ToClientAsync(new {ApiInvokeResponseDto}()
                {{
                    RequestId = ___invokeRequest.RequestId,
                    ServiceId = ___invokeRequest.ServiceId,
                    MethodId = ___invokeRequest.MethodId,
                    SessionData = ___authenticationService.SessionData,
                    StateData = ___authenticationService.IsStateChanged() ? await ___authenticationService.GetStateDataAsync(___ct) : null,
                    BinaryData = {@interface}_{method}_Serializer(response)
                }}, ___ct);
        }}

        await Send_InvokeResponseDone_ToClientAsync(new {ApiInvokeResponseDoneDto}()
            {{
                RequestId = ___invokeRequest.RequestId,
                ServiceId = ___invokeRequest.ServiceId,
                MethodId = ___invokeRequest.MethodId,
                SessionData = ___authenticationService.SessionData,
                StateData = ___authenticationService.IsStateChanged() ? await ___authenticationService.GetStateDataAsync(___ct) : null
            }}, ___ct);
    }}")))))}

{string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable || a.ResponseType.IsTaskT).Select(method =>
    {
        var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
        return $@"

    public byte[] {@interface}_{method}_Serializer({returnTypeInner} value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___Buffer);{PropertyHelper.GenerateSpanWriteCode(returnTypeInner.Type, "value", "        ", false)}   
        return ___span.Slice(0, ___offset).ToArray();
    }}";
    }))))}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }
}