using gAPI.AutoSseClient.Models;

namespace gAPI.AutoSseClient.Generators;

public class ISseManagerGenerator : BaseGenerator
{
    public ISseManagerGenerator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "IClientConnection";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public ServiceContext DataModel => Context.ServiceContext;

    public SharedReference ISseClientConnection => Context.SharedReferences.ISseClientConnection;

    public override void GenerateCode()
    {
        Reg(ISseClientConnection);


        Code = @$"// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name} : {ISseClientConnection.Name}
{{
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }
}