using gAPI.AutoSseClient.Models;
using System.Linq;

namespace gAPI.AutoSseClient.Generators;

internal class ISseManagerGenerator : BaseGenerator
{
    internal ISseManagerGenerator(
        ServiceContext dataModel)
    {
        DataModel = dataModel;

        Directory = dataModel.Config.HubClients_Destination.Directory;
        Namespace = dataModel.Config.HubClients_Destination.Namespace;

        Name = "ISseManager";
        FileName = $"{Name}.g.cs";
    }

    public ServiceContext DataModel { get; }

    public void GenerateCode()
    {
        Reg(DataModel.ISseManagerBase);


        Code = @$"// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name} : {DataModel.ISseManagerBase.Name}
{{
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }
}