using gAPI.AutoSseClient.Models;
using System.Linq;

namespace gAPI.AutoSseClient.Generators;

internal class SseManagerGenerator : BaseGenerator
{
    internal SseManagerGenerator(
        ServiceContext dataModel,
        ISseManagerGenerator iSseManager,
        SseClientGenerator sseClient)
    {
        DataModel = dataModel;
        ISseManager = iSseManager;
        SseClient = sseClient;

        Directory = dataModel.Config.HubClients_Destination.Directory;
        Namespace = dataModel.Config.HubClients_Destination.Namespace;

        Name = "SseManager";
        FileName = $"{Name}.g.cs";
    }

    public ServiceContext DataModel { get; }
    public ISseManagerGenerator ISseManager { get; }
    public SseClientGenerator SseClient { get; }

    public void GenerateCode()
    {
        Reg("Newtonsoft.Json");
        Reg("System.Collections.Concurrent");
        Reg("System.Collections.Immutable");
        Reg(ISseManager);
        Reg(SseClient);
        Reg(DataModel.IClientAuthenticationService);
        Reg(DataModel.SseManagerCollection);
        Reg(DataModel.SseServiceId);


        Code = @$"// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name} : {ISseManager.Name}
{{
    private readonly {DataModel.IClientAuthenticationService.Name} ClientAuthenticationService;
    private readonly {DataModel.SseManagerCollection.Name} SseManagerCollection;
    private readonly CancellationTokenSource Cts = new();
    private readonly ConcurrentDictionary<{DataModel.SseServiceId.Name}, {SseClient.Name}> ServiceClients = new();
{string.Join("", DataModel.Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"
    private ImmutableArray<{i.Name}> {i.Title}s = [];";
        }))}

    public SseManagerId Id {{ get; }}

    public SseManager(
        {DataModel.IClientAuthenticationService.Name} clientAuthenticationService,
        {DataModel.SseManagerCollection.Name} sseManagerCollection)
    {{
        ClientAuthenticationService = clientAuthenticationService;
        SseManagerCollection = sseManagerCollection;
        Id = SseManagerCollection.Add(this);
    }}

    public async Task SubscribeAsync(object implementation)
    {{
        {string.Join("\r\n        else ", DataModel.Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"if (implementation is {i.Name} _{i.Name})
        {{
            var serviceId = new {DataModel.SseServiceId}(nameof({i.Name}));
            var client = ServiceClients.AddOrUpdate(
                serviceId,
                serviceId =>
                {{
                    var client = new SseClient(ClientAuthenticationService, this, serviceId);
                    ImmutableInterlocked.Update(ref {i.Title}s, list => list.Add(_{i.Name}));
                    _ = Task.Run(client.ConnectAsync);
                    return client;
                }},
                (service, client) =>
                {{
                    ImmutableInterlocked.Update(ref {i.Title}s, list => list.Add(_{i.Name}));
                    return client;
                }});
        }}";
        }))}{(DataModel.Interfaces.Length == 0 ? "" : $@"
        else 
        {{
            throw new NotImplementedException(""The SseManager doesn't recognise the component you are trying to register, please add the [GenerateHub] attribute to the interface you are trying to register."");
        }}")}
    }}

    public async Task UnsubscribeAsync(object implementation)
    {{
        {string.Join("\r\n        else ", DataModel.Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"if (implementation is {i.Name} _{i.Name})
        {{
            var serviceId = new {DataModel.SseServiceId}(nameof({i.Name}));
            ImmutableInterlocked.Update(ref {i.Title}s, list => list.Remove(_{i.Name}));
            if ({i.Title}s.Length == 0 &&
                ServiceClients.TryRemove(serviceId, out var client))
            {{
                await client.DisposeAsync();
            }}
        }}";
        }))}{(DataModel.Interfaces.Length == 0 ? "" : $@"
        else 
        {{
            throw new NotImplementedException(""The SseManager doesn't recognise the component you are trying to unregister, please add the [GenerateHub] attribute to the interface you are trying to unregister."");
        }}")}
    }}

    public async Task MessageReceivedAsync(SseMessage message, CancellationToken ct)
    {{
        switch (message.ServiceId.Value)
        {{{string.Join(Environment.NewLine, DataModel.Interfaces
        .Select(i =>
        {
            Reg(i);
            return $@"
            case ""{i.Name}"":
                switch(message.ServiceMethodId.Value)
                {{{string.Join(Environment.NewLine, i.Methods.Select(m =>
                    {
                        var hasCancellationToken = m.Arguments.Any(a => a.ParameterType.Name == "CancellationToken");
                        return $@"
                    case ""{m.Name}"":
                        var {m.Name.ToLower()} = 
                            JsonConvert.DeserializeObject<{i.Title}_{m.Name}>(message.Data);
                        if ({m.Name.ToLower()} == null) return;
                        foreach (var item in {i.Title}s)
                        {{
                            await item.{m.Name}({string.Join(",", m.Arguments
                                        .Where(a => a.ParameterType.Name != "CancellationToken")
                                        .Select(a => $@"
                                {m.Name.ToLower()}.{a.Name}"))}{(hasCancellationToken ? $@",
                                ct" : "")});
                        }}
                        break;";
                    }))}
                }}
                break;";
        }))}
        }}
    }}

    public async ValueTask DisposeAsync()
    {{
        Cts.Cancel();
        Cts.Dispose();
        foreach (var client in ServiceClients.Values)
        {{
            await client.DisposeAsync();
        }}
        SseManagerCollection.Remove(Id);
    }}{string.Join("", DataModel.Interfaces
        .Select(i =>
        {
            Reg(i);
            return string.Join("", i.Methods
                .Select(m =>
                {
                    return @$"

    public class {i.Title}_{m.Name}
    {{{string.Join("", m.Arguments
    .Where(a => a.ParameterType.Name != "CancellationToken")
    .Select(p =>
                    {
                        RegRange(p.ParameterType.Namespaces);
                        return @$"
        public {p.ParameterType.Name} {p.Name} {{ get; set; }}{(p.ParameterType.IsNullable || !p.ParameterType.IsReferenceType ? "" : " = null!;")}";
                    }))}
    }}";
                }));
        }))}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }
}