using gAPI.AutoWss.Server.Models;

namespace gAPI.AutoWss.Server.Generators.Apis;

public class ApiClientContext_Generator : _BaseGenerator
{
    public ApiClientContext_Generator(
        Generator context,
        IApiClientContext_Generator iClientHandlerContext)
    {
        Context = context;
        IClientContext = iClientHandlerContext;

        Namespace = iClientHandlerContext.Namespace;
        Name = Client.Interface.CleanName + "Context";

        Directory = "";
        FileName = $"Apis/{Name}.g.cs";
    }

    public Generator Context { get; }
    public IApiClientContext_Generator IClientContext { get; }

    public ApiClient_Generator Client => IClientContext.ClientHandler;
    public Interface IClient => Client.Interface;
    public SharedReference ServerConnection => Context.ServerConnection;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;

    public override void GenerateCode()
    {
        Reg(ServerConnection);
        Reg(IClientContext);
        Reg(FabricClient);
        Reg(IClient);
        Reg(Client);
        Reg(UserId);
        Reg(SessionId);
        Reg(IServerAuthenticationService);
        Reg("Microsoft.Extensions.Logging");
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {FabricClient} fabricClient,
    ILoggerFactory loggerFactory)
    : {IClientContext}
{{
    public {IClient} ToAll
        => new {Client}(fabricClient, loggerFactory, null, null);
    public {IClient} ToUser({UserId} userId)
        => new {Client}(fabricClient, loggerFactory, null, userId);
    public {IClient} ToSession({SessionId} sessionId)
        => new {Client}(fabricClient, loggerFactory, sessionId, null);
}}";
    }
}