//using gAPI.AutoWss.Server.Models;

//namespace gAPI.AutoWss.Server.Generators.Apis;

//public class ServiceRouter_Generator : _BaseGenerator
//{
//    public ServiceRouter_Generator(Generator context)
//    {
//        Context = context;

//        OwnServiceRouter = context.SharedReferences.OwnServiceRouter;
//        if (OwnServiceRouter != null)
//        {
//            Namespace = OwnServiceRouter.Namespace;
//            Name = OwnServiceRouter.Name;
//        }
//        else
//        {
//            Namespace = "gAPI.Generated";
//            Name = "ServiceRouter";
//        }

//        FileName = $"Apis/{Name}.g.cs";
//        Directory = "";
//    }

//    public Generator Context { get; }
//    public SharedReference? OwnServiceRouter { get; }

//    public SharedReference IServiceRouter => Context.SharedReferences.IServiceRouter;

//    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
//    public SharedReference ServerSendRequestDto => Context.SharedReferences.ServerSendRequestDto;
//    public SharedReference ServerSendRequestCancelledDto => Context.SharedReferences.ServerSendRequestCancelledDto;
//    public SharedReference ServerInvokeRequestDto => Context.SharedReferences.ServerInvokeRequestDto;
//    public SharedReference ServerInvokeRequestCancelledDto => Context.SharedReferences.ServerInvokeRequestCancelledDto;
//    public SharedReference ServerStreamingRequestDto => Context.SharedReferences.ServerStreamingRequestDto;

//    public override void GenerateCode()
//    {
//        if (OwnServiceRouter != null)
//        {
//            Code = "";
//            return;
//        }

//        Reg(IServiceRouter);
//        Reg(FabricClient);
//        Reg(ServerSendRequestDto);
//        Reg(ServerSendRequestCancelledDto);
//        Reg(ServerInvokeRequestDto);
//        Reg(ServerInvokeRequestCancelledDto);
//        Reg(ServerStreamingRequestDto);
//        Reg("System");
//        Reg("System.Threading");
//        Code = @$"{GetNamespacesCode()}
//// <auto-generated />
//#nullable enable
//namespace {Namespace};

//public class {Name}(
//    IServiceProvider serviceProvider)
//    : {IServiceRouter}
//{{
//    public IAsyncEnumerable<byte[]> InvokeRequestAsync(FabricClient fabricClient, ServerInvokeRequestDto message, CancellationToken ct)
//    {{
//        throw new NotImplementedException();
//    }}

//    public Task InvokeRequestCancelled(FabricClient fabricClient, ServerInvokeRequestCancelledDto message, CancellationToken ct)
//    {{
//        throw new NotImplementedException();
//    }}

//    public Task SendRequestAsync(FabricClient fabricClient, ServerSendRequestDto message, CancellationToken ct)
//    {{
//        throw new NotImplementedException();
//    }}

//    public Task SendRequestCancelled(FabricClient fabricClient, ServerSendRequestCancelledDto message, CancellationToken ct)
//    {{
//        throw new NotImplementedException();
//    }}
//}}";
//    }
//}
