using gAPI.AutoApiClient.Models;
using gAPI.AutoSerializer;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApiClient.Generators;

public class ApiClientGenerator : BaseGenerator
{
    public ApiClientGenerator(Generator context, Interface @interface, CustomObjectMethod[] customMultipartFormDataContentSerializers)
    {
        Interface = @interface;
        Context = context;

        Directory = "";
        Namespace = @interface.Namespace;

        Name = Interface.CleanName;
        FileName = $"{Name}.g.cs";

        TypeSymbol = @interface.NamedTypeSymbol;

        PropertyHelper = new GeneratePropertyHelper([], [], customMultipartFormDataContentSerializers, Reg, NeededSerializers);
    }

    public Interface Interface { get; }
    public Generator Context { get; }

    public SharedReference IClientAuthenticatedHttpClient => Context.SharedReferences.IClientAuthenticatedHttpClient;

    public List<INamedTypeSymbol> NeededSerializers { get; } = [];
    public INamedTypeSymbol TypeSymbol { get; }
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg(Interface);
        Reg("Microsoft.Extensions.Logging");
        Reg("System.Net.Http.Json");
        Reg("System.Net.Http.Headers");
        Reg("Microsoft.AspNetCore.Http");
        Reg("System.Globalization");
        Reg("gAPI.Core.Extensions");
        Reg("gAPI.Core.Dtos");
        Reg("System.Globalization");

        var methods = string.Join("", Interface.Methods.Select(method => GenerateMethod(method)));

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {IClientAuthenticatedHttpClient.FullName} clientAuthenticationService) 
    : {Interface.Name}
    , IDisposable
{{
    private readonly CancellationTokenSource Cts = new();{methods}

    public void Dispose()
    {{
        Cts.Dispose();
    }}
}}";
    }

    private string GenerateMethod(InterfaceMethod method)
    {
        if (!method.ResponseType.IsTask && !method.ResponseType.IsTaskT) return "";

        Reg(method.ResponseType);
        foreach (var arg in method.Arguments)
        {
            Reg(arg.ParameterType);
        }

        var args = method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).ToArray();
        var cancellationToken = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);


        var skipTakeQueryItems = method.Arguments
            .Where(a => a.Name == "skip" || a.Name == "take");

        var arguments = string.Join(",", method.Arguments.Select(arg => $@"
        {arg.ParameterType} {arg}"));
        var writeProps =
                method.IsList || method.IsListBy || method.IsListNotBy
                ? $@"
        var queryItems = new List<string>();{string.Join("", skipTakeQueryItems.Select(a => $@"
        if ({a.Name} != null)
            queryItems.Add($""{a.Name}={{{a.Name}}}"");"))}"
                : string.Join(
            "",
            args.Select(arg => {
                Reg(arg.ParameterType.Type);
                var code = PropertyHelper.GenerateMultipartFormDataContentWriteCode(
                    arg.ParameterType.Type,
                    arg.Name,
                    arg.Name,
                    "        ",
                    false,
                    true
                );
                return code;
            }));
        var responseCode = GenerateResponse(method, args, cancellationToken);
        var returnCode = GenerateReturn(method, args, cancellationToken);

        return $@"

    public async {method.ResponseType} {method}({arguments})
    {{
        var ___content = new MultipartFormDataContent();{writeProps}

{responseCode}{returnCode}
    }}";
    }
    private string GenerateResponse(InterfaceMethod method, InterfaceMethodArgument[] args, InterfaceMethodArgument cancellationToken)
    {

        var code = "";
        if (args.Length == 0)
        {
            code += $"        using var response = await clientAuthenticationService.GetAsync(\"/{Interface.CleanName}/{method.Name}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsList)
        {
            code += $"        var query = $\"{{(queryItems.Count > 0 ? \"?\" : \"\")}}{{string.Join(\"&\", queryItems)}}\";\r\n";
            code += $"        using var response = await clientAuthenticationService.GetAsync($\"/{Interface.CleanName}/{method.Name}{{query}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsListBy || method.IsListNotBy)
        {
            var idArg = method.Arguments
                .First(a => a.Name != "skip" && a.Name != "take" && a.Name != "orderby");
            code += $"        var query = $\"{{(queryItems.Count > 0 ? \"?\" : \"\")}}{{string.Join(\"&\", queryItems)}}\";\r\n";
            code += $"        using var response = await clientAuthenticationService.GetAsync($\"/{Interface.CleanName}/{method.Name}/{{{idArg.Name}}}{{query}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsRead)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.GetAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsDelete)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.DeleteAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsUpdate)
        {
            code += $"        using var response = await clientAuthenticationService.PutAsync($\"/{Interface.CleanName}/{method.Name}\", ___content{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsFileUpdate)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.PutAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\", ___content{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsFileDelete)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.DeleteAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else
        {
            code += $"        using var response = await clientAuthenticationService.PostAsync(\"/{Interface.CleanName}/{method.Name}\", ___content{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        return code;
    }
    private string GenerateReturn(InterfaceMethod method, InterfaceMethodArgument[] args, InterfaceMethodArgument cancellationToken)
    {

        var orderByQueryItem = method.Arguments
            .Where(a => a.Name == "orderby")
            .FirstOrDefault();

        var skipTakeQueryItems = method.Arguments
            .Where(a => a.Name == "skip" || a.Name == "take");

        var underlaying = method.ResponseType.UnderlayingTypes.FirstOrDefault();

        var methodType =
            underlaying == null
            ? $"Task"
            : $"Task<{method.ResponseType.UnderlayingTypes[0].Name}>";

        var responseType =
            underlaying == null
            ? "BaseResponse"
            : (underlaying.IsBaseResponse || underlaying.IsBaseResponseT || underlaying.IsBaseListResponseT)
                ? underlaying.Name
                : $"BaseResponseT<{underlaying.Name}>";

        return $@"
        response.EnsureSuccessStatusCode();

        var responseData = await response.Content.ReadFromJsonAsync<{responseType}>({(cancellationToken != null ? $"{cancellationToken.Name}" : "Cts.Token")})
            ?? throw new Exception(""Could not cast response data"");{(
                underlaying == null
                ? ""
                :
                    underlaying.IsBaseResponse ||
                    underlaying.IsBaseResponseT ||
                    underlaying.IsBaseListResponseT
                    ? $@"
        return responseData;"
                    :
                        underlaying.IsNullable || underlaying.Name == "bool"
                        ? @"
        return responseData.Response;" :
                            underlaying.IsValueType
                            ? @"
        return responseData.Response!;"
                        : @"
        return responseData.Response
            ?? throw new Exception(""Could not cast response data"");")}";
    }
}