using gAPI.AutoSse.Client.Models;

namespace gAPI.AutoSse.Client.Generators;

public class AddAutoSseExtensionGenerator : BaseGenerator
{
    public AddAutoSseExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AutoSseExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference ClientConnection => Context.ClientConnection;
    public SharedReference IClientConnection => Context.SharedReferences.ISseClientConnection;
    public SharedReference SseManagerCollection => Context.SharedReferences.SseManagerCollection;

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg(ClientConnection);
        Reg(IClientConnection);
        Reg(SseManagerCollection);
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoSse(this IServiceCollection services)
    {{
        services.AddScoped<{ClientConnection}>();
        services.AddScoped<{IClientConnection}>(sp => sp.GetRequiredService<{ClientConnection}>());

        var sseManagerCollection = new {SseManagerCollection}();
        services.AddSingleton(sseManagerCollection);

        return services;
    }}
}}";
    }
}