using gAPI.AutoSseClient.Models;
using System.Linq;

namespace gAPI.AutoSseClient.Generators;

public class ClientConnectionGenerator : BaseGenerator
{
    public ClientConnectionGenerator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "ClientConnection";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public ServiceContext DataModel => Context.ServiceContext;
    public SharedReference SseClient => Context.SharedReferences.SseClient;

    public Interface[] Interfaces => Context.ServiceContext.HubInterfaces;

    public SharedReference IClientAuthenticationService => Context.SharedReferences.IClientAuthenticatedHttpClient;
    public SharedReference SseManagerCollection => Context.SharedReferences.SseManagerCollection;
    public SharedReference SseServiceId => Context.SharedReferences.ServiceId;
    public SharedReference SendRequestDto => Context.SharedReferences.SendRequestDto;
    public SharedReference SseManagerId => Context.SharedReferences.SseManagerId;
    public SharedReference IClientConnection => Context.SharedReferences.IClientConnection;

    public override void GenerateCode()
    {
        Reg("System.Text.Json");
        Reg("System.Collections.Concurrent");
        Reg("System.Collections.Immutable");
        Reg("System.Text");
        Reg(IClientConnection);
        Reg(SseClient);
        Reg(IClientAuthenticationService);
        Reg(SseManagerCollection);
        Reg(SseServiceId);
        Reg(SendRequestDto);
        Reg(SseManagerId);


        Code = @$"// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name} : {IClientConnection.Name}
{{
    private readonly {IClientAuthenticationService.Name} ClientAuthenticationService;
    private readonly {SseManagerCollection.Name} SseManagerCollection;
    private readonly CancellationTokenSource Cts = new();
    private readonly ConcurrentDictionary<{SseServiceId.Name}, {SseClient.Name}> ServiceClients = new();
{string.Join("", Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"
    private ImmutableArray<{i.Name}> {i.Title}s = [];";
        }))}

    public {SseManagerId} Id {{ get; }}

    public {Name}(
        {IClientAuthenticationService.Name} clientAuthenticationService,
        {SseManagerCollection.Name} sseManagerCollection)
    {{
        ClientAuthenticationService = clientAuthenticationService;
        SseManagerCollection = sseManagerCollection;
        Id = SseManagerCollection.Add(this);
    }}

    public void SubscribeAsync(object implementation)
    {{
        {string.Join("\r\n        else ", Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"if (implementation is {i.Name} _{i.Name})
        {{
            var serviceId = new {SseServiceId}(nameof({i.Name}));
            var client = ServiceClients.AddOrUpdate(
                serviceId,
                serviceId =>
                {{
                    var client = new SseClient(ClientAuthenticationService, this, serviceId);
                    ImmutableInterlocked.Update(ref {i.Title}s, list => list.Add(_{i.Name}));
                    _ = Task.Run(client.ConnectAsync);
                    return client;
                }},
                (service, client) =>
                {{
                    ImmutableInterlocked.Update(ref {i.Title}s, list => list.Add(_{i.Name}));
                    return client;
                }});
        }}";
        }))}{(Interfaces.Length == 0 ? "" : $@"
        else 
        {{
            throw new NotImplementedException(""The SseManager doesn't recognise the component you are trying to register, please add the [GenerateHub] attribute to the interface you are trying to register."");
        }}")}
    }}

    public void UnsubscribeAsync(object implementation)
    {{
        {string.Join("\r\n        else ", Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"if (implementation is {i.Name} _{i.Name})
        {{
            var serviceId = new {SseServiceId}(nameof({i.Name}));
            ImmutableInterlocked.Update(ref {i.Title}s, list => list.Remove(_{i.Name}));
            if ({i.Title}s.Length == 0 &&
                ServiceClients.TryRemove(serviceId, out var client))
            {{
                client.Dispose();
            }}
        }}";
        }))}{(Interfaces.Length == 0 ? "" : $@"
        else 
        {{
            throw new NotImplementedException(""The SseManager doesn't recognise the component you are trying to unregister, please add the [GenerateHub] attribute to the interface you are trying to unregister."");
        }}")}
    }}

    public async Task MessageReceivedAsync({SendRequestDto} message, CancellationToken ct)
    {{{(Interfaces.Length > 0 ? $@"
        switch (message.ServiceId.Value)
        {{{string.Join("\r\n", Interfaces
        .Select(i =>
        {
            Reg(i);
            return $@"
            case ""{i.Name}"":
                switch(message.MethodId.Value)
                {{{string.Join("\r\n", i.Methods.Select(m =>
                    {
                        var hasCancellationToken = m.Arguments.Any(a => a.ParameterType.Name == "CancellationToken");
                        return $@"
                    case ""{m.Name}"":
                        var {m.Name.ToLower()} = 
                            JsonSerializer.Deserialize<{i.Title}_{m.Name}>(
                                Encoding.UTF8.GetString(message.BinaryData));
                        if ({m.Name.ToLower()} == null) return;
                        foreach (var item in {i.Title}s)
                        {{
                            await item.{m.Name}({string.Join(",", m.Arguments
                                        .Where(a => a.ParameterType.Name != "CancellationToken")
                                        .Select(a => $@"
                                {m.Name.ToLower()}.{a.Name}"))}{(hasCancellationToken ? $@",
                                ct" : "")});
                        }}
                        break;";
                    }))}
                }}
                break;";
        }))}
        }}" : "")}
    }}

    public void Dispose()
    {{
        Cts.Cancel();
        Cts.Dispose();
        foreach (var client in ServiceClients.Values)
        {{
            client.Dispose();
        }}
        SseManagerCollection.Remove(Id);
    }}{string.Join("", Interfaces
        .Select(i =>
        {
            Reg(i);
            return string.Join("", i.Methods
                .Select(m =>
                {
                    return @$"

    public class {i.Title}_{m.Name}
    {{{string.Join("", m.Arguments
    .Where(a => a.ParameterType.Name != "CancellationToken")
    .Select(p =>
                    {
                        RegRange(p.ParameterType.Namespaces);
                        return @$"
        public {p.ParameterType.Name} {p.Name} {{ get; set; }}{(p.ParameterType.IsNullable || !p.ParameterType.IsReferenceType ? "" : " = null!;")}";
                    }))}
    }}";
                }));
        }))}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }
}