using gAPI.AutoWssServer.Models;

namespace gAPI.AutoWssServer.Generators;

public class ClientServiceContext_Generator : _BaseGenerator
{
    public ClientServiceContext_Generator(
        Generator context,
        IClientServiceContext_Generator iClientHandlerContext)
    {
        Context = context;
        IClientContext = iClientHandlerContext;

        Namespace = iClientHandlerContext.Namespace;
        Name = Client.Interface.CleanName + "Context";

        Directory = "";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public IClientServiceContext_Generator IClientContext { get; }

    public ClientService_Generator Client => IClientContext.ClientHandler;
    public Interface IClient => Client.Interface;
    public SharedReference WssHub => Context.WssHub;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference SessionId => Context.SharedReferences.SessionId;

    public override void GenerateCode()
    {
        Reg(WssHub);
        Reg(IClientContext);
        Reg(FabricClient);
        Reg(IClient);
        Reg(Client);
        Reg(UserId);
        Reg(SessionId);
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {FabricClient} fabricClient,
    ILoggerFactory loggerFactory)
    : {IClientContext}
{{
    public {IClient} ToAll
        => new {Client}(fabricClient, loggerFactory, null, null);
    public {IClient} ToUser({UserId} userId)
        => new {Client}(fabricClient, loggerFactory, null, userId);
    public {IClient} ToSession({SessionId} sessionId)
        => new {Client}(fabricClient, loggerFactory, sessionId, null);
}}";
    }
}