using gAPI.AutoSerializer;
using gAPI.AutoWssServer.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWssServer.Generators;

public class ClientService_Generator : _BaseGenerator
{
    public ClientService_Generator(Generator context, Interface @interface)
    {
        Context = context;
        Interface = @interface;

        Directory = "";
        Namespace = @interface.Namespace;

        Name = Interface.CleanName;
        FileName = $"{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }
    public Interface Interface { get; }
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;

    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference ServiceMethodId => Context.SharedReferences.ServiceMethodId;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Attributes");
        Reg("gAPI.Serializers");
        Reg("System.Runtime.CompilerServices");
        Reg(Interface);
        Reg(FabricClient);
        Reg(SessionId);
        Reg(UserId);
        Reg(ServiceId);
        Reg(ServiceMethodId);

        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }

        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }
        var functions = string.Empty;
        Code = @$"
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {FabricClient} ___fabricClient,
    ILoggerFactory ___loggerFactory,
    {SessionId}? ___sessionId,
    {UserId}? ___userId)
    : {Interface}
    , IDisposable
{{
    readonly CancellationTokenSource ___cts = new();
    readonly ILogger ___Logger = ___loggerFactory.CreateLogger<{Name}>();
    readonly {ServiceId} ___serviceId = new(""{Interface.Name}"");
{string.Join("", Interface.Methods.Where(a => a.ResponseType.IsTask).Select(method =>
{
    var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
    return $@"
    public async Task {method.Name}({string.Join(",", method.Arguments.Select(arg => $@"
        {arg.ParameterType.Name} {arg.Name}"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {method.Name}({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg.Name}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg.Name}"))});

        var serviceMethodId = new {ServiceMethodId}(""{method.Name}"");
        var payload = {Interface}_{method}_Serializer({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
            {arg}"))});
        await ___fabricClient.SendAsync(___serviceId, serviceMethodId, ___userId, ___sessionId, payload, {(ct == null ? "___cts.Token" : ct.Name)});
    }}";
}))}
{string.Join("", Interface.Methods.Where(a => a.ResponseType.IsTask == false).Select(method =>
{
    var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
    var responseInnerType = method.ResponseType.UnderlayingTypes.Single();
    return $@"
    public async {method.ResponseType} {method.Name}({string.Join(",", method.Arguments.Select(arg => $@"
        {(arg.ParameterType.IsCancellationToken ? "[EnumeratorCancellation] " : "")}{arg.ParameterType.Name} {arg.Name}"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {method.Name}({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg.Name}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg.Name}"))});

        var serviceMethodId = new {ServiceMethodId}(""{method.Name}"");
        var payload = {Interface}_{method}_Serializer({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
            {arg}"))});

        var responses = ___fabricClient.InvokeAsync(___serviceId, serviceMethodId, ___userId, ___sessionId, payload, {(ct == null ? "___cts.Token" : ct.Name)});
        await foreach (var response in responses)
        {{
            if (ct.IsCancellationRequested)
                yield break;

            var ___offset = 0;
            var ___span = new Span<byte>(response.BinaryData);
            yield return {PropertyHelper.GenerateSpanReadCode(responseInnerType.Type, false, ref functions)};
        }}
    }}"; }))}
{string.Join("", Interface.Methods.Select(method => $@"
    public byte[] {Interface}_{method}_Serializer({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg}"))})
    {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false) ? $@"
        var ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => PropertyHelper.GenerateLengthCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        var ___length = ___offset;
        ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => PropertyHelper.GenerateSpanWriteCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        if (___length != ___offset)
            throw new Exception($""Binary length doesn't match: {{___length}} != {{___offset}}"");
        return ___buffer;" : $@"
        return [];")}
    }}"))}

    public void Dispose()
    {{
        ___cts.Cancel();
        ___cts.Dispose();
    }}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }

}