using gAPI.AutoWssServer.Helpers;
using System.Linq;

namespace gAPI.AutoWssServer.Generators;

public class ClientContext_Generator : _BaseGenerator
{
    public ClientContext_Generator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "ClientContext";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public IClientContext_Generator IClientContext => Context.IClientContext;

    public override void GenerateCode()
    {
        Reg(IClientContext);
        foreach (var a in Context.ClientContexts)
        {
            Reg(a);
            Reg(a.IClientContext);
        }
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}({string.Join(",", Context.ClientContexts.Select(a => $@"    
    {a.IClientContext.Name} {a.Client.Interface.CleanName.ToCamelCase()}"))})
    : {IClientContext.Name}
{{{string.Join("", Context.ClientContexts.Select(a => $@"    
    public {a.IClientContext.Name} {a.Client.Interface.CleanName} {{ get; }} = {a.Client.Interface.CleanName.ToCamelCase()};"))}
}}";
    }
}