using gAPI.AutoApiSse.Client.Models;
using System.Linq;

namespace gAPI.AutoApiSse.Client.Generators.Sse;

public class IClientConnectionGenerator : _BaseGenerator
{
    public IClientConnectionGenerator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "IClientConnection";
        FileName = $"Sse/{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference ISseClientConnection => Context.SharedReferences.ISseClientConnection;

    public override void GenerateCode()
    {
        Reg(ISseClientConnection);

        Code = @$"// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name} : {ISseClientConnection}
{{
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }
}