using gAPI.AutoApi.Server.Models;

namespace gAPI.AutoApi.Server.Generators.Hubs;

public class HubClientContext_Generator : BaseGenerator
{
    public HubClientContext_Generator(
        Generator context,
        IHubClientContext_Generator iClientContext)
    {
        Context = context;
        IClientContext = iClientContext;

        Directory = "";
        Namespace = iClientContext.Namespace;

        Name = Interface.CleanName + "Context";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public IHubClientContext_Generator IClientContext { get; }

    public Interface Interface => IClientContext.Interface;
    public ServiceContext DataModel => Context.ServiceContext;
    public HubClient_Generator SseService => IClientContext.SseService;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference SessionId => Context.SharedReferences.SessionId;

    public override void GenerateCode()
    {
        Reg(IClientContext);
        Reg(Interface);
        Reg(SseService);
        Reg(FabricClient);
        Reg(UserId);
        Reg(SessionId);
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {FabricClient} fabricClient)
    : {IClientContext.Name}
{{
    public {Interface.Name} ToAll
        => new {SseService.Name}(fabricClient);
    public {Interface.Name} ToUser({UserId} userId)
        => new {SseService.Name}(fabricClient, userId);
    public {Interface.Name} ToSession({SessionId} sessionId)
        => new {SseService.Name}(fabricClient, null, sessionId);
}}
";
    }
}