using gAPI.AutoApi.Server.Models;

namespace gAPI.AutoApi.Server.Generators.Hubs;

public class IHubClientContext_Generator : BaseGenerator
{
    public IHubClientContext_Generator(
        Generator context,
        HubClient_Generator sseService)
    {
        Context = context;
        SseService = sseService;

        Directory = "";
        Namespace = sseService.Namespace;

        Name = $"I{sseService.Interface.CleanName}Context";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public HubClient_Generator SseService { get; }

    public Interface Interface => SseService.Interface;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference SessionId => Context.SharedReferences.SessionId;

    public override void GenerateCode()
    {
        Reg(Interface);
        Reg(SseService);
        Reg(UserId);
        Reg(SessionId);
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name}
{{
    {Interface.Name} ToAll {{ get; }}
    {Interface.Name} ToUser({UserId} userId);
    {Interface.Name} ToSession({SessionId} sessionId);
}}
";
    }
}