using gAPI.AutoWss.Server.Generators.Hubs;
using gAPI.AutoWss.Server.Generators.Wss;
using gAPI.AutoWss.Server.Models;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Startup;

public class AddAutoWssServerExtensionGenerator : _BaseGenerator
{
    public AddAutoWssServerExtensionGenerator(
        Generator context)
    {
        Context = context;

        Name = "AddAutoWssServerExtension";
        Namespace = "gAPI.Generated";

        Directory = "";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }

    public WssHub_Generator WssHub => Context.WssHub;
    public ClientServiceContext_Generator[] ClientContexts => Context.ClientContexts;
    public IClientContext_Generator IClientContext => Context.IClientContext;
    public ClientContext_Generator ClientContext => Context.ClientContext;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SseHostCollection => Context.SharedReferences.SseHostCollection;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference WssServerConnectionCollection => Context.SharedReferences.WssServerConnectionCollection;
    public SharedReference WssSessionCache => Context.SharedReferences.WssSessionCache;
    public SharedReference ServerAuthenticationAccessor => Context.SharedReferences.ServerAuthenticationAccessor;
    public SharedReference SessionId => Context.SharedReferences.SessionId;

    public override void GenerateCode()
    {
        Reg(WssHub);
        Reg(IClientContext);
        Reg(ClientContext);
        Reg(FabricClient);
        Reg(ServerConfig);
        Reg(WssServerConnectionCollection);
        Reg(SseHostCollection);
        Reg(WssSessionCache);
        Reg(ServerAuthenticationAccessor);
        Reg(SessionId);
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.Extensions.Primitives");
        Reg("System.Net");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.Logging");
        Reg("gAPI.Core.Server.Extensions");

        foreach (var mini in Context.MinimalApis)
        {
            Reg(mini);
        }

        foreach (var clientHandlerContext in ClientContexts)
        {
            Reg(clientHandlerContext);
            Reg(clientHandlerContext.IClientContext);
        }
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.MinimalApiInterfaces.Where(a => a.FullName != "gAPI.Core.Interfaces.IAccountService"))
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        foreach (var apiInterface in Context.ServiceContext.ApiInterfaces)
        {
            if (apiInterface.Service == null)
                throw new System.Exception($"Service of {Name} not implemented");
        }

        Reg("Microsoft.Extensions.DependencyInjection.Extensions");
        Reg("gAPI.Core.Server");
        Reg("gAPI.Core.Server.Authentication");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoWssServer(
        this IServiceCollection services,
        IConfigurationManager configuration,
        TimeProvider? dateTime = null)
    {{
        var config = configuration.CreateServerConfig();
        return AddAutoWssServer(
            services, 
            config,
            dateTime);
    }}

    public static IServiceCollection AddAutoWssServer(
        this IServiceCollection services, 
        {ServerConfig} config,
        TimeProvider? dateTime = null)
    {{
        return AddAutoWssServer(
            services, 
            config.FrontendUrl,
            config.FabricConnectionString,
            dateTime);
    }}

    public static IServiceCollection AddAutoWssServer(
        this IServiceCollection services,
        string? fabricConnectionString = null,
        string? frontendUrl = null,
        TimeProvider? dateTime = null)
    {{
        services.AddSingleton(dateTime ?? TimeProvider.System);

        services.AddHttpContextAccessor();
        if (frontendUrl != null)
        {{
            services.AddCors(options =>
            {{
                options.AddPolicy(""AllowSpecificOrigin"", policy =>
                {{
                    policy
                        .WithOrigins(frontendUrl)
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowCredentials()
                        .WithExposedHeaders(""X-SessionId"", ""X-StateData"");
                }});
            }});
        }}
        services.AddScoped<{WssHub}>();
        services.AddSingleton(sp => new {FabricClient}(
            sp.GetRequiredService<{WssSessionCache}>(),
            sp.GetRequiredService<ILoggerFactory>(), 
            fabricConnectionString));

        var connectionCollection = new {WssServerConnectionCollection}();
        services.AddSingleton(connectionCollection);

        var sseHostCollection = new {SseHostCollection}();
        services.AddSingleton(sseHostCollection);

        var sessionCache = new {WssSessionCache}();
        services.AddSingleton(sessionCache);

        if (fabricConnectionString == null)
        {{
            // Session cleaner, niet nodig als de fabric wordt gebruikt.
            _ = Task.Run(async () =>
            {{
                while (true)
                {{
                    sessionCache.Cleanup();
                    await Task.Delay(TimeSpan.FromMinutes(5));
                }}
            }});
        }}

        // Hubs
        services.AddScoped<{IClientContext}, {ClientContext}>();{string.Join("", ClientContexts.Select(a => $@"
        services.AddScoped<{a.IClientContext.Name}, {a.Name}>();"))}

        // Apis{string.Join("", Context.ServiceContext.ApiInterfaces.Select(apiinterface => $@"
        services.AddScoped<{apiinterface.Name}, {apiinterface.Service.Name}>();"))}

        // Minimal Apis{string.Join("", Context.ServiceContext.MinimalApiInterfaces
            .Where(a => a.FullName != "gAPI.Core.Interfaces.IAccountService")
            .Select(apiinterface => $@"
        services.AddScoped<{apiinterface.Name}, {apiinterface.Service.Name}>();"))}

        return services;
    }}
}}";

    }
}