using gAPI.AutoWss.Server.Generators.Hubs;
using gAPI.AutoWss.Server.Models;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Startup;

public class MapAutoWssServerExtensionGenerator : _BaseGenerator
{
    public MapAutoWssServerExtensionGenerator(
        Generator context)
    {
        Context = context;

        Name = "MapAutoWssServerExtension";
        Namespace = "gAPI.Generated";

        Directory = "";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }

    public ClientServiceContext_Generator[] ClientContexts => Context.ClientContexts;

    public override void GenerateCode()
    {
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.Extensions.Primitives");
        Reg("System.Net");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.Logging");

        foreach (var mini in Context.MinimalApis)
        {
            Reg(mini);
        }

        foreach (var clientHandlerContext in ClientContexts)
        {
            Reg(clientHandlerContext);
            Reg(clientHandlerContext.IClientContext);
        }
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.MinimalApiInterfaces.Where(a => a.FullName != "gAPI.Core.Interfaces.IAccountService"))
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        foreach (var apiInterface in Context.ServiceContext.ApiInterfaces)
        {
            if (apiInterface.Service == null)
                throw new System.Exception($"Service of {Name} not implemented");
        }

        Reg("Microsoft.Extensions.DependencyInjection.Extensions");
        Reg("gAPI.Core.Server");
        Reg("gAPI.Core.Server.Authentication");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static WebApplication MapAutoWssServer(this WebApplication app)
    {{
        app.UseForwardedHeaders(new ForwardedHeadersOptions
        {{
            ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
        }});

        app.UseCors(""AllowSpecificOrigin"");
        app.UseRouting();
        
        // State endpoint
        app.MapGet(""/__state"", ([FromHeader(Name = ""X-SessionId"")] string sessionId) => {{ }}).AllowAnonymous();

        // Wss endpoint
        app.MapWssEndpoint();

        // Minimal api endpoints
{(string.Join("", Context.MinimalApis.Select(Interface => $@"
        app.Map{Interface.Interface.CleanName}Endpoints();")))}

        return app;
    }}
}}";

    }
}