using gAPI.AutoWss.Server.Models;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Startup;

public class MapAutoWssServerExtensionGenerator : _BaseGenerator
{
    public MapAutoWssServerExtensionGenerator(
        Generator context)
    {
        Context = context;

        Name = "MapAutoWssServerExtension";
        Namespace = "gAPI.Generated";

        Directory = "";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }

    public WssHub_Generator WssHub => Context.WssHub;
    public ClientServiceContext_Generator[] ClientContexts => Context.ClientContexts;
    public IClientContext_Generator IClientContext => Context.IClientContext;
    public ClientContext_Generator ClientContext => Context.ClientContext;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SseHostCollection => Context.SharedReferences.SseHostCollection;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference WssServerConnectionCollection => Context.SharedReferences.WssServerConnectionCollection;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference WssSessionCache => Context.SharedReferences.WssSessionCache;
    public SharedReference ServerAuthenticationAccessor => Context.SharedReferences.ServerAuthenticationAccessor;
    public SharedReference SessionId => Context.SharedReferences.SessionId;

    public override void GenerateCode()
    {
        Reg(WssHub);
        Reg(IClientContext);
        Reg(ClientContext);
        Reg(FabricClient);
        Reg(ServerConfig);
        Reg(WssServerConnectionCollection);
        Reg(SseHostCollection);
        Reg(IServerAuthenticationService);
        Reg(WssSessionCache);
        Reg(ServerAuthenticationAccessor);
        Reg(SessionId);
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.Extensions.Primitives");
        Reg("System.Net");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.Logging");

        foreach (var mini in Context.MinimalApis)
        {
            Reg(mini);
        }

        foreach (var clientHandlerContext in ClientContexts)
        {
            Reg(clientHandlerContext);
            Reg(clientHandlerContext.IClientContext);
        }
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    RegRecursive(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.MinimalApiInterfaces.Where(a => a.FullName != "gAPI.Core.Interfaces.IAccountService"))
        {
            Reg(@interface);
            Reg(@interface.Service);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        foreach (var apiInterface in Context.ServiceContext.ApiInterfaces)
        {
            if (apiInterface.Service == null)
                throw new System.Exception($"Service of {Name} not implemented");
        }

        Reg("Microsoft.Extensions.DependencyInjection.Extensions");
        Reg("gAPI.Core.Server");
        Reg("gAPI.Core.Server.Authentication");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static WebApplication MapAutoWssServer(this WebApplication app)
    {{
        app.UseForwardedHeaders(new ForwardedHeadersOptions
        {{
            ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
        }});

        app.UseCors(""AllowSpecificOrigin"");
        app.UseRouting();

        app.UseWebSockets();
        app.MapWssEndpoint();
        app.MapStateEndpoint();

{(string.Join("", Context.MinimalApis.Select(Interface => $@"
        app.Map{Interface.Interface.CleanName}Endpoints();")))}

        return app;
    }}
}}";

    }
}