using gAPI.AutoSse.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoSse.Generators;

internal class AddAutoSseExtentionGenerator : BaseGenerator
{
    internal AddAutoSseExtentionGenerator(
        ServiceContext serviceContext,
        IEnumerable<SseServiceGenerator> sseServices,
        ISseContextGenerator iSseContext, 
        SseContextGenerator sseContext)
    {
        SseServices = sseServices;
        ISseContext = iSseContext;
        SseContext = sseContext;
        SseHostCollection = serviceContext.SseHostCollection;
        FabricClient = serviceContext.FabricClient;
        IServerAuthenticationService = serviceContext.IServerAuthenticationService;
        SseServiceId = serviceContext.SseServiceId;
        UserId = serviceContext.UserId;
        SessionId = serviceContext.SessionId;

        Directory = serviceContext.Config.AddAutoSseServices_Destination.Directory;
        Namespace = serviceContext.Config.AddAutoSseServices_Destination.Namespace;

        Name = "AddAutoSseExtention";
        FileName = $"{Name}.g.cs";
    }

    public IEnumerable<SseServiceGenerator> SseServices { get; }
    public ISseContextGenerator ISseContext { get; }
    public SseContextGenerator SseContext { get; }
    public SharedReference SseHostCollection { get; }
    public SharedReference FabricClient { get; }
    public SharedReference IServerAuthenticationService { get; }
    public SharedReference SseServiceId { get; }
    public SharedReference UserId { get;  }
    public SharedReference SessionId { get;  }

    public void GenerateCode()
    {
        Reg(ISseContext);
        Reg(SseContext);
        Reg(SseHostCollection);
        Reg(FabricClient);
        Reg(IServerAuthenticationService);
        Reg(SseServiceId);
        Reg(UserId);
        Reg(SessionId);
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.Extensions.DependencyInjection");

        //var services = string.Join(Environment.NewLine, SseServices.Select(s =>
        //{
        //    var i = s.Interface;
        //    Reg(i);
        //    Reg(s);
        //    return $@"
        //services.AddScoped<{i.Name}, {s.Name}>();";
        //}));

        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoSse(this IServiceCollection services, string? connectionString = null)
    {{
        {FabricClient} fabricClient;
        if (string.IsNullOrEmpty(connectionString))
        {{
            fabricClient = new {FabricClient}();
        }}
        else
        {{
            // Parse connection string
            var parts = connectionString!.Split(';')
                .Where(x => x.Contains('='))
                .Select(x => x.Split(['='], 2))
                .ToDictionary(x => x[0].Trim(), x => x[1].Trim(), StringComparer.OrdinalIgnoreCase);

            if (!parts.TryGetValue(""Server"", out var server))
                throw new Exception(""AutoSse ConnectionString must contain 'Server' parameter"");
            if (!parts.TryGetValue(""Port"", out var port))
                throw new Exception(""AutoSse ConnectionString must contain 'Port' parameter"");

            fabricClient = new {FabricClient}(server, Convert.ToInt32(port));
        }}

        _ = Task.Run(fabricClient.ConnectAsync);
        var sseHostCollection = new {SseHostCollection}();
        services.AddSingleton(fabricClient);
        services.AddSingleton(sseHostCollection);
        services.AddScoped<{ISseContext}, {SseContext}>();
        return services;
    }}
    public static WebApplication MapAutoSse(this WebApplication app)
    {{
        app.MapGet(""/ssehost/connect/{{serviceId}}"", async (
            string serviceId,
            [FromHeader(Name = ""X-SessionId"")] string sessionId,
            {IServerAuthenticationService} authenticationService,
            {SseHostCollection} sseHostCollection,
            {FabricClient} fabricClient,
            CancellationToken ct
        ) =>
        {{
            var sseHost = new SseHost(
                sseHostCollection,
                fabricClient,
                new {SseServiceId}(serviceId),
                new {UserId}(authenticationService.UserId),
                new {SessionId}(authenticationService.SessionId)
            );

            return Results.ServerSentEvents(
                sseHost.ReadAllAsync(ct)
            );
        }});
        return app;
    }}
}}
";

//        Code = $@"{GetNamespacesCode()}#nullable enable

        //namespace {Namespace};

        //public static class {Name}
        //{{
        //    public static void AddAutoSse(this IServiceCollection services, string? server, int? port = 9494)
        //    {{
        //        var fabricClient =
        //            server == null || port == null
        //            ? new {ServiceContext.FabricClient}()                     // Don't use a fabricNode
        //            : new {ServiceContext.FabricClient}(server, port.Value);  // Use the settings
        //        _ = Task.Run(fabricClient.ConnectAsync);
        //        var sseHostCollection = new {ServiceContext.SseHostCollection}();
        //        services.AddSingleton(fabricClient);
        //        services.AddSingleton(sseHostCollection);
        //        services.AddScoped<{ISseContext}, {SseContext}>();
        //    }}
        //}}
        //";

    }
}