using gAPI.AutoSse.Models;
using System.Linq;

namespace gAPI.AutoSse.Generators;

internal class SseContextGenerator : BaseGenerator
{
    internal SseContextGenerator(
        ServiceContext dataModel,
        SseServiceContextGenerator[] sseServiceContexts,
        ISseContextGenerator iSseContext)
    {
        DataModel = dataModel;
        SseServiceContexts = sseServiceContexts;
        ISseContext = iSseContext;

        Directory = dataModel.Config.SseContexts_Destination.Directory;
        Namespace = dataModel.Config.SseContexts_Destination.Namespace;

        Name = "SseContext";
        FileName = $"{Name}.g.cs";
    }

    public ServiceContext DataModel { get; }
    public SseServiceContextGenerator[] SseServiceContexts { get; }
    public ISseContextGenerator ISseContext { get; }

    public void GenerateCode()
    {
        Code = $@"using BSD.Core.SseServices;
using gAPI.Fabric;

// <auto-generated />
#nullable enable
namespace BSD.Core.SseContexts;

public class SseContext(
    FabricClient fabricClient)
    : ISseContext
{{
    public ITestClientServiceContext TestClientService {{ get; }} = new TestClientServiceContext(FabricClient);
}}
";
        //return;
        Reg(ISseContext);
        Reg(DataModel.FabricClient);
        var properties = string.Join(
            Environment.NewLine,
            SseServiceContexts
                .Select(a =>
                {
                    Reg(a);
                    Reg(a.ISseServiceContext);
                    return $"    public {a.ISseServiceContext.Name} {a.SseService.Interface.Title} {{ get; }} = new {a.Name}(fabricClient);";
                }));

        Code = @$"{GetNamespacesCode()}#nullable enable

namespace {Namespace};

public class {Name}(
    {DataModel.FabricClient} fabricClient)
    : {ISseContext}
{{
{properties}
}}
";
    }
}