using gAPI.AutoSerializer;
using gAPI.AutoWss.Server.Helpers;
using gAPI.AutoWss.Server.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Wss;

public class ServerConnection_Generator : _BaseGenerator
{
    public ServerConnection_Generator(Generator context)
    {
        Context = context;

        OwnServerConnection = context.SharedReferences.OwnServerConnection;
        if (OwnServerConnection != null)
        {
            Namespace = OwnServerConnection.Namespace;
            Name = OwnServerConnection.Name;
        }
        else
        {
            Namespace = "gAPI.Generated";
            Name = "ServerConnection";
        }

        Directory = "";
        FileName = $"Wss/{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }
    public SharedReference? OwnServerConnection { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;
    public SharedReference ServerConnectionCollection => Context.SharedReferences.ServerConnectionCollection;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SendRequestDto => Context.SharedReferences.SendRequestDto;
    public SharedReference InvokeRequestDto => Context.SharedReferences.InvokeRequestDto;
    public SharedReference StreamingResponseDto => Context.SharedReferences.StreamingResponseDto;
    public SharedReference InvokeRequestDoneDto => Context.SharedReferences.InvokeRequestDoneDto;
    public SharedReference StreamingCache => Context.SharedReferences.StreamingCache;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = [];
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        if (OwnServerConnection != null)
        {
            Code = "";
            return;
        }
        Reg("Microsoft.Extensions.Logging");
        Reg("System.Runtime.CompilerServices");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg("gAPI.Core.Server.Collections");
        Reg("gAPI.Core.Dtos");
        Reg("gAPI.Core.Server.Fabric");
        Reg("gAPI.Core.Server.Wss");
        Reg("gAPI.Core.Ids");
        Reg("gAPI.Core.Interfaces");
        Reg("Microsoft.CodeAnalysis");
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        var functions = string.Empty;
        var functionNames = new HashSet<string>();
        Code = @$"
// <auto-generated />
#nullable enable

namespace {Namespace};

public class {Name} : WssServerConnection
{{
    readonly ILogger ___logger;
    readonly {IServerAuthenticationService} ___authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
    readonly {@interface} {@interface.CleanName};")))}
    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];
    readonly {FabricClient} ___fabricClient;

    public {Name}(
        {IServerAuthenticationService} authenticationService,
        {ServiceSubscriptionCollection} serviceSubscriptions,
        {ServerConnectionCollection} connections,
        {StreamingCache} requestCache,
        {FabricClient} fabricClient,{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        {@interface} {@interface.CleanName.ToCamelCase()},")))}
        ILoggerFactory loggerFactory) 
        : base(authenticationService, serviceSubscriptions, connections, requestCache, fabricClient, loggerFactory)
    {{
        this.___fabricClient = fabricClient;
        this.___authenticationService = authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        this.{@interface.CleanName} = {@interface.CleanName.ToCamelCase()};")))}
        this.___logger = loggerFactory.CreateLogger<ServerConnection>();
    }}
    {GenerateSendRequest(ref functions, functionNames)}
    {GenerateInvokeRequest(ref functions, functionNames)}
    {string.Join(
        "",
        Context.ServiceContext.ApiInterfaces
            .SelectMany(@interface => @interface.Methods
                .Select(method => GenerateMethod(@interface, method, ref functions, functionNames))))}
    {functions}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }


    private string GenerateSendRequest(ref string functions2, HashSet<string> functionNames)
    {
        var functions = "";
        var code = $@"
    protected override Task Send_SendRequest_ToServiceAsync({SendRequestDto} ___sendRequest, CancellationToken ___ct)
    {{{(Context.ServiceContext.ApiInterfaces.Any(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask)) ? $@"
        var ___offset = 0;
        var ___span = new Span<byte>(___sendRequest.BinaryData);
        switch (___sendRequest.Routing.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___sendRequest.Routing.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask).Select(method =>
        {
            return $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___sendRequest,{string.Join("", method.Arguments
                                .Select((arg, index) => (arg, index))
                                .Where(a => a.arg.ParameterType.IsCancellationToken == false)
                                .Select(a => a.arg.ParameterType.IsIAsyncEnumerable
                                    ? $@"
                            RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___sendRequest.Routing, {a.index}, {method.Interface}_{method}_{a.index}_Deserializer),"
                                    : $@"
                            {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions, functionNames)},"))}
                            ___ct);";
        })))}
                }}
                break;")))}
        }}" : "")}
        throw new Exception($""Send {{___sendRequest.Routing.ServiceId.Value}}.{{___sendRequest.Routing.MethodId.Value}} not implemented"");
    }}";
        functions2 += functions;
        return code;
    }
    private string GenerateInvokeRequest(ref string functions2, HashSet<string> functionNames)
    {
        var functions = "";
        var code = $@"
    protected override IAsyncEnumerable<byte[]> Send_InvokeRequest_ToServiceAsync({InvokeRequestDto} ___invokeRequest, CancellationToken ___ct)
    {{{(Context.ServiceContext.ApiInterfaces.Any(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask == false)) ? $@"
        var ___offset = 0;
        var ___span = new Span<byte>(___invokeRequest.BinaryData);
        switch (___invokeRequest.Routing.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask == false)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___invokeRequest.Routing.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask == false).Select(method => $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___invokeRequest,{string.Join("", method.Arguments
                                .Select((arg, index) => (arg, index))
                                .Where(a => a.arg.ParameterType.IsCancellationToken == false)
                                .Select(a => a.arg.ParameterType.IsIAsyncEnumerable
                                    ? $@"
                            RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___invokeRequest.Routing, {a.index}, {method.Interface}_{method}_{a.index}_Deserializer),"
                                    : $@"
                            {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions, functionNames)},"))}
                            ___ct);")))}
                }}
                break;")))}
        }}" : "")}
        throw new Exception($""Invoke {{___invokeRequest.Routing.ServiceId.Value}}.{{___invokeRequest.Routing.MethodId.Value}} not implemented"");
    }}";
        functions2 += functions;
        return code;
    }


    private string GenerateMethod(Interface @interface, InterfaceMethod method, ref string functions2, HashSet<string> functionNames)
    {
        var code = "";
        var functions = "";
        if (method.ResponseType.IsTask)
        {
            code += GenerateTaskMethod(@interface, method);
        }
        else if (method.ResponseType.IsTaskT)
        {
            code += GenerateTaskTMethod(@interface, method);
            code += GenerateResponseSerializer(@interface, method);
        }
        else if (method.ResponseType.IsIAsyncEnumerable)
        {
            code += GenerateIAsyncEnumerableMethod(@interface, method);
            code += GenerateResponseSerializer(@interface, method);
        }
        else
        {
            throw new NotImplementedException($"{@interface}.{method} returns {method.ResponseType}, which is not supported. Please only use Task, Task<T> or IAsyncEnumerable<T>");
        }

        code += GenerateArgumentDeserializer(@interface, method, functionNames, ref functions);

        code += "\r\n";

        functions2 += functions;
        return code;
    }

    private string GenerateTaskMethod(Interface @interface, InterfaceMethod method)
    {
        return $@"
    public Task {@interface}_{method}({SendRequestDto} ___sendRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg.ParameterType} {arg}, "))}CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___sendRequest}})"", ___sendRequest);
       
        return {@interface.CleanName}.{method}({string.Join(", ", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"___ct" : $@"{arg}"))});
    }}";
    }
    private string GenerateTaskTMethod(Interface @interface, InterfaceMethod method)
    {
        return $@"
    public async IAsyncEnumerable<byte[]> {@interface}_{method}({InvokeRequestDto} ___invokeRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg.ParameterType} {arg}, "))}[EnumeratorCancellation] CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var ___responseTask = {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});

        var ___responseTaskResult = await ___responseTask;
        if (___responseTaskResult == null) yield break;

        yield return {@interface}_{method}_Serializer(___responseTaskResult);
    }}";
    }
    private string GenerateIAsyncEnumerableMethod(Interface @interface, InterfaceMethod method)
    {
        return $@"
    public async IAsyncEnumerable<byte[]> {@interface}_{method}({InvokeRequestDto} ___invokeRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg.ParameterType} {arg}, "))}[EnumeratorCancellation] CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var ___responseList = {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});
        await foreach (var response in ___responseList)
        {{
            yield return {@interface}_{method}_Serializer(response);
        }}
    }}";
    }

    private string GenerateResponseSerializer(Interface @interface, InterfaceMethod method)
    {
        var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
        return $@"
    public byte[] {@interface}_{method}_Serializer({returnTypeInner} value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___Buffer);{PropertyHelper.GenerateSpanWriteCode(returnTypeInner.Type, "value", "        ", false)}   
        return ___span.Slice(0, ___offset).ToArray();
    }}";
    }
    private string GenerateArgumentDeserializer(Interface @interface, InterfaceMethod method, HashSet<string> functionNames, ref string functions)
    {
        var code = "";
        foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
        {
            if (!arg.ParameterType.IsIAsyncEnumerable)
                continue;

            var innerType = arg.ParameterType.UnderlayingTypes.Single();
            code += $@"
    public {innerType} {@interface}_{method}_{index}_Deserializer(byte[] value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(value);
        return {PropertyHelper.GenerateSpanReadCode(innerType.Type, false, ref functions, functionNames)};
    }}";
        }
        return code;
    }
}