using gAPI.AutoSerializer;
using gAPI.AutoWss.Server.Helpers;
using gAPI.AutoWss.Server.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Wss;

public class ServerConnection_Generator : _BaseGenerator
{
    public ServerConnection_Generator(Generator context)
    {
        Context = context;

        Namespace = "gAPI.Generated";
        Name = "ServerConnection";

        Directory = "";
        FileName = $"Wss/{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;
    public SharedReference ServerConnectionCollection => Context.SharedReferences.ServerConnectionCollection;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SendRequestDto => Context.SharedReferences.SendRequestDto;
    public SharedReference InvokeRequestDto => Context.SharedReferences.InvokeRequestDto;
    public SharedReference StreamingResponseDto => Context.SharedReferences.StreamingResponseDto;
    public SharedReference InvokeRequestDoneDto => Context.SharedReferences.InvokeRequestDoneDto;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg("gAPI.Core.Server.Collections");
        Reg("gAPI.Core.Dtos");
        Reg("gAPI.Core.Server.Fabric");
        Reg("gAPI.Core.Server.Wss");
        Reg("gAPI.Core.Ids");
        Reg("gAPI.Core.Interfaces");
        Reg("Microsoft.CodeAnalysis");
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        var functions = string.Empty;
        var functionNames = new HashSet<string>();
        Code = @$"
// <auto-generated />
#nullable enable

namespace {Namespace};

public class {Name} : WssServerConnection
{{
    readonly ILogger ___logger;
    readonly {IServerAuthenticationService} ___authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
    readonly {@interface} {@interface.CleanName};")))}
    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];
    readonly {FabricClient} ___fabricClient;

    public {Name}(
        {IServerAuthenticationService} authenticationService,
        {ServiceSubscriptionCollection} ServiceSubscriptionCollection,
        {ServerConnectionCollection} connections,
        {FabricClient} fabricClient,{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        {@interface} {@interface.CleanName.ToCamelCase()},")))}
        ILoggerFactory loggerFactory) 
        : base(authenticationService, ServiceSubscriptionCollection, connections, fabricClient, loggerFactory)
    {{
        this.___fabricClient = fabricClient;
        this.___authenticationService = authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        this.{@interface.CleanName} = {@interface.CleanName.ToCamelCase()};")))}
        this.___logger = loggerFactory.CreateLogger<ServerConnection>();
    }}
    {GenerateSendRequest(ref functions, functionNames)}
    {GenerateInvokeRequest(ref functions, functionNames)}
    {GenerateTaskCalls()}
    {GenerateTaskTCalls()}
    {GenerateIAsyncEnumerableCalls()}
    {functions}
    {GenerateSerializers()}
    {GenerateArgumentDeserializers(ref functions, functionNames)}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }

    private string GenerateIAsyncEnumerableCalls()
    {
        return string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable).Select(method => $@"
    public async IAsyncEnumerable<byte[]> {@interface}_{method}({InvokeRequestDto} ___invokeRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg.ParameterType} {arg}, "))}CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var responses = {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});

        await foreach (var response in responses)
        {{
            yield return {@interface}_{method}_Serializer(response);
        }}
    }}"))));
    }
    private string GenerateTaskTCalls()
    {
        return string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTaskT).Select(method => $@"
    public async IAsyncEnumerable<byte[]> {@interface}_{method}({InvokeRequestDto} ___invokeRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg.ParameterType} {arg}, "))}CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var response = await {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});

        yield return {@interface}_{method}_Serializer(response);
    }}"))));
    }
    private string GenerateTaskCalls()
    {
        return string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask).Select(method => $@"
    public async Task {@interface}_{method}({SendRequestDto} ___sendRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg.ParameterType} {arg}, "))}CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___sendRequest}})"", ___sendRequest);

        await {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});
    }}"))));
    }

    private string GenerateSerializers()
    {
        return string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable || a.ResponseType.IsTaskT).Select(method =>
        {
            var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
            return $@"

    public byte[] {@interface}_{method}_Serializer({returnTypeInner} value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___Buffer);{PropertyHelper.GenerateSpanWriteCode(returnTypeInner.Type, "value", "        ", false)}   
        return ___span.Slice(0, ___offset).ToArray();
    }}";
        }))));
    }

    private string GenerateSendRequest(ref string functions2, HashSet<string> functionNames)
    {
        var functions = "";
        var code = $@"
    protected override Task Send_SendRequest_ToServiceAsync({SendRequestDto} ___sendRequest, CancellationToken ___ct)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___sendRequest.BinaryData);
        switch (___sendRequest.Routing.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___sendRequest.Routing.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask).Select(method =>
        {
            return $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___sendRequest,{GenerateArguments(method, "___sendRequest", ref functions, functionNames)}
                            ___ct);";
        })))}
                }}
                break;")))}
        }}
        throw new Exception($""Send {{___sendRequest.Routing.ServiceId.Value}}.{{___sendRequest.Routing.MethodId.Value}} not implemented"");
    }}";
        functions2 = functions;
        return code;
    }
    private string GenerateInvokeRequest(ref string functions2, HashSet<string> functionNames)
    {
        var functions = "";
        var code = $@"
    protected override IAsyncEnumerable<byte[]> Send_InvokeRequest_ToServiceAsync({InvokeRequestDto} ___invokeRequest, CancellationToken ___ct)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___invokeRequest.BinaryData);
        switch (___invokeRequest.Routing.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask == false)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___invokeRequest.Routing.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask == false).Select(method => $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___invokeRequest,{GenerateArguments(method, "___invokeRequest", ref functions, functionNames)}
                            ___ct);")))}
                }}
                break;")))}
        }}
        throw new Exception($""Invoke {{___invokeRequest.Routing.ServiceId.Value}}.{{___invokeRequest.Routing.MethodId.Value}} not implemented"");
    }}";
        functions2 = functions;
        return code;
    }

    private string GenerateArgumentDeserializers(ref string functions, HashSet<string> functionNames)
    {
        var argumentDeserializers = string.Empty;
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            foreach (var method in @interface.Methods)
            {
                foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
                {
                    if (!arg.ParameterType.IsIAsyncEnumerable)
                        continue;

                    var innerType = arg.ParameterType.UnderlayingTypes.Single();
                    argumentDeserializers += $@"

    public {innerType} {@interface}_{method}_{index}_Deserializer(byte[] value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(value);
        return {PropertyHelper.GenerateSpanReadCode(innerType.Type, false, ref functions, functionNames)};
    }}";
                }
            }
        }

        return argumentDeserializers;
    }
    private string GenerateArguments(InterfaceMethod method, string requestName, ref string functions, HashSet<string> functionNames)
    {
        var result = string.Empty;
        foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
        {
            if (arg.ParameterType.IsCancellationToken)
                continue;

            result += arg.ParameterType.IsIAsyncEnumerable
                ? $"\n                            RegisterRemoteAsyncEnumerableArgument<{arg.ParameterType.UnderlayingTypes.Single()}>({requestName}.Routing, {index}, {method.Interface}_{method}_{index}_Deserializer),"
                : $"\n                            {PropertyHelper.GenerateSpanReadCode(arg.ParameterType.Type, false, ref functions, functionNames)},";
        }

        return result;
    }
}