using gAPI.AutoSerializer;
using gAPI.AutoWss.Server.Helpers;
using gAPI.AutoWss.Server.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Wss;

public class ServerConnection_Generator : _BaseGenerator
{
    public ServerConnection_Generator(Generator context)
    {
        Context = context;

        Namespace = "gAPI.Generated";
        Name = "ServerConnection";

        Directory = "";
        FileName = $"Wss/{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference SseServiceSubscriptionCollection => Context.SharedReferences.SseServiceSubscriptionCollection;
    public SharedReference WssServerConnectionCollection => Context.SharedReferences.WssServerConnectionCollection;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SendRequestDto => Context.SharedReferences.SendRequestDto;
    public SharedReference InvokeRequestDto => Context.SharedReferences.InvokeRequestDto;
    public SharedReference InvokeResponseDto => Context.SharedReferences.InvokeResponseDto;
    public SharedReference InvokeResponseDoneDto => Context.SharedReferences.InvokeResponseDoneDto;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    private string GenerateArguments(InterfaceMethod method, string requestName, ref string functions, HashSet<string> functionNames)
    {
        var result = string.Empty;
        foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
        {
            if (arg.ParameterType.IsCancellationToken)
                continue;

            result += arg.ParameterType.IsIAsyncEnumerable
                ? $"\n                            RegisterRemoteAsyncEnumerableArgument<{arg.ParameterType.UnderlayingTypes.Single()}>({requestName}.RequestId, {index}, {InterfaceName(method)}_{index}_Deserializer),"
                : $"\n                            {PropertyHelper.GenerateSpanReadCode(arg.ParameterType.Type, false, ref functions, functionNames)},";
        }

        return result;
    }

    private string InterfaceName(InterfaceMethod method) => $"{method.Interface}_{method}";

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg("gAPI.Core.Server.Collections");
        Reg("gAPI.Core.Dtos");
        Reg("gAPI.Core.Server.Fabric");
        Reg("gAPI.Core.Server.Wss");
        Reg("gAPI.Core.Ids");
        Reg("gAPI.Core.Interfaces");
        Reg("Microsoft.CodeAnalysis");
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        var functions = string.Empty;
        var functionNames = new HashSet<string>();
        var argumentDeserializers = GenerateArgumentDeserializers(ref functions, functionNames);
        Code = @$"
// <auto-generated />
#nullable enable

namespace {Namespace};

public class {Name} : WssServerConnection
{{
    readonly ILogger ___logger;
    readonly {IServerAuthenticationService} ___authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
    readonly {@interface} {@interface.CleanName};")))}
    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];

    public {Name}(
        {IServerAuthenticationService} authenticationService,
        {SseServiceSubscriptionCollection} SseServiceSubscriptionCollection,
        {WssServerConnectionCollection} connections,
        {FabricClient} fabricClient,{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        {@interface} {@interface.CleanName.ToCamelCase()},")))}
        ILoggerFactory loggerFactory) 
        : base(authenticationService, SseServiceSubscriptionCollection, connections, fabricClient, loggerFactory)
    {{
        this.___authenticationService = authenticationService;{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => $@"
        this.{@interface.CleanName} = {@interface.CleanName.ToCamelCase()};")))}
        this.___logger = loggerFactory.CreateLogger<ServerConnection>();
    }}

    protected override Task Send_SendRequest_ToServiceAsync({SendRequestDto} ___sendRequest, CancellationToken ___ct)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___sendRequest.BinaryData);
        switch (___sendRequest.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___sendRequest.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask).Select(method =>
        {
            return $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___sendRequest,{GenerateArguments(method, "___sendRequest", ref functions, functionNames)}
                            ___ct);";
        })))}
                }}
                break;")))}
        }}
        throw new Exception($""Send {{___sendRequest.ServiceId.Value}}.{{___sendRequest.MethodId.Value}} not implemented"");
    }}
    protected override Task Send_InvokeRequest_ToServiceAsync({InvokeRequestDto} ___invokeRequest, CancellationToken ___ct)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___invokeRequest.BinaryData);
        switch (___invokeRequest.ServiceId.Value)
        {{{(string.Join("", Context.ServiceContext.ApiInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask == false)).Select(@interface => $@"
            case ""{@interface}"":
                switch (___invokeRequest.MethodId.Value)
                {{{(string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask == false).Select(method => $@"
                    case ""{method}"":
                        return {@interface}_{method}(
                            ___invokeRequest,{GenerateArguments(method, "___invokeRequest", ref functions, functionNames)}
                            ___ct);")))}
                }}
                break;")))}
        }}
        throw new Exception($""Invoke {{___invokeRequest.ServiceId.Value}}.{{___invokeRequest.MethodId.Value}} not implemented"");
    }}
{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTask).Select(method => $@"
    public async Task {@interface}_{method}(
        {SendRequestDto} ___sendRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg},"))}
        CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___sendRequest}})"", ___sendRequest);

        await {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});
    }}")))))}
{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsTaskT).Select(method => $@"
    public async Task {@interface}_{method}(
        {InvokeRequestDto} ___invokeRequest, {string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg},"))}
        CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var response = await {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});

        await Send_InvokeResponse_ToClientAsync(new {InvokeResponseDto}()
            {{
                RequestId = ___invokeRequest.RequestId,
                ServiceId = ___invokeRequest.ServiceId,
                MethodId = ___invokeRequest.MethodId,
                SessionId = ___authenticationService.SessionId,
                StateData = ___authenticationService.IsStateDataChanged() ? ___authenticationService.GetStateData() : null,
                BinaryData = {@interface}_{method}_Serializer(response)
            }}, ___ct);
    }}")))))}
{(string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable).Select(method => $@"
    public async Task {@interface}_{method}(
        {InvokeRequestDto} ___invokeRequest,{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg},"))}
        CancellationToken ___ct)
    {{
        if (___logger.IsEnabled(LogLevel.Trace))
            ___logger.LogTrace(""{@interface}_{method}({{___invokeRequest}})"", ___invokeRequest);

        var responses = {@interface.CleanName}.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken ? $@"
            ___ct" : $@"
            {arg}"))});

        await foreach (var response in responses)
        {{
            await Send_InvokeResponse_ToClientAsync(new {InvokeResponseDto}()
                {{
                    RequestId = ___invokeRequest.RequestId,
                    ServiceId = ___invokeRequest.ServiceId,
                    MethodId = ___invokeRequest.MethodId,
                    SessionId = ___authenticationService.SessionId,
                    StateData = ___authenticationService.IsStateDataChanged() ? ___authenticationService.GetStateData() : null,
                    BinaryData = {@interface}_{method}_Serializer(response)
                }}, ___ct);
        }}
    }}")))))}{functions}

{string.Join("", Context.ServiceContext.ApiInterfaces.Select(@interface => string.Join("", @interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable || a.ResponseType.IsTaskT).Select(method =>
        {
            var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
            return $@"

    public byte[] {@interface}_{method}_Serializer({returnTypeInner} value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___Buffer);{PropertyHelper.GenerateSpanWriteCode(returnTypeInner.Type, "value", "        ", false)}   
        return ___span.Slice(0, ___offset).ToArray();
    }}";
        }))))}{argumentDeserializers}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }

    private string GenerateArgumentDeserializers(ref string functions, HashSet<string> functionNames)
    {
        var argumentDeserializers = string.Empty;
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            foreach (var method in @interface.Methods)
            {
                foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
                {
                    if (!arg.ParameterType.IsIAsyncEnumerable)
                        continue;

                    var innerType = arg.ParameterType.UnderlayingTypes.Single();
                    argumentDeserializers += $@"

    public {innerType} {@interface}_{method}_{index}_Deserializer(byte[] value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(value);
        return {PropertyHelper.GenerateSpanReadCode(innerType.Type, false, ref functions, functionNames)};
    }}";
                }
            }
        }

        return argumentDeserializers;
    }
}