
using gAPI.AutoApi.Server.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApi.Server.Generators;

public class AddAutoApiSseServerExtension_Generator : BaseGenerator
{
    public AddAutoApiSseServerExtension_Generator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoApiSseServerExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference? Middleware => Context.SharedReferences.AuthServer_Middleware;


    public IEnumerable<ClientService_Generator> SseServices => Context.SseServices;
    public IClientContext_Generator IClientContext => Context.IClientContext;
    public ClientContext_Generator ClientContext => Context.ClientContext;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference SseServiceSubscription => Context.SharedReferences.SseServiceSubscription;
    public SharedReference SessionCache => Context.SharedReferences.SessionCache;
    public SharedReference AuthenticationOptions => Context.SharedReferences.AuthenticationOptions;

    public override void GenerateCode()
    {

        Reg(IClientContext);
        Reg(ClientContext);
        Reg(ServiceId);
        Reg(UserId);
        Reg(SessionId);
        Reg(SseServiceSubscription);
        Reg(SessionCache);
        Reg(AuthenticationOptions);
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("Microsoft.Extensions.Logging");
        Reg("Microsoft.Extensions.DependencyInjection");

        foreach (var item in Context.ClientContexts)
        {
            Reg(item);
            Reg(item.IClientContext);
        }

        Reg("Microsoft.AspNetCore.Authentication");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("System.Reflection");
        Reg("System.Globalization");
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.Logging");
        Reg(ServerConfig);
        Reg(FabricClient);
        Reg(ServiceSubscriptionCollection);
        Reg("Microsoft.Extensions.DependencyInjection");
        var propertiesCode = "";
        foreach (var controller in Context.Apis.Where(a => a.Interface.FullName != "gAPI.Core.Interfaces.IAccountService"))
        {
            var service = controller.Service;
            var @interface = controller.Interface;
            Reg(service);
            Reg(@interface);
            propertiesCode += $"        services.AddScoped<{@interface.Name}, {service.Name}>();\r\n";
        }
        foreach (var api in Context.MinimalApis)
        {
            Reg(api);
            Reg(api.Interface);
            Reg(api.Interface.Service);
            foreach (var method in api.Interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoApiSseServer(this IServiceCollection services, {ServerConfig} serverConfig)
    {{
        return AddAutoApiSseServer(services, serverConfig.FrontendUrl, serverConfig.FabricConnectionString);
    }}
    public static IServiceCollection AddAutoApiSseServer(this IServiceCollection services, string frontendUrl, string? fabricConnectionString)
    {{
        services.AddSingleton(new {AuthenticationOptions}(false));
        CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;

        services.AddHttpContextAccessor();
        services.AddCors(options =>
        {{
            options.AddPolicy(""AllowSpecificOrigin"", policy =>
            {{
                policy
                    .WithOrigins(frontendUrl)
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()
                    .WithExposedHeaders(""X-SessionId"", ""X-StateData"");
            }});
        }});

        services.AddSingleton(sp => new {FabricClient}(sp.GetRequiredService<ILoggerFactory>(), fabricConnectionString));

        var ServiceSubscriptionCollection = new {ServiceSubscriptionCollection}();
        services.AddSingleton(ServiceSubscriptionCollection);

        {propertiesCode}
        services.AddAuthorization();
        services.AddControllers();


        services.AddHttpContextAccessor();
        services.AddCors(options =>
        {{
            options.AddPolicy(""AllowSpecificOrigin"", policy =>
            {{
                policy
                    .WithOrigins(frontendUrl)
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()
                    .WithExposedHeaders(""X-SessionId"", ""X-StateData"");
            }});
        }});

        services.AddSingleton(sp => new {FabricClient}(sp.GetRequiredService<ILoggerFactory>(), fabricConnectionString));

        var sessionCache = new {SessionCache}();
        services.AddSingleton(sessionCache);

        services.AddScoped<{IClientContext}, {ClientContext}>();

{string.Join("", Context.ClientContexts.Select(a => $@"
        services.AddScoped<{a.IClientContext}, {a}>();"))}

        return services;
    }}

    public static WebApplication MapAutoApiSseServer<TMiddleware>(this WebApplication app)
    {{
        app.UseForwardedHeaders(new ForwardedHeadersOptions
        {{
            ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
        }});

        app.UseCors(""AllowSpecificOrigin"");

        app.UseMiddleware<TMiddleware>();
        app.UseAuthentication();
        app.UseAuthorization();

        // 🔥 State handshake endpoint
        app.MapGet(""/__state"", ([FromHeader(Name = ""X-SessionId"")] string sessionId) => {{ }}).AllowAnonymous();

        // 🔥 Sse endpoint
        app.MapSseEndpoint();

        // 🔥 Minimal api endpoints
{(string.Join("", Context.MinimalApis.Select(Interface => $@"
        app.Map{Interface.Interface.CleanName}Endpoints();")))}

        // 🔥 Controllers
        app.MapControllers();

        return app;
    }}
}}

";

    }
}