//using gAPI.AutoApiSse.Server.Models;
//using System.Collections.Generic;
//using System.Linq;

//namespace gAPI.AutoApiSse.Server.Generators;

//public class AddAutoSseExtention_Generator : BaseGenerator
//{
//    public AddAutoSseExtention_Generator(
//        Generator context)
//    {
//        Context = context;

//        Directory = "";
//        Namespace = "gAPI.Generated";

//        Name = "AddAutoSseExtension";
//        FileName = $"{Name}.g.cs";
//    }

//    public Generator Context { get; }

//    public IEnumerable<ClientService_Generator> SseServices => Context.SseServices;
//    public IClientContext_Generator IClientContext => Context.IClientContext;
//    public ClientContext_Generator ClientContext => Context.ClientContext;
//    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;
//    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
//    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
//    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
//    public SharedReference UserId => Context.SharedReferences.UserId;
//    public SharedReference SessionId => Context.SharedReferences.SessionId;
//    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
//    public SharedReference SseServiceSubscription => Context.SharedReferences.SseServiceSubscription;
//    public SharedReference SessionCache => Context.SharedReferences.SessionCache;

//    public override void GenerateCode()
//    {
//        Reg(IClientContext);
//        Reg(ClientContext);
//        Reg(ServiceSubscriptionCollection);
//        Reg(FabricClient);
//        Reg(IServerAuthenticationService);
//        Reg(ServiceId);
//        Reg(UserId);
//        Reg(SessionId);
//        Reg(ServerConfig);
//        Reg(SseServiceSubscription);
//        Reg(SessionCache);
//        Reg("Microsoft.AspNetCore.Mvc");
//        Reg("Microsoft.AspNetCore.HttpOverrides");
//        Reg("Microsoft.AspNetCore.Builder");
//        Reg("Microsoft.AspNetCore.Http");
//        Reg("Microsoft.Extensions.Logging");
//        Reg("Microsoft.Extensions.DependencyInjection");

//        foreach (var item in Context.ClientContexts)
//        {
//            Reg(item);
//            Reg(item.IClientContext);
//        }

//        Code = @$"{GetNamespacesCode()}
//// <auto-generated />
//#nullable enable
//namespace {Namespace};

//public static class {Name}
//{{
//    public static IServiceCollection AddAutoSse(this IServiceCollection services, {ServerConfig} serverConfig)
//    {{
//        return AddAutoSse(services, serverConfig.FrontendUrl, serverConfig.FabricConnectionString);
//    }}
//    public static IServiceCollection AddAutoSse(this IServiceCollection services, string? frontendUrl, string? fabricConnectionString = null)
//    {{
//        services.AddHttpContextAccessor();
//        services.AddCors(options =>
//        {{
//            options.AddPolicy(""AllowSpecificOrigin"", policy =>
//            {{
//                policy
//                    .WithOrigins(frontendUrl)
//                    .AllowAnyMethod()
//                    .AllowAnyHeader()
//                    .AllowCredentials()
//                    .WithExposedHeaders(""X-SessionId"", ""X-StateData"");
//            }});
//        }});

//        services.AddSingleton(sp => new {FabricClient}(sp.GetRequiredService<ILoggerFactory>(), fabricConnectionString));

//        var ServiceSubscriptionCollection = new {ServiceSubscriptionCollection}();
//        services.AddSingleton(ServiceSubscriptionCollection);

//        var sessionCache = new {SessionCache}();
//        services.AddSingleton(sessionCache);

//        services.AddScoped<{IClientContext}, {ClientContext}>();

//{string.Join("", Context.ClientContexts.Select(a => $@"
//        services.AddScoped<{a.IClientContext}, {a}>();"))}

//        return services;
//    }}
//    public static WebApplication MapAutoSse(this WebApplication app)
//    {{
//        app.MapGet(""/SseServiceSubscription/connect/{{serviceId}}"", async (
//            string serviceId,
//            [FromHeader(Name = ""X-SessionId"")] string sessionId,
//            {IServerAuthenticationService} authenticationService,
//            {ServiceSubscriptionCollection} ServiceSubscriptionCollection,
//            {FabricClient} fabricClient,
//            CancellationToken ct
//        ) =>
//        {{
//            var SseServiceSubscription = new {SseServiceSubscription}(
//                ServiceSubscriptionCollection,
//                fabricClient,
//                new {ServiceId}(serviceId),
//                authenticationService.UserId,
//                authenticationService.SessionId
//            );

//            return Results.ServerSentEvents(
//                SseServiceSubscription.ReadAllAsync(ct)
//            );
//        }});
//        return app;
//    }}
//}}
//";

//    }
//}