
using gAPI.AutoApi.Server.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApi.Server.Generators;

public class SseEndpointExtension_Generator : BaseGenerator
{
    public SseEndpointExtension_Generator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "SseEndpointExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;

    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference SseServiceSubscription => Context.SharedReferences.SseServiceSubscription;

    public override void GenerateCode()
    {
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg(IServerAuthenticationService);
        Reg(FabricClient);
        Reg(ServiceSubscriptionCollection);
        Reg(ServiceId);
        Reg(SseServiceSubscription);
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static WebApplication MapSseEndpoint(this WebApplication app)
    {{
        // 🔥 Sse endpoint
        app.MapGet(""/SseServiceSubscription/connect/{{serviceId}}"", async (
            string serviceId,
            [FromHeader(Name = ""X-SessionId"")] string sessionId,
            {IServerAuthenticationService} authenticationService,
            {ServiceSubscriptionCollection} ServiceSubscriptionCollection,
            {FabricClient} fabricClient,
            CancellationToken ct
        ) =>
        {{
            var SseServiceSubscription = new {SseServiceSubscription}(
                ServiceSubscriptionCollection,
                fabricClient,
                new {ServiceId}(serviceId),
                authenticationService.UserId,
                authenticationService.SessionId
            );

            return Results.ServerSentEvents(
                SseServiceSubscription.ReadAllAsync(ct)
            );
        }});

        return app;
    }}
}}

";



    }
}