
using gAPI.AutoApi.Server.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApi.Server.Generators;

public class SseEndpointExtension_Generator : BaseGenerator
{
    public SseEndpointExtension_Generator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "SseEndpointExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SseServiceSubscriptionCollection => Context.SharedReferences.SseServiceSubscriptionCollection;

    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference SseServiceSubscription => Context.SharedReferences.SseServiceSubscription;

    public override void GenerateCode()
    {
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg(IServerAuthenticationService);
        Reg(FabricClient);
        Reg(SseServiceSubscriptionCollection);
        Reg(ServiceId);
        Reg(SseServiceSubscription);
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static WebApplication MapSseEndpoint(this WebApplication app)
    {{
        // 🔥 Sse endpoint
        app.MapGet(""/SseServiceSubscription/connect/{{serviceId}}"", async (
            string serviceId,
            [FromHeader(Name = ""X-SessionId"")] string sessionId,
            {IServerAuthenticationService} authenticationService,
            {SseServiceSubscriptionCollection} SseServiceSubscriptionCollection,
            {FabricClient} fabricClient,
            CancellationToken ct
        ) =>
        {{
            var SseServiceSubscription = new {SseServiceSubscription}(
                SseServiceSubscriptionCollection,
                fabricClient,
                new {ServiceId}(serviceId),
                authenticationService.UserId,
                authenticationService.SessionId
            );

            return Results.ServerSentEvents(
                SseServiceSubscription.ReadAllAsync(ct)
            );
        }});

        return app;
    }}
}}

";

































        //        Code = $@"{GetNamespacesCode()}
        //namespace {Namespace};

        //public static class {Name}
        //{{
        //    public static void AddAutoApi<TInterface, TImplementation>(this IServiceCollection services, string frontendUrl, params Assembly[] assembliesToScan)
        //        where TInterface : class, gAPI.Core.Interfaces.IServerAuthenticationService
        //        where TImplementation : class, gAPI.Core.Interfaces.IServerAuthenticationService, TInterface
        //    {{
        //        // JSON standaard op invariant zetten
        //        services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options =>
        //        {{
        //            options.SerializerOptions.Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping;
        //            options.SerializerOptions.PropertyNamingPolicy = null;
        //            options.SerializerOptions.WriteIndented = false;
        //        }});

        //        // Add normal asp.net core controllers
        //        services.AddControllers();

        //        // Http context accessor for gAPI
        //        services.AddHttpContextAccessor();

        //        // Remaining services
        //        services.AddAutoApiServices();

        //        // Add Cors
        //        services.AddCors(options =>
        //        {{
        //            options.AddPolicy(""AllowSpecificOrigin"", policy =>
        //            {{
        //                policy.WithOrigins(frontendUrl)
        //                      .AllowAnyMethod()
        //                      .AllowAnyHeader()
        //                      .AllowCredentials();
        //            }});
        //        }});

        //        // Add gAPI server authentication 
        //        services.AddScoped<TImplementation>() ;
        //        services.AddScoped<TInterface>(sp => sp.GetRequiredService<TImplementation>())   ;
        //        services.AddScoped<gAPI.Core.Interfaces.IServerAuthenticationService>(sp => sp.GetRequiredService<TImplementation>());
        //        services.AddAuthentication(""gAPI"")
        //                        .AddScheme<AuthenticationSchemeOptions, BSD.Core.Authentication.ServerAuthenticationHandler>(""gAPI"", _ => {{ }});
        //        services.AddAuthorization();

        //    }}

        //    public static void MapAutoApi(this WebApplication app)
        //    {{
        //        app.UseForwardedHeaders(new ForwardedHeadersOptions
        //        {{
        //            ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
        //        }});

        //        app.UseCors(""AllowSpecificOrigin"");

        //        app.MapControllers();

        //        app.UseMiddleware<BSD.Core.Authentication.ServerAuthenticationMiddleware>();
        //        app.UseAuthentication();
        //        app.UseAuthorization();
        //    }}
        //}}
        //";

    }
}