//using Bsd.Public.Shared.Interfaces;
//using gAPI.Core.Ids;
//using gAPI.Core.Interfaces;
//using gAPI.Core.Server.Fabric;

//// <auto-generated />
//#nullable enable

//namespace gAPI.Generated;

//public class CameraApiContext(
//    FabricClient fabricClient,
//    IServerAuthenticationService authenticationService,
//    ILoggerFactory loggerFactory) : ICameraApiContext

//{
//    public ICameraApi ToFabricConnection(FabricConnectionId fabricConnectionId, ClientConnectionId clientConnectionId)
//        => new CameraApiProxy(fabricClient, authenticationService, loggerFactory, fabricConnectionId, clientConnectionId);
//}
