//using Bsd.Public.Shared.Dtos;
//using Bsd.Public.Shared.Interfaces;
//using gAPI.Core.Dtos;
//using gAPI.Core.Ids;
//using gAPI.Core.Interfaces;
//using gAPI.Core.Serializers;
//using gAPI.Core.Server.Fabric;
//using gAPI.Core.Server.Interfaces;
//using System.Collections.Concurrent;
//using System.Runtime.CompilerServices;

//// <auto-generated />
//#nullable enable
//namespace gAPI.Generated;

//public class ServiceRouter(
//    IServiceProvider serviceProvider)
//    : IServiceRouter
//{
//    ConcurrentDictionary<RequestId, ApiScope> Scopes = [];
//    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];

//    public async Task SendRequestAsync(FabricClient fabricClient, ServerSendRequestDto ___message, CancellationToken ___ct)
//    {
//        var apiScope = await CreateScope(
//            ___message.Routing,
//            ___message.Path,
//            ___message.QueryString,
//            ___message.IpAddress,
//            ___message.CookieData,
//            ___message.SessionData,
//            ___message.StateData,
//            ___ct);
//        if (apiScope == null)
//            return;


//        var ___offset = 0;
//        var ___span = new Span<byte>(___message.BinaryData);
//        switch (___message.Routing.ServiceId.Value)
//        {
//            case "ICameraApi":
//                switch (___message.Routing.MethodId.Value)
//                {
//                    case "SendVideoChunkAsync":
//                        await apiScope.CameraApi.SendVideoChunkAsync(
//                            PrimitivesSpanSerializer.ReadString(___span, ref ___offset),
//                            PrimitivesSpanSerializer.ReadString(___span, ref ___offset),
//                            GuidSerializer.ReadGuid(___span, ref ___offset),
//                            CameraInfoSpanSerializer.ReadCameraInfo(___span, ref ___offset),
//                            PrimitivesSpanSerializer.ReadByteReadOnlyMemory(___span, ref ___offset),
//                            ___ct);
//                        return;
//                    case "UnsubscribeFromListener":
//                        await apiScope.CameraApi.UnsubscribeFromListener(
//                            CameraRecordingListenerSpanSerializer.ReadCameraRecordingListener(___span, ref ___offset),
//                            ___ct);
//                        return;
//                    case "Pong":
//                        await apiScope.CameraApi.Pong(
//                            CameraRecordingListenerSpanSerializer.ReadCameraRecordingListener(___span, ref ___offset),
//                            PrimitivesSpanSerializer.ReadString(___span, ref ___offset),
//                            ___ct);
//                        return;
//                }
//                break;
//        }
//        throw new Exception($"Send {___message.Routing.ServiceId.Value}.{___message.Routing.MethodId.Value} not implemented");
//    }
//    public async Task SendRequestCancelled(FabricClient fabricClient, ServerSendRequestCancelledDto message, CancellationToken ct)
//    {
//    }

//    public async IAsyncEnumerable<byte[]> InvokeRequestAsync(FabricClient fabricClient, ServerInvokeRequestDto ___message, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        var apiScope = await CreateScope(
//            ___message.Routing,
//            ___message.Path,
//            ___message.QueryString,
//            ___message.IpAddress,
//            ___message.CookieData,
//            ___message.SessionData,
//            ___message.StateData,
//            ___ct);
//        if (apiScope == null)
//            yield break;

//        var ___offset = 0;
//        var ___span = new Span<byte>(___message.BinaryData);
//        switch (___message.Routing.ServiceId.Value)
//        {
//            case "ICameraApi":
//                switch (___message.Routing.MethodId.Value)
//                {
//                    case "ListActiveRecordings":
//                        var item1 = await apiScope.CameraApi.ListActiveRecordings(
//                            ___ct);
//                        yield return ICameraApi_ListActiveRecordings_Serializer(item1);
//                        yield break;
//                    case "SubscribeToRecording":
//                        var item = await apiScope.CameraApi.SubscribeToRecording(
//                            CameraRecordingSpanSerializer.ReadCameraRecording(___span, ref ___offset),
//                            ___ct);
//                        yield return ICameraApi_SubscribeToRecording_Serializer(item);
//                        yield break;
//                }
//                break;
//        }
//        throw new Exception($"Invoke {___message.Routing.ServiceId.Value}.{___message.Routing.MethodId.Value} not implemented");

//    }
//    public async Task InvokeRequestCancelled(FabricClient fabricClient, ServerInvokeRequestCancelledDto message, CancellationToken ct)
//    {
//    }

//    public byte[] ICameraApi_ListActiveRecordings_Serializer(CameraRecording[] value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___Buffer);
//        PrimitivesSpanSerializer.WriteInt32(ref ___span, ref ___offset, value.Length);
//        foreach (var item1 in value)
//        {
//            CameraRecordingSpanSerializer.Write(ref ___span, ref ___offset, item1);
//        }
//        return ___span.Slice(0, ___offset).ToArray();
//    }
//    public byte[] ICameraApi_SubscribeToRecording_Serializer(CameraRecordingListener value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___Buffer);
//        CameraRecordingListenerSpanSerializer.Write(ref ___span, ref ___offset, value);
//        return ___span.Slice(0, ___offset).ToArray();
//    }

//    private async Task<ApiScope?> CreateScope(
//        ServerRoutingDto routing,
//        string path,
//        string? queryString,
//        byte[] ipAddress,
//        string? cookieData,
//        string? sessionData,
//        string? stateData,
//        CancellationToken ___ct)
//    {
//        var scope = serviceProvider.CreateAsyncScope();
//        var apiScope = new ApiScope(scope);
//        var result = await apiScope.AuthenticationService.InitializeAsync(
//            new PathString(path),
//            new QueryString(queryString),
//            new System.Net.IPAddress(ipAddress),
//            cookieData,
//            sessionData,
//            stateData,
//            ___ct);

//        if (result.Forbidden || Scopes.TryAdd(routing.RequestId, apiScope) == false)
//        {
//            await apiScope.DisposeAsync();
//            return null;
//        }

//        return apiScope;
//    }

//}
//public class ApiScope : IAsyncDisposable
//{
//    private readonly AsyncServiceScope Scope;
//    public CancellationTokenSource? Cts;

//    public ApiScope(AsyncServiceScope scope)
//    {
//        Scope = scope;
//        AuthenticationService = scope.ServiceProvider.GetRequiredService<IServerAuthenticationService>();
//        CameraApi = scope.ServiceProvider.GetRequiredService<ICameraApi>();

//        Cts = new(TimeSpan.FromSeconds(100));
//        Cts.Token.Register(async () =>
//        {
//            Cts = null;
//            await DisposeAsync();
//        });
//    }

//    public IServerAuthenticationService AuthenticationService { get; }
//    public ICameraApi CameraApi { get; }

//    public ValueTask DisposeAsync()
//    {
//        Cts?.Dispose();
//        return Scope.DisposeAsync();
//    }
//}