namespace gAPI.AutoApiClient.Generators;

public class AutoApiClientExtensionGenerator : BaseGenerator
{
    public AutoApiClientExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AutoApiClientExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public ApiClientGenerator[] Clients => Context.Clients;

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");

        var propertiesCode = "";
        foreach (var client in Clients)
        {
            var @interface = client.Interface;
            Reg(@interface);
            Reg(client);
            propertiesCode += $"\r\n        services.AddScoped<{@interface.Name}, {client.Name}>();";
        }

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
namespace {Namespace};

public static class {Name}
{{
    public static void AddAutoApiClient(this IServiceCollection services)
    {{{propertiesCode}
    }}
}}";
    }
}