using gAPI.AutoApi.Client.Models;
using System.Linq;

namespace gAPI.AutoApi.Client.Generators.Sse;

public class ClientConnectionGenerator : _BaseGenerator
{
    public ClientConnectionGenerator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "ClientConnection";
        FileName = $"Sse/{Name}.g.cs";
    }

    public Generator Context { get; }
    public ServiceContext DataModel => Context.ServiceContext;
    public SharedReference SseClient => Context.SharedReferences.SseClient;

    public Interface[] Interfaces => Context.ServiceContext.HubInterfaces;

    public SharedReference IClientAuthenticatedHttpClient => Context.SharedReferences.IClientAuthenticatedHttpClient;
    public SharedReference SseManagerCollection => Context.SharedReferences.SseManagerCollection;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference ServiceMethodId => Context.SharedReferences.ServiceMethodId;
    public SharedReference IClientConnection => Context.IClientConnection;
    public SharedReference SseClientConnection => Context.SharedReferences.SseClientConnection;

    public override void GenerateCode()
    {
        Reg("System.Text.Json");
        Reg("System.Collections.Concurrent");
        Reg("System.Collections.Immutable");
        Reg("System.Text");
        Reg("System.Runtime.CompilerServices");
        Reg(IClientConnection);
        Reg(SseClient);
        Reg(IClientAuthenticatedHttpClient);
        Reg(SseManagerCollection);
        Reg(ServiceId);
        Reg(SseClientConnection);


        Code = @$"
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name} : {SseClientConnection}, {IClientConnection.Name}
{{{string.Join("", Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"
    private ImmutableArray<{i.Name}> {i.Title}s = [];";
        }))}

    public {Name}(
        {IClientAuthenticatedHttpClient.Name} clientAuthenticatedHttpClient,
        {SseManagerCollection.Name} sseManagerCollection)
        : base(clientAuthenticatedHttpClient, sseManagerCollection)
    {{
    }}

    public async Task SubscribeAsync(object implementation, CancellationToken ct)
    {{
        {string.Join("", Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"
        if (implementation is {i.Name} _{i.Name})
        {{
            var serviceId = new {ServiceId}(nameof({i.Name}));
            var client = ServiceClients.AddOrUpdate(
                serviceId,
                serviceId =>
                {{
                    var client = new SseClient(ClientAuthenticatedHttpClient, this, serviceId);
                    ImmutableInterlocked.Update(ref {i.Title}s, list => list.Add(_{i.Name}));
                    _ = Task.Run(client.ConnectAsync);
                    return client;
                }},
                (service, client) =>
                {{
                    ImmutableInterlocked.Update(ref {i.Title}s, list => list.Add(_{i.Name}));
                    return client;
                }});
        }}";
        }))}
    }}
    public async Task UnsubscribeAsync(object implementation, CancellationToken ct)
    {{
        {string.Join("", Interfaces
        .Select(i =>
        {
            Reg(i);
            return @$"
        if (implementation is {i.Name} _{i.Name})
        {{
            var serviceId = new {ServiceId}(nameof({i.Name}));
            ImmutableInterlocked.Update(ref {i.Title}s, list => list.Remove(_{i.Name}));
            if ({i.Title}s.Length == 0 &&
                ServiceClients.TryRemove(serviceId, out var client))
            {{
                client.Dispose();
            }}
        }}";
        }))}
    }}

    public async Task SendRequest_ReceivedAsync(
        {ServiceId} serviceId,
        {ServiceMethodId} methodId,
        byte[] data,
        CancellationToken ct)
    {{{(Interfaces.Length > 0 ? $@"
        switch (serviceId.Value)
        {{{string.Join("\r\n", Interfaces
        .Select(i =>
        {
            Reg(i);
            return $@"
            case ""{i.Name}"":
                switch(methodId.Value)
                {{{string.Join("\r\n", i.Methods.Where(a => a.ResponseType.IsTask || a.ResponseType.IsVoid).Select(m =>
            {
                var hasCancellationToken = m.Arguments.Any(a => a.ParameterType.Name == "CancellationToken");
                return $@"
                    case ""{m.Name}"":
                        var {m.Name.ToLower()} = 
                            JsonSerializer.Deserialize<{i.Title}_{m.Name}>(
                                Encoding.UTF8.GetString(data));
                        if ({m.Name.ToLower()} == null) return;
                        foreach (var hub in {i.Title}s)
                        {{
                            {(m.ResponseType.IsVoid ? "" : "await ")}hub.{m.Name}({string.Join(", ", m.Arguments
    .Where(a => a.ParameterType.Name != "CancellationToken")
    .Select(a => $"{m.Name.ToLower()}.{a.Name}")
    .Concat(hasCancellationToken ? new[] { "ct" } : Enumerable.Empty<string>()))});
                        }}
                        break;";
            }))}
                }}
                break;";
        }))}
        }}" : "")}
    }}

    public async IAsyncEnumerable<byte[]> InvokeRequest_ReceivedAsync(
        {ServiceId} serviceId,
        {ServiceMethodId} methodId,
        byte[] data,
        CancellationToken ct)
    {{{(Interfaces.Length > 0 ? $@"
        switch (serviceId.Value)
        {{{string.Join("\r\n", Interfaces
        .Select(i =>
        {
            Reg(i);
            return $@"
            case ""{i.Name}"":
                switch(methodId.Value)
                {{{string.Join("\r\n", i.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable).Select(m =>
            {
                var hasCancellationToken = m.Arguments.Any(a => a.ParameterType.Name == "CancellationToken");
                return $@"
                    case ""{m.Name}"":
                        {{
                            var {m.Name.ToLower()} = 
                                JsonSerializer.Deserialize<{i.Title}_{m.Name}>(
                                    Encoding.UTF8.GetString(data));
                            if ({m.Name.ToLower()} == null) yield break;
                            foreach (var hub in {i.Title}s)
                            {{
                                var list = hub.{m.Name}({string.Join(", ", m.Arguments
                                    .Where(a => a.ParameterType.Name != "CancellationToken")
                                    .Select(a => $"{m.Name.ToLower()}.{a.Name}")
                                    .Concat(hasCancellationToken ? new[] { "ct" } : Enumerable.Empty<string>()))});

                                await foreach (var item in list)
                                {{
                                    yield return Encoding.UTF8.GetBytes(
                                        JsonSerializer.Serialize(item));
                                }}
                            }}
                        }}
                        break;";
            }))}
                }}
                break;";
        }))}
        }}" : "")}
        yield break;
    }}{string.Join("", Interfaces
        .Select(i =>
        {
            Reg(i);
            return string.Join("", i.Methods
                .Select(m =>
                {
                    return @$"

    public class {i.Title}_{m.Name}
    {{{string.Join("", m.Arguments
    .Where(a => a.ParameterType.Name != "CancellationToken")
    .Select(p =>
    {
        RegRange(p.ParameterType.Namespaces);
        return @$"
        public {p.ParameterType.Name} {p.Name} {{ get; set; }}{(p.ParameterType.IsNullable || !p.ParameterType.IsReferenceType ? "" : " = null!;")}";
    }))}
    }}";
                }));
        }))}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }
}