<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<Version>0.0.1-beta</Version>
		<Authors>Willem Beltman</Authors>
		<Company>Willem Beltman</Company>

		<PackageId>gAPI.AutoSerializer</PackageId>
		<Description>gAPI AutoSerializer source generator.</Description>
		<PackageTags>gapi;roslyn;source-generator;analyzer;codegen;dotnet</PackageTags>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/willembeltman/gAPI</PackageProjectUrl>
		<RepositoryUrl>https://github.com/willembeltman/gAPI</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README.md</PackageReadmeFile>

		<DevelopmentDependency>true</DevelopmentDependency>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<PackageReleaseNotes>Improved record support with inheritance.</PackageReleaseNotes>

		<!-- Dit zorgt ervoor dat de DLL niet in de standaard 'lib' map terechtkomt -->
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<NoPackageAnalysis>true</NoPackageAnalysis>
	</PropertyGroup>

	<ItemGroup>
		<!-- Up-to-date en specifieke packages voor C# Source Generators -->
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<!-- Zorgt dat je README netjes meegaat in het NuGet-pakket -->
		<None Include="README.md" Pack="true" PackagePath="" />

		<!-- Plaatst je gecompileerde generator DLL exact in de juiste analyzer-map voor de compiler -->
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

</Project>
