<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<Version>0.0.1-alpha</Version>
		<Authors>Willem Beltman</Authors>
		<Company>Willem Beltman</Company>

		<PackageId>gAPI.AutoSerializer</PackageId>
		<Title>gAPI AutoSerializer</Title>
		<Description>
			gAPI source analyzer and generator for automatic serialization code generation.
		</Description>

		<PackageTags>gapi;api;rpc;codegen;dotnet;source-generator;roslyn;analyzer</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/willembeltman/gAPI</PackageProjectUrl>
		<RepositoryUrl>https://github.com/willembeltman/gAPI</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README.md</PackageReadmeFile>

		<IncludeSymbols>false</IncludeSymbols>
		<IncludeSource>false</IncludeSource>

		<DevelopmentDependency>true</DevelopmentDependency>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

		<!-- Niet noodzakelijk, maar prima voor analyzer packages -->
		<IncludeBuildOutput>true</IncludeBuildOutput>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Common"
						  Version="5.9.0"
						  PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md"
			  Pack="true"
			  PackagePath="" />
	</ItemGroup>

</Project>