<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<Version>0.0.1-alpha</Version>
		<Authors>Willem Beltman</Authors>
		<Company>Willem Beltman</Company>

		<PackageId>gAPI.AutoSerializer</PackageId>
		<Description>gAPI AutoSerializer source generator.</Description>
		<PackageTags>gapi;roslyn;source-generator;analyzer;codegen;dotnet</PackageTags>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/willembeltman/gAPI</PackageProjectUrl>
		<RepositoryUrl>https://github.com/willembeltman/gAPI</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README.md</PackageReadmeFile>

		<DevelopmentDependency>true</DevelopmentDependency>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Common"
                          Version="5.9.0"
                          PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md"
              Pack="true"
              PackagePath="" />
	</ItemGroup>

	<Target Name="PackAnalyzer" BeforeTargets="Pack">
		<ItemGroup>
			<None Include="$(TargetPath)"
                  Pack="true"
                  PackagePath="analyzers/dotnet/cs" />
		</ItemGroup>
	</Target>

</Project>