using gAPI.AutoSerializer;
using gAPI.AutoWss.Client.Helpers;
using gAPI.AutoWss.Client.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWss.Client.Generators.Wss;

public class ClientConnectionGenerator : _BaseGenerator
{
    public ClientConnectionGenerator(Generator context)
    {
        Context = context;

        OwnClientConnection = context.SharedReferences.OwnClientConnection;
        if (OwnClientConnection != null)
        {
            Namespace = OwnClientConnection.Namespace;
            Name = OwnClientConnection.Name;
        }
        else
        {
            Namespace = "gAPI.Generated";
            Name = "ClientConnection";
        }

        FileName = $"Wss/{Name}.g.cs";
        Directory = "";

        PropertyHelper = new GeneratePropertyHelper([], [.. Context.CustomSpanSerializers], [], Reg, NeededSpanSerializers);
    }

    public Generator Context { get; }
    public SharedReference? OwnClientConnection { get; }

    public SharedReference WssClientConnection => Context.SharedReferences.WssClientConnection;
    public SharedReference IClientConnection => Context.IClientConnection;
    public SharedReference IClientAuthenticatedHttpClient => Context.SharedReferences.IClientAuthenticatedHttpClient;
    public SharedReference SubscribeDto => Context.SharedReferences.SubscribeDto;
    public SharedReference InvokeRequestDto => Context.SharedReferences.InvokeRequestDto;
    public SharedReference SendRequestDto => Context.SharedReferences.SendRequestDto;
    public SharedReference UnsubscribeDto => Context.SharedReferences.UnsubscribeDto;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference StreamingResponseDto => Context.SharedReferences.StreamingResponseDto;
    public SharedReference IClientLoggerFactory => Context.SharedReferences.IClientLoggerFactory;

    public List<INamedTypeSymbol> NeededSpanSerializers { get; private set; } = [];
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        if (OwnClientConnection != null)
        {
            Code = "";
            return;
        }

        Reg("Microsoft.Extensions.Logging");
        Reg("Microsoft.Extensions.Options");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg("System.Runtime.CompilerServices");
        Reg(WssClientConnection);
        Reg(IClientConnection);
        Reg(IClientAuthenticatedHttpClient);
        Reg(SubscribeDto);
        Reg(InvokeRequestDto);
        Reg(SendRequestDto);
        Reg(UnsubscribeDto);
        Reg(ServiceId);
        Reg(StreamingResponseDto);
        Reg(IClientLoggerFactory);
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        var functions = string.Empty;
        var functionNames = new HashSet<string>();

        var innerCode = 

        Code = @$"
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}
    : {WssClientConnection}, {IClientConnection}
{{
    public {Name}(
        {IClientAuthenticatedHttpClient} httpClient,
        string wssBackendUrl)
        : base(httpClient, wssBackendUrl)
    {{
        ___Logger = (({IClientLoggerFactory})this).CreateLogger<{Name}>();{string.Join("", Context.Apis.Select(api => $@"
        {api} = new {api}(this, this, httpClient);"))}
    }}

    readonly ILogger ___Logger;
    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];
    {GenerateApiProperties()}
    {GenerateHubProperties()}
    {GenerateSubscribe()}{GenerateUnsubscibe()}
    {GenerateSendRequest(ref functions, functionNames)}{GenerateInvokeRequest(ref functions, functionNames)}
    {string.Join("", Context.ServiceContext.HubInterfaces.Select(Interface => GenerateMethods(ref functions, functionNames, Interface)))}
    {functions}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }

    private string GenerateApiProperties()
    {
        return string.Join("", Context.Apis.Select(api => $@"
    
    public {api} {api} {{ get; }}
    {api.Interface} {IClientConnection}.{api} => {api};"));
    }
    private string GenerateHubProperties()
    {
        return string.Join("", Context.ServiceContext.HubInterfaces.Select(@interface => $@"

    readonly List<{@interface}> {@interface.CleanName.ToMultiple()} = [];
    readonly SemaphoreSlim {@interface.CleanName.ToMultiple()}Lock = new(1, 1);
    
    private async Task<{@interface}[]> Get{@interface.CleanName.ToMultiple()}SnapshotAsync()
    {{
        await {@interface.CleanName.ToMultiple()}Lock.WaitAsync();
        try
        {{
            return [.. {@interface.CleanName.ToMultiple()}];
        }}
        finally
        {{
            {@interface.CleanName.ToMultiple()}Lock.Release();
        }}
    }}"));
    }

    private string GenerateSubscribe()
    {
        return $@"
    public async Task SubscribeAsync(object implementation, CancellationToken ___ct = default)
    {{
        await TryConnectAsync(___ct);{string.Join("", Context.ServiceContext.HubInterfaces.Select(hub => $@"

        if (implementation is {hub} {hub.CleanName.ToCamelCase()})
        {{
            if (___Logger.IsEnabled(LogLevel.Trace))
                ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" SubscribeAsync({{serviceId}})"", ""{hub}"");

            await {hub.CleanName.ToMultiple()}Lock.WaitAsync(___ct);
            try
            {{
                {hub.CleanName.ToMultiple()}.Add({hub.CleanName.ToCamelCase()});
            }}
            finally
            {{
                {hub.CleanName.ToMultiple()}Lock.Release();
            }}

            await Send_Subscribe_ToServerAsync(new {SubscribeDto}(
                new ServiceId(""{hub}""),
                HttpClient.UserId,
                HttpClient.SessionId
            ), ___ct);
        }}"))}
    }}";
    }
    private string GenerateUnsubscibe()
    {
        return $@"
    public async Task UnsubscribeAsync(object implementation, CancellationToken ___ct = default)
    {{
        if (!Initialized)
            return;{string.Join("", Context.ServiceContext.HubInterfaces.Select(hub => $@"

        if (implementation is {hub} {hub.CleanName.ToCamelCase()})
        {{
            if (___Logger.IsEnabled(LogLevel.Trace))
                ___Logger.LogTrace(""UnsubscribeAsync({{serviceId}})"", ""{hub}"");

            await {hub.CleanName.ToMultiple()}Lock.WaitAsync(___ct);
            try
            {{
                {hub.CleanName.ToMultiple()}.Remove({hub.CleanName.ToCamelCase()});
            }}
            finally
            {{
                {hub.CleanName.ToMultiple()}Lock.Release();
            }}

            await Send_Unsubscribe_ToServerAsync(new {UnsubscribeDto}(
                new {ServiceId}(""{hub}""),
                HttpClient.UserId,
                HttpClient.SessionId
            ), ___ct);
        }}"))}
    }}";
    }

    private string GenerateSendRequest(ref string functions2, HashSet<string> functionNames)
    {
        var functions = "";
        var code = $@"
    protected override async Task Send_SendRequest_ToServiceAsync({SendRequestDto} ___sendRequest, CancellationToken ___ct)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""Send_SendRequest_ToServiceAsync({{___sendRequest}})"", ___sendRequest);
        {(Context.ServiceContext.HubInterfaces.Any(hub => hub.Methods.Any(a => a.ResponseType.IsTask)) ? $@"
        switch (___sendRequest.Routing.ServiceId.Value)
        {{{string.Join("", Context.ServiceContext.HubInterfaces.Where(hub => hub.Methods.Any(a => a.ResponseType.IsTask)).Select(hub => $@"
            case ""{hub}"":
                {{
                    var clients = await Get{hub.CleanName.ToMultiple()}SnapshotAsync();
                    switch (___sendRequest.Routing.MethodId.Value)
                    {{{string.Join("", hub.Methods.Where(a => a.ResponseType.IsTask).Select(method => $@"
                        case ""{method}"":
                            {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false) ? $@"
                                var ___offset = 0;
                                var ___span = new Span<byte>(___sendRequest.BinaryData);{string.Join("", method.Arguments
            .Select((arg, index) => (arg, index))
            .Where(a => a.arg.ParameterType.IsCancellationToken == false)
            .Select(a => a.arg.ParameterType.IsIAsyncEnumerable
                ? $@"
                                var {a.arg.Name.ToCamelCase()} = RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___sendRequest.Routing, {a.index}, {@method.Interface}_{method}_{a.index}_Deserializer);"
                : $@"
                                var {a.arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions, functionNames)};"))}" : "")}
                                foreach (var client in clients)
                                {{
                                    await client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
                                        {arg.Name.ToCamelCase()}" : $@"
                                        ___ct"))});
                                }}
                                return;
                            }}"))}
                    }}
                    break;
                }}"))}
        }}" : "")}

        throw new Exception($""Service \""{{___sendRequest.Routing.ServiceId.Value}}\"" / Method \""{{___sendRequest.Routing.MethodId.Value}}\"" not found"");
    }}";
        functions2 += functions;
        return code;
    }
    private string GenerateInvokeRequest(ref string functions3, HashSet<string> functionNames)
    {
        var functions2 = "";
        var code = $@"
    protected override async IAsyncEnumerable<byte[]> Send_InvokeRequest_ToServiceAsync({InvokeRequestDto} ___invokeRequest, [EnumeratorCancellation] CancellationToken ___ct)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""Send_InvokeRequest_ToServiceAsync({{___invokeRequest}})"", ___invokeRequest);
{(Context.ServiceContext.HubInterfaces.Any(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask == false)) ? $@"

        switch (___invokeRequest.Routing.ServiceId.Value)
        {{{string.Join("", Context.ServiceContext.HubInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsTask == false)).Select(hub => $@"
            case ""{hub}"":
                {{
                    var clients = await Get{hub.CleanName.ToMultiple()}SnapshotAsync();
                    switch (___invokeRequest.Routing.MethodId.Value)
                    {{{string.Join("", hub.Methods.Where(a => a.ResponseType.IsTask == false).Select(method =>
        {
            var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
            return
                method.ResponseType.IsTaskT
                ? $@"
                        case ""{method}"":
                            {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false) ? $@"
                                var ___offset = 0;
                                var ___span = new Span<byte>(___invokeRequest.BinaryData);{string.Join("", method.Arguments
            .Select((arg, index) => (arg, index))
            .Where(a => a.arg.ParameterType.IsCancellationToken == false)
            .Select(a => a.arg.ParameterType.IsIAsyncEnumerable
                ? $@"
                                var {a.arg.Name.ToCamelCase()} = RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___invokeRequest.Routing, {a.index}, {@method.Interface}_{method}_{a.index}_Deserializer);"
                : $@"
                                var {a.arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions2, functionNames)};"))}" : "")}
                                foreach (var client in clients)
                                {{
                                    var response = client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
                                        {arg.Name.ToCamelCase()}" : $@"
                                        ___ct"))});
                                    {(returnTypeInner.IsHubResultT ? $@"
                                    response.UserId = HttpClient.UserId;
                                    response.SessionId = HttpClient.SessionId;
                                    " : "")}
                                    yield return {hub}_{method}_Serializer(response);
                                }}
                            }}
                            yield break;"
                :
                    method.ResponseType.IsIAsyncEnumerable
                    ? $@"
                        case ""{method}"":
                            {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false) ? $@"
                                var ___offset = 0;
                                var ___span = new Span<byte>(___invokeRequest.BinaryData);{string.Join("", method.Arguments
                                    .Select((arg, index) => (arg, index))
                                    .Where(a => a.arg.ParameterType.IsCancellationToken == false)
                                    .Select(a => a.arg.ParameterType.IsIAsyncEnumerable
                                    ? $@"
                                var {a.arg.Name.ToCamelCase()} = RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___invokeRequest.Routing, {a.index}, {@method.Interface}_{method}_{a.index}_Deserializer);"
                                    : $@"
                                var {a.arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions2, functionNames)};"))}" : "")}
                                foreach (var client in clients)
                                {{
                                    var responses = client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
                                        {arg.Name.ToCamelCase()}" : $@"
                                        ___ct"))});
                                    await foreach (var response in responses)
                                    {{{(returnTypeInner.IsHubResultT ? $@"
                                        response.UserId = HttpClient.UserId;
                                        response.SessionId = HttpClient.SessionId;
                                        " : "")}
                                        yield return {hub}_{method}_Serializer(response);
                                    }}
                                }}
                            }}
                            yield break;"
                    : "";
        }))}
                    }}
                    break;
                }}"))}
        }}" : "yield break;")}

        throw new Exception($""Service \""{{___invokeRequest.Routing.ServiceId.Value}}\"" / Method \""{{___invokeRequest.Routing.MethodId.Value}}\"" not found"");
    }}";
        functions3 += functions2;
        return code;
    }

    private string GenerateMethods(ref string functions2, HashSet<string> functionNames, Interface @interface)
    {
        var functions = "";
        var code = string.Join("\r\n", @interface.Methods.Select(method => GenerateMethod(ref functions, functionNames, @interface, method)));
        functions2 += functions;
        return code;
    }
    private string GenerateMethod(ref string functions2, HashSet<string> functionNames, Interface @interface, InterfaceMethod method)
    {
        var code = "";
        var functions = "";

        if (method.ResponseType.IsTask)
        {
    //        code += $@"
    //public async Task {@interface}_{method}(SendRequestDto ___sendRequest, {@interface}[] ___clients, CancellationToken ___ct)
    //{{
    //    var ___offset = 0;
    //    var ___span = new Span<byte>(___sendRequest.BinaryData);{string.Join("", method.Arguments
    //.Select((arg, index) => (arg, index))
    //.Where(a => a.arg.ParameterType.IsCancellationToken == false)
    //.Select(a => a.arg.ParameterType.IsIAsyncEnumerable
    //? $@"
    //    var {a.arg.Name.ToCamelCase()} = RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___sendRequest.Routing, {a.index}, {@method.Interface}_{method}_{a.index}_Deserializer);"
    //: $@"
    //    var {a.arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions, functionNames)};"))}
    //    foreach (var ___client in ___clients)
    //    {{
    //        await ___client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
    //            {arg.Name.ToCamelCase()}" : $@"
    //            ___ct"))});
    //    }}
    //}}";
        }
        if (method.ResponseType.IsTaskT)
        {
            var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
    //        code += $@"
    //public async IAsyncEnumerable<byte[]> {@interface}_{method}({InvokeRequestDto} ___invokeRequest, {@interface}[] ___clients, CancellationToken ___ct)
    //{{
    //    var ___offset = 0;
    //    var ___span = new Span<byte>(___invokeRequest.BinaryData);{string.Join("", method.Arguments
    //        .Select((arg, index) => (arg, index))
    //        .Where(a => a.arg.ParameterType.IsCancellationToken == false)
    //        .Select(a => a.arg.ParameterType.IsIAsyncEnumerable
    //        ? $@"
    //    var {a.arg.Name.ToCamelCase()} = RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___invokeRequest.Routing, {a.index}, {@method.Interface}_{method}_{a.index}_Deserializer);"
    //        : $@"
    //    var {a.arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions, functionNames)};"))}
    //    foreach (var client in clients)
    //    {{
    //        var response = client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
    //            {arg.Name.ToCamelCase()}" : $@"
    //            ___ct"))});
    //        {(returnTypeInner.IsHubResultT ? $@"
    //        response.UserId = HttpClient.UserId;
    //        response.SessionId = HttpClient.SessionId;
    //        " : "")}
    //        yield return {@interface}_{method}_Serializer(response);
    //    }}
    //}}";
        }

        if (method.ResponseType.IsIAsyncEnumerable)
        {
            var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
    //        code = $@"
    //public async IAsyncEnumerable<byte[]> {@interface}_{method}({InvokeRequestDto} ___invokeRequest, {@interface}[] ___clients, CancellationToken ___ct)
    //{{
    //    var ___offset = 0;
    //    var ___span = new Span<byte>(___invokeRequest.BinaryData);{string.Join("", method.Arguments
    //        .Select((arg, index) => (arg, index))
    //        .Where(a => a.arg.ParameterType.IsCancellationToken == false)
    //        .Select(a => a.arg.ParameterType.IsIAsyncEnumerable
    //        ? $@"
    //    var {a.arg.Name.ToCamelCase()} = RegisterRemoteAsyncEnumerableArgument<{a.arg.ParameterType.UnderlayingTypes.Single()}>(___invokeRequest.Routing, {a.index}, {@method.Interface}_{method}_{a.index}_Deserializer);"
    //        : $@"
    //    var {a.arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(a.arg.ParameterType.Type, false, ref functions, functionNames)};"))}
    //    foreach (var ___client in ___clients)
    //    {{
    //        var responses = ___client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
    //            {arg.Name.ToCamelCase()}" : $@"
    //            ___ct"))});
    //        await foreach (var response in responses)
    //        {{{(returnTypeInner.IsHubResultT ? $@"
    //            response.UserId = HttpClient.UserId;
    //            response.SessionId = HttpClient.SessionId;
    //            " : "")}
    //            yield return {@interface}_{method}_Serializer(response);
    //        }}
    //    }}
    //}}"; 
            code = $@"
    public byte[] {@interface}_{method}_Serializer({returnTypeInner} value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___Buffer);{PropertyHelper.GenerateSpanWriteCode(returnTypeInner.Type, "value", "        ", false)}
        return ___span.Slice(0, ___offset).ToArray();
    }}";
        }

        foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
        {
            if (!arg.ParameterType.IsIAsyncEnumerable)
                continue;

            var innerType = arg.ParameterType.UnderlayingTypes.Single();
            code += $@"
    public {innerType} {@interface}_{method}_{index}_Deserializer(byte[] value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(value);
        return {PropertyHelper.GenerateSpanReadCode(innerType.Type, false, ref functions, functionNames)};
    }}";
        }

        functions2 += functions;

        return code;
    }
}