using gAPI.AutoHub.Models;

namespace gAPI.AutoHub.Generators;

internal class AddAutoHubExtentionGenerator : BaseGenerator
{
    internal AddAutoHubExtentionGenerator(ServiceContext serviceContext, SignalRHubGenerator signalRHub)
    {
        ServiceContext = serviceContext;
        SignalRHub = signalRHub;

        Directory = serviceContext.Config.AddAutoHubServices_Destination.Directory;
        Namespace = serviceContext.Config.AddAutoHubServices_Destination.Namespace;

        Name = "AddAutoHubExtention";
        FileName = $"{Name}.g.cs";
    }

    public ServiceContext ServiceContext { get; }
    public SignalRHubGenerator SignalRHub { get; }

    internal void GenerateCode()
    {
        Reg(SignalRHub);
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.AspNetCore.Routing");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("System.Reflection");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
namespace {Namespace};

public static class {Name}
{{
    public static void AddAutoHub(this IServiceCollection services)
    {{
        services.AddSignalR();
        services.AddAutoHubServices();
    }}

    public static void MapAutoHub(this IEndpointRouteBuilder app)
    {{
        app.MapHub<{SignalRHub.Name}>(""/hubs/signalrhub"");
    }}
}}
";

    }
}