using gAPI.AutoApiSse.Client.Models;

namespace gAPI.AutoApiSse.Client.Generators;

public class AddAutoApiSseClientExtensionGenerator : BaseGenerator
{
    public AddAutoApiSseClientExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AutoApiSseClientExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public ApiClientGenerator[] Clients => Context.Clients;
    public SharedReference ClientConnection => Context.ClientConnection;
    public SharedReference IClientConnection => Context.SharedReferences.ISseClientConnection;
    public SharedReference SseManagerCollection => Context.SharedReferences.SseManagerCollection;

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg(ClientConnection);
        Reg(IClientConnection);
        Reg(SseManagerCollection);

        var propertiesCode = "";
        foreach (var client in Clients)
        {
            var @interface = client.Interface;
            Reg(@interface);
            Reg(client);
            propertiesCode += $"\r\n        services.AddScoped<{@interface.Name}, {client.Name}>();";
        }

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
namespace {Namespace};

public static class {Name}
{{
    public static void AddAutoApiSseClient(this IServiceCollection services)
    {{{propertiesCode}
        services.AddScoped<{ClientConnection}>();
        services.AddScoped<{IClientConnection}>(sp => sp.GetRequiredService<{ClientConnection}>());

        var sseManagerCollection = new {SseManagerCollection}();
        services.AddSingleton(sseManagerCollection);

    }}
}}";
    }
}