using gAPI.AutoAuth.Server.Models;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class AuthenticationServiceGenerator : _BaseGenerator
{
    public AuthenticationServiceGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AuthenticationService";
        FileName = $"Authentication/{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IAuthenticationService => Context.IAuthenticationService;
    public SharedReference IStateMappingT => Context.SharedReferences.IStateMappingT;
    public SharedReference AuthenticationServiceT => Context.SharedReferences.AuthenticationServiceT;

    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;
    public SharedReference State => StateDto ?? AuthStateDto;

    public SharedReference AuthUserEntity => Context.SharedReferences.AuthUser;
    public SharedReference? UserEntity => Context.SharedReferences.User;
    public SharedReference User => UserEntity ?? AuthUserEntity;




    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference AuthenticationInitializeResult => Context.SharedReferences.AuthenticationInitializeResult;
    public SharedReference AuthenticationHeaders => Context.SharedReferences.AuthenticationHeaders;
    public SharedReference SessionCache => Context.SharedReferences.SessionCache;
    public SharedReference IAuthenticationStateFactoryT => Context.SharedReferences.IAuthenticationStateFactoryT;
    public SharedReference IUserTokenFactoryT => Context.SharedReferences.IUserTokenFactoryT;
    public SharedReference IAuthenticationCheckT => Context.SharedReferences.IAuthenticationCheckT;
    public SharedReference IStateParserT => Context.SharedReferences.IStateParserT;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;

    public override void GenerateCode()
    {
        Reg(State);
        Reg(User);
        Reg(IAuthenticationCheckT);
        Reg(IUserTokenFactoryT);
        Reg(UserId);
        Reg(SessionCache);
        Reg(IAuthenticationStateFactoryT);
        Reg(AuthenticationInitializeResult);
        Reg(SessionId);
        Reg(UserId);
        Reg(IServerAuthenticationService);
        Reg(AuthenticationHeaders);
        Reg(IStateParserT);
        Reg(IAuthenticationService);
        Reg(FabricClient);
        Reg("Microsoft.Extensions.Primitives");
        Reg("System.Security.Claims");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {IAuthenticationStateFactoryT}<{User}> authenticationStateFactory,
    {IUserTokenFactoryT}<{User}> userTokenFactory,
    {IStateMappingT}<{User}, {State}> stateMapping,
    {IStateParserT}<{State}> stateSerializer,
    IHostEnvironment hostEnvironment,
    {FabricClient} fabricClient,
    IEnumerable<{IAuthenticationCheckT}<{User}, {State}>> authenticationChecks) 
    : {AuthenticationServiceT}<{User}, {State}>(
        authenticationStateFactory,
        userTokenFactory,
        stateMapping,
        stateSerializer,
        hostEnvironment,
        fabricClient,
        authenticationChecks)
    , {IAuthenticationService}
{{
}}";
    }
}