using gAPI.AutoAuth.Server.Models;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class IAuthenticationServiceGenerator : _BaseGenerator
{
    public IAuthenticationServiceGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "IAuthenticationService";
        FileName = $"Authentication/{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;
    public SharedReference State => StateDto ?? AuthStateDto;

    public SharedReference AuthUserEntity => Context.SharedReferences.AuthUser;
    public SharedReference? UserEntity => Context.SharedReferences.User;
    public SharedReference User => UserEntity ?? AuthUserEntity;

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference AuthenticationState => Context.SharedReferences.AuthenticationState;

    public SharedReference IAuthenticationServiceT => Context.SharedReferences.IAuthenticationServiceT;

    public override void GenerateCode()
    {
        Reg(State);
        Reg(User);
        Reg(IServerAuthenticationService);
        Reg(AuthenticationState);
        Reg(IAuthenticationServiceT);
        Reg("Microsoft.Extensions.Primitives");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name}
    : {IAuthenticationServiceT}<{User}, {State}>
    , {IServerAuthenticationService}
{{
}}

";
    }
}