using gAPI.AutoAuth.Server.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class IStateParserGenerator : _BaseGenerator
{
    public IStateParserGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "IStateParser";
        FileName = $"Authentication/{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference IStateParserT => Context.SharedReferences.IStateParserT;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;

    public SharedReference State => StateDto ?? AuthStateDto;

    public List<INamedTypeSymbol> NeededState_ListForBeingLazy { get; private set; } = new();

    public override void GenerateCode()
    {
        if (StateDto != null)
            NeededState_ListForBeingLazy.Add(StateDto._NamedTypeSymbol!);

        Reg(State);
        Reg(IStateParserT);
        Reg("Microsoft.Extensions.Primitives");
        
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name} : {IStateParserT}<{State}>
{{
}}";
    }
}