using gAPI.AutoAuth.Server.Models;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class NoDbAuthenticationServiceGenerator : _BaseGenerator
{
    public NoDbAuthenticationServiceGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "NoDbAuthenticationService";
        FileName = $"Authentication/{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IAuthenticationService => Context.IAuthenticationService;
    public SharedReference IStateMappingT => Context.SharedReferences.IStateMappingT;
    public SharedReference AuthenticationServiceT => Context.SharedReferences.AuthenticationServiceT;

    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;
    public SharedReference State => StateDto ?? AuthStateDto;

    public SharedReference AuthUserEntity => Context.SharedReferences.AuthUser;
    public SharedReference? UserEntity => Context.SharedReferences.User;
    public SharedReference User => UserEntity ?? AuthUserEntity;




    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference NoDbServerAuthenticationServiceT => Context.SharedReferences.NoDbServerAuthenticationServiceT;
    public SharedReference AuthenticationInitializeResult => Context.SharedReferences.AuthenticationInitializeResult;
    public SharedReference AuthenticationHeaders => Context.SharedReferences.AuthenticationHeaders;
    public SharedReference SessionCache => Context.SharedReferences.SessionCache;
    public SharedReference IAuthenticationStateFactoryT => Context.SharedReferences.IAuthenticationStateFactoryT;
    public SharedReference IUserTokenFactoryT => Context.SharedReferences.IUserTokenFactoryT;
    public SharedReference IAuthenticationCheckT => Context.SharedReferences.IAuthenticationCheckT;
    public SharedReference IStateParserT => Context.SharedReferences.IStateParserT;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference AuthenticationOptions => Context.SharedReferences.AuthenticationOptions;

    public override void GenerateCode()
    {
        Reg(AuthenticationOptions);
        Reg("Microsoft.Extensions.Primitives");
        Reg("System.Security.Claims");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {IStateMappingT.FullName}<{User.FullName}, {State.FullName}> stateMapping,
    {IStateParserT.FullName}<{State.FullName}> stateSerializer,
    {FabricClient.FullName} fabricClient,
    {AuthenticationOptions} authenticationOptions) 
    : {NoDbServerAuthenticationServiceT.FullName}<{User.FullName}, {State.FullName}>(
        stateMapping,
        stateSerializer,
        fabricClient,
        authenticationOptions)
    , {IAuthenticationService.FullName}
{{
}}";
    }
}