using gAPI.AutoAuth.Server.Models;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class NoDbAuthenticationServiceGenerator : _BaseGenerator
{
    public NoDbAuthenticationServiceGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "NoDbAuthenticationService";
        FileName = $"Authentication/{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IAuthenticationService => Context.IAuthenticationService;
    public SharedReference IStateMappingT => Context.SharedReferences.IStateMappingT;
    public SharedReference AuthenticationServiceT => Context.SharedReferences.AuthenticationServiceT;

    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;
    public SharedReference State => StateDto ?? AuthStateDto;

    public SharedReference AuthUserEntity => Context.SharedReferences.AuthUser;
    public SharedReference? UserEntity => Context.SharedReferences.User;
    public SharedReference User => UserEntity ?? AuthUserEntity;




    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference NoDbServerAuthenticationServiceT => Context.SharedReferences.NoDbServerAuthenticationServiceT;
    public SharedReference AuthenticationInitializeResult => Context.SharedReferences.AuthenticationInitializeResult;
    public SharedReference AuthenticationHeaders => Context.SharedReferences.AuthenticationHeaders;
    public SharedReference SessionCache => Context.SharedReferences.SessionCache;
    public SharedReference IAuthenticationStateFactoryT => Context.SharedReferences.IAuthenticationStateFactoryT;
    public SharedReference IUserTokenFactoryT => Context.SharedReferences.IUserTokenFactoryT;
    public SharedReference IAuthenticationCheckT => Context.SharedReferences.IAuthenticationCheckT;
    public SharedReference IStateParserT => Context.SharedReferences.IStateParserT;
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference AuthenticationOptions => Context.SharedReferences.AuthenticationOptions;

    public override void GenerateCode()
    {
        Reg(State);
        Reg(User);
        Reg(IAuthenticationCheckT);
        Reg(IUserTokenFactoryT);
        Reg(UserId);
        Reg(SessionCache);
        Reg(IAuthenticationStateFactoryT);
        Reg(AuthenticationInitializeResult);
        Reg(SessionId);
        Reg(UserId);
        Reg(NoDbServerAuthenticationServiceT);
        Reg(AuthenticationHeaders);
        Reg(IStateParserT);
        Reg(IAuthenticationService);
        Reg(FabricClient);
        Reg(AuthenticationOptions);
        Reg("Microsoft.Extensions.Primitives");
        Reg("System.Security.Claims");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {IStateMappingT}<{User}, {State}> stateMapping,
    {IStateParserT}<{State}> stateSerializer,
    {FabricClient} fabricClient,
    {AuthenticationOptions} authenticationOptions,
    IEnumerable<{IAuthenticationCheckT}<{User}, {State}>> authenticationChecks) 
    : {NoDbServerAuthenticationServiceT}<{User}, {State}>(
        stateMapping,
        stateSerializer,
        fabricClient,
        authenticationOptions,
        authenticationChecks)
    , {IAuthenticationService}
{{
}}";
    }
}