using gAPI.AutoAuth.Server;
using gAPI.AutoAuth.Server.Generators;
using gAPI.AutoAuth.Server.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class StateParserGenerator : _BaseGenerator
{
    public StateParserGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "StateParser";
        FileName = $"Authentication/{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference IStateParser => Context.IStateParser;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;

    public SharedReference State => StateDto ?? AuthStateDto;

    public List<INamedTypeSymbol> NeededState_ListForBeingLazy { get; private set; } = new();

    public override void GenerateCode()
    {
        if (StateDto != null)
            NeededState_ListForBeingLazy.Add(StateDto._NamedTypeSymbol!);

        Reg(State);
        Reg(IStateParser);
        Reg("Microsoft.Extensions.Primitives");
        
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name} : {IStateParser}
{{
    public bool TryParse(string? value, out {State} state)
    {{
        state = default!;

        if (string.IsNullOrWhiteSpace(value))
            return false;

        try
        {{
            var data = Convert.FromBase64String(value);
            var offset = 0;
            try
            {{
                state = data.Read{State}(ref offset);
            }}
            catch
            {{
                return false;
            }}
            return true;
        }}
        catch
        {{
            return false;
        }}
    }}
    public StringValues ToStringValuesBase64({State} value)
    {{
        string? base64{State} = ToStringBase64(value);
        return new StringValues(base64{State});
    }}
    public string? ToStringBase64({State}? value)
    {{
        if (value == null)
            value = new {State}();

        byte[] Buffer = new byte[64 * 1024];
        var span = new Span<byte>(Buffer, 0, Buffer.Length);
        var offset = 0;
        span.Write(ref offset, value);
        var base64value = Convert.ToBase64String(Buffer, 0, offset);
        return base64value;
    }}
    public bool IsDifferent({State}? value1, {State}? value2)
    {{
        if (value1 == null && value2 == null) return true;
        if (value1 == null || value2 == null) return false;
        return value1.IsDifferent(value2);
    }}
    public {State}? CreateCopy({State}? value)
    {{
        return value?.CreateCopy();
    }}
    
}}";
    }
}