using gAPI.AutoAuth.Server.Models;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class AddAutoAuthServerExtensionGenerator : _BaseGenerator
{
    public AddAutoAuthServerExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoAuthServerExtension";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IAuthenticationService => Context.IAuthenticationService;

    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;
    public SharedReference State => StateDto ?? AuthStateDto;

    public SharedReference AuthUserEntity => Context.SharedReferences.AuthUser;
    public SharedReference? UserEntity => Context.SharedReferences.User;
    public SharedReference User => UserEntity ?? AuthUserEntity;

    public SharedReference AuthenticationDbContextT => Context.SharedReferences.AuthenticationDbContextT;
    public SharedReference? CustomDbContext => Context.SharedReferences.CustomDbContext;
    public string ApplicationDbContext =>
        CustomDbContext?.FullName
        ?? $"{AuthenticationDbContextT.FullName}<{User}>";


    public SharedReference AuthenticationStateMappingT => Context.SharedReferences.AuthenticationStateMappingT;
    public SharedReference? CustomStateMapping => Context.SharedReferences.CustomStateMapping;
    public string StateMapping =>
        CustomStateMapping?.Name
        ?? $"{AuthenticationStateMappingT}<{User}, {State}>";


    public SharedReference AuthenticationStateFactoryT => Context.SharedReferences.AuthenticationStateFactoryT;
    public SharedReference IAuthenticationServiceT => Context.SharedReferences.IAuthenticationServiceT;
    public SharedReference IUserTokenFactoryT => Context.SharedReferences.IUserTokenFactoryT;
    public SharedReference UserTokenFactoryT => Context.SharedReferences.UserTokenFactoryT;
    public SharedReference AuthenticationSecurityT => Context.SharedReferences.AuthenticationSecurityT;
    public SharedReference IAuthenticationStateFactoryT => Context.SharedReferences.IAuthenticationStateFactoryT;
    public SharedReference AccountServiceT => Context.SharedReferences.AccountServiceT;
    public SharedReference IStateMappingT => Context.SharedReferences.IStateMappingT;
    public SharedReference ServerConfig => Context.SharedReferences.ServerConfig;
    public SharedReference AuthenticationService => Context.AuthenticationService;
    public SharedReference AuthenticationServiceT => Context.SharedReferences.AuthenticationServiceT;

    public SharedReference ServerAuthenticationAccessor => Context.SharedReferences.ServerAuthenticationAccessor;
    public SharedReference IAccountService => Context.SharedReferences.IAccountService;
    public SharedReference IAuthenticationSecurity => Context.SharedReferences.IAuthenticationSecurity;
    public SharedReference AuthenticationHandler => Context.SharedReferences.AuthenticationHandler;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference EmptyServerAuthenticationService => Context.SharedReferences.EmptyServerAuthenticationServiceT;

    public override void GenerateCode()
    {
        Reg(AuthenticationStateMappingT);
        Reg(AuthenticationStateFactoryT);
        Reg(IUserTokenFactoryT);
        Reg(UserTokenFactoryT);
        Reg(AuthenticationSecurityT);
        Reg(IAuthenticationStateFactoryT);
        Reg(ServerAuthenticationAccessor);
        Reg(IAccountService);
        Reg(IAuthenticationSecurity);
        Reg(AuthenticationHandler);
        Reg(IServerAuthenticationService);
        Reg(EmptyServerAuthenticationService);
        Reg(IStateMappingT);
        Reg(AuthenticationDbContextT);
        Reg(ServerConfig);
        if (CustomStateMapping != null)
            Reg(CustomStateMapping);

        Reg(State);
        Reg(User);
        Reg("Microsoft.EntityFrameworkCore");
        Reg("Microsoft.AspNetCore.Authentication");
        Reg("Microsoft.Extensions.Configuration");
        Reg("gAPI.Core.Server.Extensions");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoAuthServer(
        this IServiceCollection services,
        IConfigurationManager configuration)
    {{
        var serverConfig = configuration.CreateServerConfig();
        return AddAutoAuthServer(services, serverConfig);
    }}
    public static IServiceCollection AddAutoAuthServer(
        this IServiceCollection services, 
        {ServerConfig} serverConfig)
    {{
        return AddAutoAuthServer(
            services, 
            serverConfig.UseMemoryDatabase, 
            serverConfig.DefaultConnectionString, 
            serverConfig.LoginMaxAttempt, 
            serverConfig.LoginMaxAttemptTimeout, 
            serverConfig.RegisterMaxAttempt, 
            serverConfig.RegisterMaxAttemptTimeout, 
            serverConfig.ForgetPasswordMaxAttempt, 
            serverConfig.ForgetPasswordMaxAttemptTimeout, 
            serverConfig.ChangePasswordMaxAttempt, 
            serverConfig.ChangePasswordMaxAttemptTimeout);
    }}

    public static IServiceCollection AddAutoAuthServer(
        this IServiceCollection services,
        bool useMemoryDatabase = false,
        string? dbConnectionString = null,
        int loginMaxAttempt = 5,
        long loginMaxAttemptTimeout = 15,
        int registerMaxAttempt = 5,
        long registerMaxAttemptTimeout = 24 * 7 * 52, // 8736
        int forgetPasswordMaxAttempt = 5,
        long forgetPasswordMaxAttemptTimeout = 24,
        int changePasswordMaxAttempt = 5,
        long changePasswordMaxAttemptTimeout = 24,
        double shortHoursAgo = -1,
        double longHoursAgo = -72)
    {{
        if (dbConnectionString == null)
        {{
            services.AddScoped<{IServerAuthenticationService}, {EmptyServerAuthenticationService}<{State}>>();

            // Todo State ellende
        }}
        else
        {{
            services.AddScoped<{ServerAuthenticationAccessor}>();
            services.AddScoped<{AuthenticationService}>();
            services.AddScoped<{IAuthenticationService}>(sp =>
            {{
                var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

                if (accessor.Current is null)
                    return sp.GetRequiredService<{AuthenticationService}>();

                return (accessor.Current as {IAuthenticationService})!;
            }});
            services.AddScoped<{IAuthenticationServiceT}<{User}, {State}>>(sp =>
            {{
                var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

                if (accessor.Current is null)
                    return sp.GetRequiredService<{AuthenticationService}>();

                return (accessor.Current as {IAuthenticationServiceT}<{User}, {State}>)!;
            }});
            services.AddScoped<{AuthenticationServiceT}<{User}, {State}>>(sp =>
            {{
                var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

                if (accessor.Current is null)
                    return sp.GetRequiredService<{AuthenticationService}>();

                return (accessor.Current as {AuthenticationServiceT}<{User}, {State}>)!;
            }});
            services.AddScoped<{IServerAuthenticationService}>(sp =>
            {{
                var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

                if (accessor.Current is null)
                    return sp.GetRequiredService<{AuthenticationService}>();

                return (accessor.Current as {IServerAuthenticationService})!;
            }});

            services.AddAuthentication(""gAPI"")
                    .AddScheme<AuthenticationSchemeOptions, {AuthenticationHandler}>(""gAPI"", _ => {{ }});

            services.AddScoped<{IAuthenticationSecurity}>(sp => 
                new {AuthenticationSecurityT}<{User}, {State}>(
                    sp.GetRequiredService<{IAuthenticationServiceT}<{User}, {State}>>(),
                    sp.GetRequiredService<IDbContextFactory<{ApplicationDbContext}>>(),
                    sp.GetRequiredService<TimeProvider>(),
                    loginMaxAttempt, 
                    loginMaxAttemptTimeout,
                    registerMaxAttempt,
                    registerMaxAttemptTimeout,
                    forgetPasswordMaxAttempt,
                    forgetPasswordMaxAttemptTimeout,
                    changePasswordMaxAttempt,
                    changePasswordMaxAttemptTimeout));

            services.AddScoped<{IAuthenticationStateFactoryT}<{User}>>(sp => 
                new {AuthenticationStateFactoryT}<{User}>(
                    sp.GetRequiredService<IDbContextFactory<{ApplicationDbContext}>>(),
                    sp.GetRequiredService<TimeProvider>(),
                    shortHoursAgo,
                    longHoursAgo,
                    useMemoryDatabase));

            services.AddScoped<{IUserTokenFactoryT}<{User}>, {UserTokenFactoryT}<{User}>>();
            services.AddScoped<{IAccountService}, {AccountServiceT}<{User}, {State}>>();

            // DATABASE SECTION{(

    CustomDbContext == null ? $@"

            // ✅ Factory voor {ApplicationDbContext}
            services.AddDbContextFactory<{ApplicationDbContext}>(options =>
            {{
                if (useMemoryDatabase)
                {{
                    options.UseInMemoryDatabase(""InMemoryDb"");
                }}
                else
                {{
                    options.UseSqlServer(
                        dbConnectionString,
                        sql => sql.EnableRetryOnFailure(10, TimeSpan.FromSeconds(5), null));
                }}
            }});

            // ✅ Normale {ApplicationDbContext}
            services.AddScoped<{ApplicationDbContext}>(sp =>
                sp.GetRequiredService<IDbContextFactory<{ApplicationDbContext}>>()
                  .CreateDbContext());"

    : $@"

            // ✅ Factory voor {ApplicationDbContext}
            services.AddDbContextFactory<{ApplicationDbContext}>(options =>
            {{
                if (useMemoryDatabase)
                {{
                    options.UseInMemoryDatabase(""InMemoryDb"");
                }}
                else
                {{
                    options.UseSqlServer(
                        dbConnectionString,
                        sql => sql.EnableRetryOnFailure(10, TimeSpan.FromSeconds(5), null));
                }}
            }});

            // ✅ Normale {ApplicationDbContext}
            services.AddScoped<{ApplicationDbContext}>(sp =>
                sp.GetRequiredService<IDbContextFactory<{ApplicationDbContext}>>()
                  .CreateDbContext());

            // ✅ Normale {AuthenticationDbContextT}<{User}>
            services.AddScoped<{AuthenticationDbContextT}<{User}>>(sp =>
                sp.GetRequiredService<{ApplicationDbContext}>());

            // ✅ Factory voor {AuthenticationDbContextT}<{User}>
            services.AddScoped<IDbContextFactory<{AuthenticationDbContextT}<{User}>>>(sp =>
            {{
                var factory = sp.GetRequiredService<IDbContextFactory<{ApplicationDbContext}>>();

                return new AuthenticationDbContextFactory<{AuthenticationDbContextT}<{User}>>(
                    () => factory.CreateDbContext());
            }});"
    )}
        }}
        services.AddScoped<{IStateMappingT}<{User}, {State}>, {StateMapping}>();
        return services;
    }}
}}
";
    }
}