using gAPI.AutoAuth.Server.Models;

namespace gAPI.AutoAuth.Server.Generators.Authentication;

public class AddAutoAuthServerExtensionGenerator : _BaseGenerator
{
    public AddAutoAuthServerExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoAuthServerExtension";
        FileName = $"Startup/{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IAuthenticationService => Context.IAuthenticationService;

    public SharedReference AuthStateDto => Context.SharedReferences.AuthStateDto;
    public SharedReference? StateDto => Context.SharedReferences.StateDto;
    public SharedReference State => StateDto ?? AuthStateDto;

    public SharedReference AuthUserEntity => Context.SharedReferences.AuthUser;
    public SharedReference? UserEntity => Context.SharedReferences.User;
    public SharedReference User => UserEntity ?? AuthUserEntity;

    public SharedReference AuthenticationDbContextT => Context.SharedReferences.AuthenticationDbContextT;
    public SharedReference? CustomDbContext => Context.SharedReferences.CustomDbContext;
    public string ApplicationDbContext =>
        CustomDbContext?.FullName
        ?? $"{AuthenticationDbContextT.FullName}<{User}>";


    public SharedReference AuthenticationStateMappingT => Context.SharedReferences.AuthenticationStateMappingT;
    public SharedReference? CustomStateMapping => Context.SharedReferences.CustomStateMapping;
    public string StateMapping =>
        CustomStateMapping?.Name
        ?? $"{AuthenticationStateMappingT}<{User}, {State}>";


    public SharedReference AuthenticationStateFactoryT => Context.SharedReferences.AuthenticationStateFactoryT;
    public SharedReference IAuthenticationServiceT => Context.SharedReferences.IAuthenticationServiceT;
    public SharedReference IUserTokenFactoryT => Context.SharedReferences.IUserTokenFactoryT;
    public SharedReference UserTokenFactoryT => Context.SharedReferences.UserTokenFactoryT;
    public SharedReference AuthenticationSecurityT => Context.SharedReferences.AuthenticationSecurityT;
    public SharedReference IAuthenticationStateFactoryT => Context.SharedReferences.IAuthenticationStateFactoryT;
    public SharedReference AccountServiceT => Context.SharedReferences.AccountServiceT;
    public SharedReference IStateMappingT => Context.SharedReferences.IStateMappingT;
    public SharedReference AuthenticationService => Context.AuthenticationService;
    public SharedReference AuthenticationServiceT => Context.SharedReferences.AuthenticationServiceT;

    public SharedReference ServerAuthenticationAccessor => Context.SharedReferences.ServerAuthenticationAccessor;
    public SharedReference IAccountService => Context.SharedReferences.IAccountService;
    public SharedReference IAuthenticationSecurity => Context.SharedReferences.IAuthenticationSecurity;
    public SharedReference AuthenticationHandler => Context.SharedReferences.AuthenticationHandler;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    public SharedReference EmptyServerAuthenticationService => Context.SharedReferences.EmptyServerAuthenticationService;
    
    public override void GenerateCode()
    {
        Reg(AuthenticationStateMappingT);
        Reg(AuthenticationStateFactoryT);
        Reg(IUserTokenFactoryT);
        Reg(UserTokenFactoryT);
        Reg(AuthenticationSecurityT);
        Reg(IAuthenticationStateFactoryT);
        Reg(ServerAuthenticationAccessor);
        Reg(IAccountService);
        Reg(IAuthenticationSecurity);
        Reg(AuthenticationHandler);
        Reg(IServerAuthenticationService);
        Reg(EmptyServerAuthenticationService);
        Reg(IStateMappingT);
        if (CustomStateMapping != null)
            Reg(CustomStateMapping);

        Reg(State);
        Reg(User);
        Reg("Microsoft.AspNetCore.Authentication");

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoAuthServer(this IServiceCollection services)
    {{{(CustomDbContext == null ? $@"
        services.AddScoped<{IServerAuthenticationService}, {EmptyServerAuthenticationService}>();
" : "")}
        services.AddScoped<{ServerAuthenticationAccessor}>();
        services.AddScoped<{AuthenticationService}>();
        services.AddScoped<{IAuthenticationService}>(sp =>
        {{
            var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

            if (accessor.Current is null)
                return sp.GetRequiredService<{AuthenticationService}>();

            return (accessor.Current as {IAuthenticationService})!;
        }});
        services.AddScoped<{IAuthenticationServiceT}<{User}, {State}>>(sp =>
        {{
            var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

            if (accessor.Current is null)
                return sp.GetRequiredService<{AuthenticationService}>();

            return (accessor.Current as {IAuthenticationServiceT}<{User}, {State}>)!;
        }});
        services.AddScoped<{AuthenticationServiceT}<{User}, {State}>>(sp =>
        {{
            var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

            if (accessor.Current is null)
                return sp.GetRequiredService<{AuthenticationService}>();

            return (accessor.Current as {AuthenticationServiceT}<{User}, {State}>)!;
        }});
        services.AddScoped<{IServerAuthenticationService}>(sp =>
        {{
            var accessor = sp.GetRequiredService<{ServerAuthenticationAccessor}>();

            if (accessor.Current is null)
                return sp.GetRequiredService<{AuthenticationService}>();

            return (accessor.Current as {IServerAuthenticationService})!;
        }});

        services.AddAuthentication(""gAPI"")
                .AddScheme<AuthenticationSchemeOptions, {AuthenticationHandler}>(""gAPI"", _ => {{ }});

        services.AddScoped<{IAuthenticationSecurity}, {AuthenticationSecurityT}<{User}, {State}>>();
        services.AddScoped<{IAuthenticationStateFactoryT}<{User}>, {AuthenticationStateFactoryT}<{User}>>();
        services.AddScoped<{IUserTokenFactoryT}<{User}>, {UserTokenFactoryT}<{User}>>();
        services.AddScoped<{IAccountService}, {AccountServiceT}<{User}, {State}>>();
        services.AddScoped<{IStateMappingT}<{User}, {State}>, {StateMapping}>();
        return services;
    }}
}}
";
    }
}