<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		<Version>0.0.2-beta</Version>
		
		<!-- Zorgt ervoor dat gegenereerde code fysiek op schijf wordt opgeslagen -->
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<!-- Verplaatst de output naar een nette map in je projectroot in plaats van diep in obj -->
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

	<Target Name="ClearGeneratedFolder" BeforeTargets="BeforeBuild">
		<ItemGroup>
			<FolderToClean Include="$(ProjectDir)Generated\" />
		</ItemGroup>
		<RemoveDir Directories="@(FolderToClean)" />
		<MakeDir Directories="@(FolderToClean)" />
	</Target>
	
	<ItemGroup>
		<!-- Zorgt ervoor dat de compiler de fysieke bestanden niet dubbel meeneemt -->
		<Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\gAPI.Core\gAPI.Core.csproj" />
		<!--<PackageReference Include="gAPI.Core" Version="0.0.2-beta" />-->
	</ItemGroup>

</Project>
