using gAPI.AutoSerializer;
using gAPI.AutoWss.Client.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWss.Client.Generators.Clients;

public class ApiClient_Generator : _BaseGenerator
{
    public ApiClient_Generator(Generator context, Interface @interface)
    {
        Context = context;
        Interface = @interface;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = @interface.CleanName;
        FileName = $"Clients/{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], [.. Context.CustomSpanSerializers], [], Reg, NeededSpanSerializerTypes);
    }

    public Generator Context { get; }
    public Interface Interface { get; }
    public SharedReference WssClientConnection => Context.SharedReferences.IWssClientConnection;
    public SharedReference IClientLoggerFactory => Context.SharedReferences.IClientLoggerFactory;
    public SharedReference IClientAuthenticatedHttpClient => Context.SharedReferences.IClientAuthenticatedHttpClient;
    public SharedReference RequestId => Context.SharedReferences.RequestId;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference RoutingDto => Context.SharedReferences.RoutingDto;

    public List<INamedTypeSymbol> NeededSpanSerializerTypes { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg(Interface);
        Reg(WssClientConnection);
        Reg(IClientLoggerFactory);
        Reg(IClientAuthenticatedHttpClient);
        Reg(RequestId);
        Reg(ServiceId);
        Reg(RoutingDto);
        Reg("System.Collections.Concurrent");
        Reg("System.Runtime.CompilerServices");
        Reg("System.Threading.Channels");
        Reg("Microsoft.Extensions.Logging");
        foreach (var method in Interface.Methods)
        {
            RegRecursive(method.ResponseType);
            foreach (var arg in method.Arguments)
            {
                Reg(arg.ParameterType);
            }
        }
        var generatedFunctions = string.Empty;
        var generatedFunctionNames = new HashSet<string>();

        Code = $@"
// <auto-generated />
#nullable enable
namespace {Namespace};

public sealed class {Name}(
    {WssClientConnection} ___clientConnection,
    {IClientLoggerFactory} ___loggerFactory,
    {IClientAuthenticatedHttpClient} ___httpClient)
    : {Interface}
    , IDisposable
{{
    readonly CancellationTokenSource ___Cts = new();
    readonly ILogger ___Logger = ___loggerFactory.CreateLogger<{Name}>();
    readonly {ServiceId} ___ServiceId = new(""{Interface}"");
    {string.Join("\r\n", Interface.Methods.Select(method => GetMethod(method, ref generatedFunctions, generatedFunctionNames)))}
    {generatedFunctions}
    {GenerateDispose()}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }

    private string GetMethod(InterfaceMethod method, ref string functions, HashSet<string> functionNames)
    {
        var code = "";

        if (method.ResponseType.IsTask)
            code += GenerateMethodForTask(method, ref functions, functionNames) ;
        if (method.ResponseType.IsTaskT)
            code += GenerateMethodForTaskT(method, ref functions, functionNames) ;
        if (method.ResponseType.IsIAsyncEnumerable)
            code += GenerateMethodForIAsyncEnumerable(method, ref functions, functionNames);

        code += GenerateMethodSerializer(method);

        return code;
    }

    private string GenerateMethodForTask(InterfaceMethod method, ref string functions, HashSet<string> functionNames)
    {
        var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
        return $@"
    public async Task {method}({string.Join(", ", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"{arg.ParameterType} {arg}" : $@"{arg.ParameterType} {arg} = default"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""{method}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg}"))});
        {(ct == null
        ? $@"
        var ___activityCts = ___Cts;"
        : $@"
        using var ___activityCts = CancellationTokenSource.CreateLinkedTokenSource(___Cts.Token, {ct});")}

        var ___routing = new {RoutingDto}(
            {RequestId}.New(),
            ___ServiceId,
            new(""{method}""),
            ___httpClient.UserId,
            ___httpClient.SessionId
        );
        {string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? $@"
        ___clientConnection.RegisterAsyncEnumerableArgument(___routing, {index}, {arg}, ___{method}_{index}_Serializer, ___activityCts.Token);" : ""))}
        await ___clientConnection.TryConnectAsync(___Cts.Token);
        {(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? $@"
        try" : "")}
        {{
            await ___clientConnection.Send_SendRequest_ToServerAsync(
                ___routing,
                ___{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"{arg}"))}),
                ___activityCts.Token);
        }}{(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? $@"
        finally
        {{
            ___clientConnection.UnRegisterAsyncEnumerableArguments(___routing);
        }}" : "")}
    }}";
    }
    private string GenerateMethodForTaskT(InterfaceMethod method, ref string functions, HashSet<string> functionNames)
    {
        var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
        var responseInnerType = method.ResponseType.UnderlayingTypes.Single();
        return $@"
    public async Task<{responseInnerType}{(responseInnerType.IsNullable ? "?" : "")}> {method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"{arg.ParameterType} {arg}" : $@"{arg.ParameterType} {arg} = default"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""{method}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg}"))});
        {(ct == null
        ? $@"
        var ___activityCts = ___Cts;"
        : $@"
        using var ___activityCts = CancellationTokenSource.CreateLinkedTokenSource(___Cts.Token, {ct});")}

        var ___routing = new {RoutingDto}(
            {RequestId}.New(),
            ___ServiceId,
            new(""{method}""),
            ___httpClient.UserId,
            ___httpClient.SessionId
        );
        {string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? $@"
        ___clientConnection.RegisterAsyncEnumerableArgument(___routing, {index}, {arg}, ___{method}_{index}_Serializer, ___activityCts.Token);" : ""))}
        
        await ___clientConnection.TryConnectAsync(___Cts.Token);

        {responseInnerType}{(responseInnerType.IsNullable ? "?" : "")} ___result = default!;
        {(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? $@"
        try" : "")}
        {{
            var ___responses = ___clientConnection.Send_InvokeRequest_ToServerAsync(
                ___routing,
                ___{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"{arg}"))}),
                ___activityCts.Token);

            await foreach (var item in ___responses)
            {{
                var ___offset = 0;
                var ___span = new Span<byte>(item);
                ___result = {PropertyHelper.GenerateSpanReadCode(responseInnerType.Type, false, ref functions, functionNames)};
            }}
        }}{(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? $@"
        finally
        {{
            ___clientConnection.UnRegisterAsyncEnumerableArguments(___routing);
        }}" : "")}

        return ___result;
    }}";
    }
    private string GenerateMethodForIAsyncEnumerable(InterfaceMethod method, ref string functions, HashSet<string> functionNames)
    {
        var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
        var responseInnerType = method.ResponseType.UnderlayingTypes.Single();
        return $@"
    public async IAsyncEnumerable<{responseInnerType}{(responseInnerType.IsNullable ? "?" : "")}> {method}({string.Join(", ", method.Arguments.Select(arg => !arg.ParameterType.IsCancellationToken ? $@"{arg.ParameterType} {arg}" : $@"[EnumeratorCancellation] {arg.ParameterType} {arg} = default"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""{method}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg}"))});

        var ___requestId = {RequestId}.New();
        var ___routing = new {RoutingDto}(
            ___requestId,
            ___ServiceId,
            new(""{method}""),
            ___httpClient.UserId,
            ___httpClient.SessionId
        );
        {(ct == null ? $@"
        var ___activityCts = ___Cts;" : $@"
        using var ___activityCts = CancellationTokenSource.CreateLinkedTokenSource(___Cts.Token, {ct});")}

        await ___clientConnection.TryConnectAsync(___Cts.Token);
        {string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? $@"
        ___clientConnection.RegisterAsyncEnumerableArgument(___routing, {index}, {arg}, ___{method}_{index}_Serializer, ___activityCts.Token);" : ""))}
        {(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? $@"
        try" : "")}
        {{
            var ___responses = ___clientConnection.Send_InvokeRequest_ToServerAsync(
                ___routing,
                ___{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"{arg}"))}),
                ___activityCts.Token);

            await foreach (var item in ___responses)
            {{
                var ___offset = 0;
                var ___span = new Span<byte>(item);
                yield return {PropertyHelper.GenerateSpanReadCode(responseInnerType.Type, false, ref functions, functionNames)};
            }}
        }}{(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? $@"
        finally
        {{
            ___clientConnection.UnRegisterAsyncEnumerableArguments(___routing);
        }}" : "")}
    }}";
    }

    private string GenerateMethodSerializer(InterfaceMethod method)
    {
        return $@"
    private byte[] ___{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"{arg.ParameterType} {arg}"))})
    {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false) ? $@"
        var ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => PropertyHelper.GenerateLengthCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        var ___length = ___offset;
        ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => PropertyHelper.GenerateSpanWriteCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        if (___length != ___offset)
            throw new Exception($""Binary length doesn't match: {{___length}} != {{___offset}}"");
        return ___buffer;" : $@"
        return [];")}
    }}{string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? GenerateMethodArgumentSerializer(method, arg, index) : ""))}";
    }
    private string GenerateMethodArgumentSerializer(InterfaceMethod method, InterfaceMethodArgument arg, int index)
    {
        return $@"
    private byte[] ___{method}_{index}_Serializer({arg.ParameterType.UnderlayingTypes.Single()} value)
    {{
        var ___offset = 0;
        {PropertyHelper.GenerateLengthCode(arg.ParameterType.UnderlayingTypes.Single().Type, "value", "        ", false)}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        ___offset = 0;
        {PropertyHelper.GenerateSpanWriteCode(arg.ParameterType.UnderlayingTypes.Single().Type, "value", "        ", false)}
        return ___span.Slice(0, ___offset).ToArray();
    }}";
    }

    private string GenerateDispose()
    {
        return $@"
    public void Dispose()
    {{
        ___Cts.Cancel();
        ___Cts.Dispose();

        GC.SuppressFinalize(this);
    }}";
    }
}