using gAPI.AutoApi.Server.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApi.Server.Generators.Endpoints;

public class SseResponseController_Generator : BaseGenerator
{
    public SseResponseController_Generator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "SseResponseController";
        FileName = $"Controllers\\{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;

    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;
    public SharedReference ServerConnectionCollection => Context.SharedReferences.ServerConnectionCollection;

    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference SseServiceSubscription => Context.SharedReferences.SseServiceSubscription;
    public SharedReference StreamingCache => Context.SharedReferences.StreamingCache;
    public SharedReference BaseResponse => Context.SharedReferences.BaseResponse;

    public SharedReference InvokeRequestDoneClientDto => Context.SharedReferences.InvokeRequestDoneClientDto;
    public SharedReference StreamingRequestClientDto => Context.SharedReferences.StreamingRequestClientDto;
    public SharedReference StreamingResponseClientDto => Context.SharedReferences.StreamingResponseClientDto;

    public override void GenerateCode()
    {
        if (Context.ServiceContext.HubInterfaces.Any(a => a.Methods.Any(b => b.ResponseType.IsIAsyncEnumerable)) == false)
        {
            Code = "";
            return;
        }
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg("System.Text.Json");
        Reg(IServerAuthenticationService);
        Reg(FabricClient);
        Reg(ServiceSubscriptionCollection);
        Reg(ServerConnectionCollection);
        Reg(ServiceId);
        Reg(SseServiceSubscription);
        Reg(BaseResponse);
        Reg(InvokeRequestDoneClientDto);
        Reg(StreamingResponseClientDto);
        Reg(StreamingCache);
        // TODO AANSLUITEN
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

[ApiController]
[Route(""sseservicesubscription"")]
public class SseResponseController(
    {StreamingCache} StreamingCache,
    {IServerAuthenticationService} authenticationService,
    {FabricClient} fabricClient)
    : ControllerBase
{{
    [HttpPost(""invokerequestdone"")]
    public async Task<ActionResult<{BaseResponse}>> InvokeRequestDone([FromForm] {InvokeRequestDoneClientDto} message, CancellationToken ct, [FromHeader(Name = ""X-SessionId"")] string ___sessionId)
    {{
        if (message.StateIsChanged)
            await authenticationService.UpdateStateDataAsync(message.StateData, ct);

        await fabricClient.Send_FabricInvokeRequestDone_ToFabricAsync(message, ct);

        return Ok(new {BaseResponse}() {{ Success = true }});
    }}

    [HttpPost(""streamingRequest"")]
    public async Task<ActionResult<{BaseResponse}>> StreamingRequest([FromForm] {StreamingRequestClientDto} message, CancellationToken ct, [FromHeader(Name = ""X-SessionId"")] string ___sessionId)
    {{
        if (message.StateIsChanged)
            await authenticationService.UpdateStateDataAsync(message.StateData, ct);

        await fabricClient.Send_StreamingRequestClientToServer_ToFabricAsync(message, ct);

        return Ok(new {BaseResponse}() {{ Success = true }});
    }}

    [HttpPost(""streamingresponse"")]
    public async Task<ActionResult<{BaseResponse}>> StreamingResponse([FromForm] string messageJson, CancellationToken ct, [FromHeader(Name = ""X-SessionId"")] string ___sessionId)
    {{
        var message = JsonSerializer.Deserialize<{StreamingResponseClientDto}>(messageJson);
        if (message == null)
            return NotFound();

        if (message.StateIsChanged)
            await authenticationService.UpdateStateDataAsync(message.StateData, ct);

        await fabricClient.Send_StreamingResponseClientToServer_ToFabricAsync(message, ct);

        return Ok(new {BaseResponse}() {{ Success = true }});
    }}




    //[HttpPost(""streamingresponse"")]
    //public async Task<ActionResult<{BaseResponse}>> StreamingResponse([FromForm] string messageJson, CancellationToken ct, [FromHeader(Name = ""X-SessionId"")] string ___sessionId)
    //{{
    //    var message = JsonSerializer.Deserialize<{StreamingResponseClientDto}>(messageJson);
    //    if (message == null)
    //        return NotFound();

    //    if (message.StateIsChanged)
    //        await authenticationService.UpdateStateDataAsync(message.StateData, ct);

    //    // altijd een response op een argument iasyncenumerable
    //    if (StreamingCache.Timeouts.TryGetValue(message.Routing.RequestId, out var timeout))
    //        timeout.Reset();

    //    if (StreamingCache.StreamingResponseHandlers.TryGetValue(new(message.Routing.RequestId, message.ArgumentIndex, message.StreamId), out var responseHandler))
    //        responseHandler.Invoke(message);

    //    return Ok(new {BaseResponse}() {{ Success = true }});
    //}}
}}
";



    }
}