using gAPI.AutoApi.Server.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApi.Server.Generators.Endpoints;

public class SseResponseController_Generator : BaseGenerator
{
    public SseResponseController_Generator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "SseEndpointExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;
    public SharedReference ServerConnectionCollection => Context.SharedReferences.ServerConnectionCollection;

    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference SseServiceSubscription => Context.SharedReferences.SseServiceSubscription;
    public SharedReference StreamingCache => Context.SharedReferences.StreamingCache;

    public override void GenerateCode()
    {
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg(IServerAuthenticationService);
        Reg(FabricClient);
        Reg(ServiceSubscriptionCollection);
        Reg(ServerConnectionCollection);
        Reg(ServiceId);
        Reg(SseServiceSubscription);
        // TODO AANSLUITEN
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

[ApiController]
[Route(""sseservicesubscription"")]
public class SseResponseController(
    StreamingCache StreamingCache,
    IServerAuthenticationService authenticationService,
    FabricClient fabricClient)
    : ControllerBase
{{
    [HttpPost(""invokerequestdone"")]
    public async Task<ActionResult<BaseResponse>> InvokeRequestDone([FromForm] InvokeRequestDoneClientDto message, CancellationToken ct, [FromHeader(Name = ""X-SessionId"")] string ___sessionId)
    {{
        if (message.StateIsChanged)
            await authenticationService.UpdateStateDataAsync(message.StateData, ct);

        // Voor als er geen fabric is
        if (StreamingCache.PendingClientInvokeRequests.TryRemove(message.Routing.RequestId, out var completion))
            completion.TrySetResult(message);
        else
            await fabricClient.Send_FabricInvokeRequestDone_ToFabricAsync(message, ct);

        return Ok(new BaseResponse() {{ Success = true }});
    }}
    [HttpPost(""streamingresponse"")]
    public async Task<ActionResult<BaseResponse>> StreamingResponse([FromForm] StreamingResponseClientDto message, CancellationToken ct, [FromHeader(Name = ""X-SessionId"")] string ___sessionId)
    {{
        if (message.StateIsChanged)
            await authenticationService.UpdateStateDataAsync(message.StateData, ct);

        if (StreamingCache.Timeouts.TryGetValue(message.Routing.RequestId, out var timeout))
            timeout.Reset();

        if (StreamingCache.StreamingResponseHandlers.TryGetValue(new(message.Routing.RequestId, message.ArgumentIndex, message.StreamId), out var responseHandler))
            responseHandler.Invoke(message);
        return Ok(new BaseResponse() {{ Success = true }});
    }}
    [HttpPost(""fabricstreamingresponse"")]
    public async Task<ActionResult<BaseResponse>> FabricStreamingResponse([FromForm] string messageJson, CancellationToken ct, [FromHeader(Name = ""X-SessionId"")] string ___sessionId)
    {{
        var message = JsonSerializer.Deserialize<StreamingResponseClientDto>(messageJson);
        if (message == null)
            return NotFound();

        if (message.StateIsChanged)
            await authenticationService.UpdateStateDataAsync(message.StateData, ct);

        if (fabricClient.IsConnected)
        {{
            // Doorlussen naar fabric
            await fabricClient.Send_StreamingResponseClientToServer_ToFabricAsync(message, ct);
        }}
        else
        {{
            // Fallback maar eigenlijk niet helemaal netjes.
            if (StreamingCache.Timeouts.TryGetValue(message.Routing.RequestId, out var timeout))
                timeout.Reset();

            if (StreamingCache.StreamingResponseHandlers.TryGetValue(new(message.Routing.RequestId, message.ArgumentIndex, message.StreamId), out var responseHandler))
                responseHandler.Invoke(message);
        }}
        return Ok(new BaseResponse() {{ Success = true }});
    }}
}}




";



    }
}