using gAPI.AutoApi.Server.Models;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoApi.Server.Generators.Endpoints;

public class SseResponsController_Generator : BaseGenerator
{
    public SseResponsController_Generator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "SseEndpointExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;
    
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference ServiceSubscriptionCollection => Context.SharedReferences.ServiceSubscriptionCollection;
    public SharedReference ServerConnectionCollection => Context.SharedReferences.ServerConnectionCollection;

    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference SseServiceSubscription => Context.SharedReferences.SseServiceSubscription;
    public SharedReference StreamingCache => Context.SharedReferences.StreamingCache;

    public override void GenerateCode()
    {
        Reg("Microsoft.AspNetCore.Mvc");
        Reg("Microsoft.AspNetCore.HttpOverrides");
        Reg("Microsoft.AspNetCore.Builder");
        Reg("Microsoft.AspNetCore.Http");
        Reg(IServerAuthenticationService);
        Reg(FabricClient);
        Reg(ServiceSubscriptionCollection);
        Reg(ServerConnectionCollection);
        Reg(ServiceId);
        Reg(SseServiceSubscription);
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static WebApplication MapSseEndpoint(this WebApplication app)
    {{
        app.MapGet(""/SseServiceSubscription/invokeDone/{{serviceId}}"", async (
            string serviceId,
            [FromHeader(Name = ""X-SessionId"")] string sessionId,
            [FromServices] {IServerAuthenticationService} authenticationService,
            [FromServices] {ServerConnectionCollection} serverConnectionCollection,
            [FromServices] {ServiceSubscriptionCollection} ServiceSubscriptionCollection,
            [FromServices] {StreamingCache} streamingCache,
            [FromServices] {FabricClient} fabricClient,
            CancellationToken ct
        ) =>
        {{
        }});
        app.MapGet(""/SseServiceSubscription/streamingResponse/{{serviceId}}"", async (
            string serviceId,
            [FromHeader(Name = ""X-SessionId"")] string sessionId,
            [FromServices] {IServerAuthenticationService} authenticationService,
            [FromServices] {ServerConnectionCollection} serverConnectionCollection,
            [FromServices] {ServiceSubscriptionCollection} ServiceSubscriptionCollection,
            [FromServices] {StreamingCache} streamingCache,
            [FromServices] {FabricClient} fabricClient,
            CancellationToken ct
        ) =>
        {{
        }});

        return app;
    }}
}}

";



    }
}