using gAPI.AutoSerializer;
using gAPI.AutoWss.Server.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Hubs;

public class ClientService_Generator : _BaseGenerator
{
    public ClientService_Generator(Generator context, Interface @interface)
    {
        Context = context;
        Interface = @interface;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = Interface.CleanName;
        FileName = $"Hubs/{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }
    public Interface Interface { get; }
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;

    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference ServiceMethodId => Context.SharedReferences.ServiceMethodId;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg("System.Runtime.CompilerServices");
        Reg(Interface);
        Reg(FabricClient);
        Reg(SessionId);
        Reg(UserId);
        Reg(ServiceId);
        Reg(ServiceMethodId);
        Reg("gAPI.Core.Ids");

        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    if (!arg.ParameterType.IsIAsyncEnumerable)
                        RegRecursive(arg.ParameterType);
                }
            }
        }

        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    if (!arg.ParameterType.IsIAsyncEnumerable)
                        RegRecursive(arg.ParameterType);
                }
            }
        }
        var functions = string.Empty;
        var functionNames = new HashSet<string>();
        string argumentSerializers = GenerateArgumentSerializers();
        var methodsCode =
            string.Join("", Interface.Methods.Where(a => a.ResponseType.IsTask).Select(method => GenerateTask(method))) +
            string.Join("", Interface.Methods.Where(a => a.ResponseType.IsTask == false).Select(method => GenerateNotTask(method, ref functions, functionNames))) +
            string.Join("", Interface.Methods.Select(method => GenerateSerializer(method))) +
            GenerateDispose();

        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {FabricClient} ___fabricClient,
    ILoggerFactory ___loggerFactory,
    {SessionId}? ___sessionId,
    {UserId}? ___userId)
    : {Interface}
    , IDisposable
{{
    readonly CancellationTokenSource ___cts = new();
    readonly ILogger ___Logger = ___loggerFactory.CreateLogger<{Name}>();
    readonly {ServiceId} ___serviceId = new(""{Interface.Name}"");
{methodsCode}
{functions}
{argumentSerializers}
}}";
    }

    private string GenerateTask(InterfaceMethod method)
    {
        var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
        return $@"
    public async Task {method.Name}({string.Join(",", method.Arguments.Select(arg => $@"
        {arg.ParameterType.Name} {arg.Name}"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""{method.Name}({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg.Name}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg.Name}"))});

        var ___serviceMethodId = new {ServiceMethodId}(""{method.Name}"");
        var ___requestId = RequestId.New();
        var ___payload = {Interface}_{method}_Serializer({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"
            {arg}"))});

{string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? $@"
        ___fabricClient.RegisterAsyncEnumerableArgument(___requestId, {index}, {arg}, {Interface}_{method}_{index}_Serializer, {(ct == null ? "___cts.Token" : ct.Name)});" : ""))}
        
        await ___fabricClient.{(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? "SendAsync" : "SendAsync")}(
            ___requestId,
            ___serviceId, 
            ___serviceMethodId, 
            ___userId,
            ___sessionId,
            ___payload, 
            {(ct == null ? "___cts.Token" : ct.Name)});
    }}";
    }
    private string GenerateNotTask(InterfaceMethod method, ref string functions, HashSet<string> functionNames)
    {
        var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
        var responseInnerType = method.ResponseType.UnderlayingTypes.Single();
        return $@"
    public async {method.ResponseType} {method.Name}({string.Join(",", method.Arguments.Select(arg => $@"
        {(arg.ParameterType.IsCancellationToken ? "[EnumeratorCancellation] " : "")}{arg.ParameterType.Name} {arg.Name}"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""{method.Name}({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg.Name}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg.Name}"))});

        var ___requestId = RequestId.New();
        var ___serviceMethodId = new {ServiceMethodId}(""{method.Name}"");
        var ___payload = {Interface}_{method}_Serializer({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"
            {arg}"))});
{string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? $@"
        ___fabricClient.RegisterAsyncEnumerableArgument(___requestId, {index}, {arg}, {Interface}_{method}_{index}_Serializer, {(ct == null ? "___cts.Token" : ct.Name)});" : ""))}

        var responses = ___fabricClient.InvokeAsync(
            ___requestId,
            ___serviceId, 
            ___serviceMethodId, 
            ___userId, 
            ___sessionId, 
            ___payload, 
            {(ct == null ? "___cts.Token" : ct.Name)});
        await foreach (var response in responses)
        {{
            if (ct.IsCancellationRequested)
                yield break;

            var ___offset = 0;
            var ___span = new Span<byte>(response.BinaryData);
            yield return {PropertyHelper.GenerateSpanReadCode(responseInnerType.Type, false, ref functions, functionNames)};
        }}
    }}";
    }
    private string GenerateSerializer(InterfaceMethod method)
    {
        return $@"
    public byte[] {Interface}_{method}_Serializer({string.Join(",", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"
        {arg.ParameterType} {arg}"))})
    {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false) ? $@"
        var ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => PropertyHelper.GenerateLengthCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        var ___length = ___offset;
        ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => PropertyHelper.GenerateSpanWriteCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        if (___length != ___offset)
            throw new Exception($""Binary length doesn't match: {{___length}} != {{___offset}}"");
        return ___buffer;" : $@"
        return [];")}
    }}";
    }
    private string GenerateArgumentSerializers()
    {
        var argumentSerializers = string.Empty;
        foreach (var method in Interface.Methods)
        {
            foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
            {
                if (!arg.ParameterType.IsIAsyncEnumerable)
                    continue;

                var innerType = arg.ParameterType.UnderlayingTypes.Single();
                argumentSerializers += $@"

    public byte[] {Interface}_{method}_{index}_Serializer({innerType} value)
    {{
        var ___offset = 0;
        {PropertyHelper.GenerateLengthCode(innerType.Type, "value", "        ", false)}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        ___offset = 0;
        {PropertyHelper.GenerateSpanWriteCode(innerType.Type, "value", "        ", false)}
        return ___span.Slice(0, ___offset).ToArray();
    }}";
            }
        }

        return argumentSerializers;
    }

    private string GenerateDispose()
    {
        return $@"

    public void Dispose()
    {{
        ___cts.Cancel();
        ___cts.Dispose();
    }}";
    }
}