using gAPI.AutoSerializer;
using gAPI.AutoWss.Server.Models;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWss.Server.Generators.Hubs;

public class HubClient_Generator : _BaseGenerator
{
    public HubClient_Generator(Generator context, Interface @interface)
    {
        Context = context;
        Interface = @interface;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = Interface.CleanName;
        FileName = $"Hubs/{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }
    public Interface Interface { get; }
    public SharedReference FabricClient => Context.SharedReferences.FabricClient;
    public SharedReference SessionId => Context.SharedReferences.SessionId;
    public SharedReference UserId => Context.SharedReferences.UserId;
    public SharedReference RequestId => Context.SharedReferences.RequestId;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference ServiceMethodId => Context.SharedReferences.ServiceMethodId;
    public SharedReference RoutingDto => Context.SharedReferences.RoutingDto;
    public SharedReference IServerAuthenticationService => Context.SharedReferences.IServerAuthenticationService;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg("System.Runtime.CompilerServices");
        Reg(Interface);
        Reg(FabricClient);
        Reg(SessionId);
        Reg(UserId);
        Reg(ServiceId);
        Reg(ServiceMethodId);
        Reg(IServerAuthenticationService);
        Reg("gAPI.Core.Ids");

        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    if (!arg.ParameterType.IsIAsyncEnumerable)
                        RegRecursive(arg.ParameterType);
                }
            }
        }

        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    if (!arg.ParameterType.IsIAsyncEnumerable)
                        RegRecursive(arg.ParameterType);
                }
            }
        }
        var functions = string.Empty;
        var functionNames = new HashSet<string>();

        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {IServerAuthenticationService} ___authenticationService,
    {FabricClient} ___fabricClient,
    ILoggerFactory ___loggerFactory,
    {SessionId}? ___sessionId,
    {UserId}? ___userId)
    : {Interface}
    , IDisposable
{{
    readonly CancellationTokenSource ___Cts = new();
    readonly ILogger ___Logger = ___loggerFactory.CreateLogger<{Name}>();
    readonly {ServiceId} ___ServiceId = new(""{Interface.Name}"");
{string.Join("\r\n", Interface.Methods.Select(method => GenerateMethod(method, ref functions, functionNames)))}
{functions}
{GenerateDispose()}
}}";
    }

    private string GenerateMethod(InterfaceMethod method, ref string functions2, HashSet<string> functionNames)
    {
        var functions = "";
        var code = "";

        if (method.ResponseType.IsTask)
            code += GenerateTask(method);
        if (method.ResponseType.IsIAsyncEnumerable)
            code += GenerateIAsyncEnumerable(method, ref functions, functionNames);
        code += GenerateSerializer(method);
        code += GenerateArgumentSerializers(method);

        functions2 = functions;

        return code;
    }

    private string GenerateTask(InterfaceMethod method)
    {
        var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
        return $@"
    public async Task {method.Name}({string.Join(", ", method.Arguments.Select(arg => $@"{arg.ParameterType.Name} {arg.Name}"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""{method.Name}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg.Name}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg.Name}"))});

        var ___requestId = {RequestId}.New();
        var ___routing = new {RoutingDto}(
            ___requestId,
            ___ServiceId,
            new(""{method}""),
            ___userId,
            ___sessionId
        );
        var ___payload = ___{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"
            {arg}"))});

{string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? $@"
        ___fabricClient.RegisterAsyncEnumerableArgument(___authenticationService, ___routing, {index}, {arg}, ___{method}_{index}_Serializer, {(ct == null ? "___Cts.Token" : ct.Name)});" : ""))}
        
        await ___fabricClient.{(method.Arguments.Any(a => a.ParameterType.IsIAsyncEnumerable) ? "SendAsync" : "SendAsync")}(
            ___authenticationService,
            ___routing,
            ___payload, 
            {(ct == null ? "___Cts.Token" : ct.Name)});
    }}";
    }
    private string GenerateIAsyncEnumerable(InterfaceMethod method, ref string functions, HashSet<string> functionNames)
    {
        var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
        var responseInnerType = method.ResponseType.UnderlayingTypes.Single();
        return $@"
    public async {method.ResponseType} {method.Name}({string.Join(", ", method.Arguments.Select(arg => $@"{(arg.ParameterType.IsCancellationToken ? "[EnumeratorCancellation] " : "")}{arg.ParameterType.Name} {arg.Name}"))})
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(""{method.Name}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg.Name}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg.Name}"))});

        var ___routing = new {RoutingDto}(
            {RequestId}.New(),
            ___ServiceId,
            new(""{method}""),
            ___userId,
            ___sessionId
        );
        var ___payload = ___{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"
            {arg}"))});
{string.Join("", method.Arguments.Select((arg, index) => arg.ParameterType.IsIAsyncEnumerable ? $@"
        ___fabricClient.RegisterAsyncEnumerableArgument(___authenticationService, ___routing, {index}, {arg}, ___{method}_{index}_Serializer, {(ct == null ? "___Cts.Token" : ct.Name)});" : ""))}

        var responses = ___fabricClient.InvokeAsync(
            ___authenticationService,
            ___routing, 
            ___payload, 
            {(ct == null ? "___Cts.Token" : ct.Name)});
        await foreach (var response in responses)
        {{
            if (response.StateIsChanged)
                await ___authenticationService.UpdateStateDataAsync(
                    response.StateData, 
                    {(ct == null ? "___Cts.Token" : ct.Name)});

            if (ct.IsCancellationRequested)
                yield break;

            var ___offset = 0;
            var ___span = new Span<byte>(response.BinaryData);
            yield return {PropertyHelper.GenerateSpanReadCode(responseInnerType.Type, false, ref functions, functionNames)};
        }}
    }}";
    }
    private string GenerateSerializer(InterfaceMethod method)
    {
        return $@"
    private byte[] ___{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => $@"{arg.ParameterType} {arg}"))})
    {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false) ? $@"
        var ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => PropertyHelper.GenerateLengthCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        var ___length = ___offset;
        ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false && a.ParameterType.IsIAsyncEnumerable == false).Select(arg => PropertyHelper.GenerateSpanWriteCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        if (___length != ___offset)
            throw new Exception($""Binary length doesn't match: {{___length}} != {{___offset}}"");
        return ___buffer;" : $@"
        return [];")}
    }}";
    }
    private string GenerateArgumentSerializers(InterfaceMethod method)
    {
        var argumentSerializers = string.Empty;
        foreach (var (arg, index) in method.Arguments.Select((arg, index) => (arg, index)))
        {
            if (!arg.ParameterType.IsIAsyncEnumerable)
                continue;

            var innerType = arg.ParameterType.UnderlayingTypes.Single();
            argumentSerializers += $@"
    private byte[] ___{method}_{index}_Serializer({innerType} value)
    {{
        var ___offset = 0;
        {PropertyHelper.GenerateLengthCode(innerType.Type, "value", "        ", false)}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        ___offset = 0;
        {PropertyHelper.GenerateSpanWriteCode(innerType.Type, "value", "        ", false)}
        return ___span.Slice(0, ___offset).ToArray();
    }}";
        }
        return argumentSerializers;
    }

    private string GenerateDispose()
    {
        return $@"
    public void Dispose()
    {{
        ___Cts.Cancel();
        ___Cts.Dispose();
    }}";
    }
}