namespace gAPI.AutoWssClient.Generators;

public class FormFileGenerator : BaseGenerator
{
    public FormFileGenerator(Generator context)
    {
        Context = context;

        if (context.SharedReferences.AuthClient_FormFile != null)
        {
            Namespace = context.SharedReferences.AuthClient_FormFile.Namespace;
            Name = context.SharedReferences.AuthClient_FormFile.Name;
        }
        else
        {
            Namespace = "gAPI.Generated";
            Name = "FormFile";
        }

        Directory = "";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }

    public override void GenerateCode()
    {
        if (Context.SharedReferences.AuthClient_FormFile != null)
            return;

        Code = $@"using gAPI.Attributes;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Http;

// <auto-generated />
#nullable enable
namespace {Namespace};

[IsFormFile]
public class FormFile : IFormFile
{{
    public FormFile(IBrowserFile browserFile, byte[] content)
    {{
        Name = browserFile.Name;
        FileName = browserFile.Name;
        ContentType = browserFile.ContentType;
        Length = browserFile.Size;
        ContentDisposition = $""form-data; name=\""{{Name}}\""; filename=\""{{FileName}}\"""";
        ___Buffer = content;
    }}

    public IHeaderDictionary Headers => new HeaderDictionary();

    public string Name {{ get; }}
    public string FileName {{ get; }}
    public string ContentType {{ get; }}
    public long Length {{ get; }}
    public string ContentDisposition {{ get; }}
    public byte[] ___Buffer {{ get; }}

    public Stream OpenReadStream()
    {{
        return new MemoryStream(___Buffer);
    }}

    public void CopyTo(Stream target)
    {{
        target.Write(___Buffer, 0, ___Buffer.Length);
    }}

    public async Task CopyToAsync(Stream target, CancellationToken cancellationToken = default)
    {{
        await target.WriteAsync(___Buffer, 0, ___Buffer.Length);
    }}
}}";
    }
}
