using gAPI.AutoWss.Client.Models;
using System.Linq;

namespace gAPI.AutoWss.Client.Generators;

public class AddAutoWssClientExtensionGenerator : _BaseGenerator
{
    public AddAutoWssClientExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AddAutoWssClientExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference ClientConnection => Context.ClientConnection;
    public SharedReference IClientConnection => Context.IClientConnection;
    public SharedReference IWssLoggerFactory => Context.SharedReferences.IWssLoggerFactory;
    public SharedReference IWssClientConnection => Context.SharedReferences.IWssClientConnection;
    public SharedReference FrontendConfig => Context.SharedReferences.FrontendConfig;

    public SharedReference IUriNavigationManager => Context.SharedReferences.IUriNavigationManager;
    public SharedReference DefaultNavigationManager => Context.SharedReferences.DefaultNavigationManager;
    public SharedReference StaticNavigationManager => Context.SharedReferences.StaticNavigationManager;

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg("Microsoft.Extensions.DependencyInjection.Extensions");
        Reg("Microsoft.AspNetCore.Components");
        Reg("gAPI.Core.Client.Interfaces");
        Reg("gAPI.Core.Client");
        Reg(ClientConnection);
        Reg(IClientConnection);
        Reg(IWssLoggerFactory);
        Reg(IWssClientConnection);
        Reg(FrontendConfig);
        Reg(IUriNavigationManager);
        Reg(DefaultNavigationManager);
        Reg(StaticNavigationManager);
        foreach (var api in Context.Apis)
        {
            Reg(api);
            Reg(api.Interface);
        }
        foreach (var api in Context.MinimalApis)
        {
            Reg(api);
            Reg(api.Interface);
        }
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoWssClient(this IServiceCollection services, string apiAddress, string wssAddress)
    {{
        // Set up authorization core
        services.AddAuthorizationCore();

        // Set up configuration
        var config = new {FrontendConfig}()
        {{
            ApiBackendUrl = apiAddress,
            WssBackendUrl = wssAddress
        }};
        services.AddSingleton(config);

        // Connection stuff
        //services.TryAddScoped<IClientAuthenticatedHttpClient, EmptyClientAuthenticatedHttpClient>();
        //services.AddAuthenticationServices(apiAddress);
        services.AddScoped<{ClientConnection}>();
        services.AddScoped<{IClientConnection}>(sp => sp.GetRequiredService<{ClientConnection}>());
        services.AddScoped<{IWssLoggerFactory}>(sp => sp.GetRequiredService<{ClientConnection}>());

        services.AddScoped<{IUriNavigationManager}>(sp =>
        {{
            var navigationManager = sp.GetService<NavigationManager>();
            if (navigationManager != null )
            {{
                return new {DefaultNavigationManager}(navigationManager);
            }}
            else
            {{
                return new {StaticNavigationManager}();
            }}
        }});

        // Api clients{string.Join("", Context.Apis.Select(api => $@"
        services.AddScoped<{api.Interface}>(sp => sp.GetRequiredService<{ClientConnection}>().{api});"))}
        
        // Minimal api clients{string.Join("", Context.MinimalApis.Select(api => $@"
        services.AddScoped<{api.Interface}, {api}>();"))}

        return services;
    }}
}}";
    }
}