using gAPI.AutoSerializer;
using gAPI.AutoWssClient.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWssClient.Generators;

public class ApiClientGenerator : BaseGenerator
{
    public ApiClientGenerator(Generator context, Interface @interface)
    {
        Context = context;
        Interface = @interface;

        Directory = "";
        Namespace = @interface.Namespace;

        Name = @interface.CleanName;
        FileName = $"{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }
    public Interface Interface { get; }
    public SharedReference WssClientConnection => Context.SharedReferences.WssClientConnection;
    public SharedReference IWssLoggerFactory => Context.SharedReferences.IWssLoggerFactory;
    public SharedReference IClientAuthenticatedHttpClient => Context.SharedReferences.IClientAuthenticatedHttpClient;
    public SharedReference RequestId => Context.SharedReferences.RequestId;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference ApiInvokeResponseDto => Context.SharedReferences.ApiInvokeResponseDto;
    public SharedReference ApiSendRequestDto => Context.SharedReferences.ApiSendRequestDto;
    public SharedReference ApiInvokeRequestDto => Context.SharedReferences.ApiInvokeRequestDto;
    public SharedReference ApiInvokeResponseDoneDto => Context.SharedReferences.ApiInvokeResponseDoneDto;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg(Interface);
        Reg(WssClientConnection);
        Reg(IWssLoggerFactory);
        Reg(IClientAuthenticatedHttpClient);
        Reg(RequestId);
        Reg(ServiceId);
        Reg(ApiInvokeResponseDto);
        Reg(ApiSendRequestDto);
        Reg(ApiInvokeRequestDto);
        Reg(ApiInvokeResponseDoneDto);
        Reg("System.Collections.Concurrent");
        Reg("System.Runtime.CompilerServices");
        Reg("System.Threading.Channels");
        Reg("Microsoft.Extensions.Logging");
        foreach (var method in Interface.Methods)
        {
            RegRecursive(method.ResponseType);
            foreach (var arg in method.Arguments)
            {
                Reg(arg.ParameterType);
            }
        }
        var functions = string.Empty;
        Code = $@"
// <auto-generated />
#nullable enable
namespace {Namespace};

public sealed class {Name}(
    {WssClientConnection} ___clientConnection,
    {IWssLoggerFactory} ___loggerFactory,
    {IClientAuthenticatedHttpClient} ___httpClient)
    : {Interface}
    , IDisposable
{{
    readonly CancellationTokenSource ___Cts = new();
    readonly ILogger ___Logger = ___loggerFactory.CreateLogger<{Name}>();
    readonly ConcurrentDictionary<{RequestId}, Channel<{ApiInvokeResponseDto}>> ___PendingRequests = new();
    readonly {ServiceId} ___ServiceId = new(""{Interface}"");
{string.Join("", Interface.Methods.Where(method => method.ResponseType.IsTask).Select(method =>
{
    var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
    return $@"
    public async Task {method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
        {arg.ParameterType} {arg}" : $@"
        {arg.ParameterType} {arg} = default"))})
    {{
        if (___clientConnection.Initialized == false)
            throw new Exception(""Not initialized, please wait or contact tech support if you already waited."");

        if (___Logger.IsEnabled(LogLevel.Trace))
        {{
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {method}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg}"))});
        }}
{(ct == null ? $@"
        var ___activityCts = ___Cts;" : $@"
        using var ___activityCts = CancellationTokenSource.CreateLinkedTokenSource(___Cts.Token, {ct});")}

        await ___clientConnection.TryConnectAsync(___activityCts.Token);

        await ___clientConnection.Send_SendRequest_ToServerAsync(new {ApiSendRequestDto}()
        {{
            ServiceId = ___ServiceId,
            MethodId = new(""{method}""),
            SessionId = ___httpClient.SessionId,
            StateData = ___httpClient.IsStateChanged() ? await ___httpClient.GetStateDataAsync(false, ___activityCts.Token) : null,
            BinaryData = {Interface}_{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg}"))})
        }}, ___activityCts.Token);
    }}";
}))}
{string.Join("", Interface.Methods.Where(method => method.ResponseType.IsTaskT).Select(method =>
{
    var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
    var responseInnerType = method.ResponseType.UnderlayingTypes.Single();
    return $@"
    public async Task<{responseInnerType}{(responseInnerType.IsNullable ? "?" : "")}> {method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
        {arg.ParameterType} {arg}" : $@"
        {arg.ParameterType} {arg} = default"))})
    {{
        if (___clientConnection.Initialized == false)
            throw new Exception(""Not initialized, please wait or contact tech support if you already waited."");

        if (___Logger.IsEnabled(LogLevel.Trace))
        {{
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {method}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg}"))});
        }}

        var ___requestId = {RequestId}.New();

        var ___channel = Channel.CreateUnbounded<{ApiInvokeResponseDto}>();
        ___PendingRequests[___requestId] = ___channel;
{(ct == null ? $@"
        var ___activityCts = ___Cts;" : $@"
        using var ___activityCts = CancellationTokenSource.CreateLinkedTokenSource(___Cts.Token, {ct});")}
        var ___timeout = TimeSpan.FromSeconds(10);
        var ___activity = new SemaphoreSlim(0, 1);

        _ = Task.Run(async () =>
        {{
            try
            {{
                while (!___activityCts.IsCancellationRequested)
                {{
                    // wacht op activiteit of ___timeout
                    if (!await ___activity.WaitAsync(___timeout))
                        throw new TimeoutException(""Client did not ACK"");

                    // activiteit gezien → reset timer
                }}
            }}
            catch (Exception ex)
            {{
                ___Logger.LogError(""{method} => Exception: {{ex}}"", ex);
                // Als hij stopt en de taak is al klaar zal hij hem niet vinden
                if (___PendingRequests.TryRemove(___requestId, out var pending))
                    pending.Writer.TryComplete(ex);
            }}
        }}, ___activityCts.Token);

        await ___clientConnection.TryConnectAsync(___activityCts.Token);
        await ___clientConnection.Send_InvokeRequest_ToServerAsync(new {ApiInvokeRequestDto}()
        {{
            RequestId = ___requestId,
            ServiceId = ___ServiceId,
            MethodId = new(""{method}""),
            SessionId = ___httpClient.SessionId,
            StateData = ___httpClient.IsStateChanged() ? await ___httpClient.GetStateDataAsync(false, ___activityCts.Token) : null,
            BinaryData = {Interface}_{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg}"))})
        }}, ___activityCts.Token);

        {responseInnerType}{(responseInnerType.IsNullable ? "?" : "")} ___result = default!;
        await foreach (var item in ___channel.Reader.ReadAllAsync())
        {{
            var ___offset = 0;
            var ___span = new Span<byte>(item.BinaryData);
            ___result = {PropertyHelper.GenerateSpanReadCode(responseInnerType.Type, false, ref functions)};
            ___activity.Release();
        }}

        ___activityCts.Cancel();
        ___activity.Release();

        if (___PendingRequests.TryRemove(___requestId, out var pending))
            pending.Writer.TryComplete();

        return ___result;
    }}";
}))}
{string.Join("", Interface.Methods.Where(method => method.ResponseType.IsIAsyncEnumerable).Select(method =>
{
    var ct = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);
    var responseInnerType = method.ResponseType.UnderlayingTypes.Single();
    return $@"
    public async IAsyncEnumerable<{responseInnerType}{(responseInnerType.IsNullable ? "?" : "")}> {method}({string.Join(",", method.Arguments.Select(arg => !arg.ParameterType.IsCancellationToken ? $@"
        {arg.ParameterType} {arg}" : $@"
        [EnumeratorCancellation] {arg.ParameterType} {arg} = default"))})
    {{
        if (___clientConnection.Initialized == false)
            throw new Exception(""Not initialized, please wait or contact tech support if you already waited."");

        if (___Logger.IsEnabled(LogLevel.Trace))
        {{
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" {method}({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{{{arg}}}"))})""{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@", {arg}"))});
        }}

        var ___requestId = {RequestId}.New();

        var ___channel = Channel.CreateUnbounded<{ApiInvokeResponseDto}>();
        ___PendingRequests[___requestId] = ___channel;
{(ct == null ? $@"
        var ___activityCts = ___Cts;" : $@"
        using var ___activityCts = CancellationTokenSource.CreateLinkedTokenSource(___Cts.Token, {ct});")}
        var ___timeout = TimeSpan.FromSeconds(10);
        var ___activity = new SemaphoreSlim(0, 1);

        _ = Task.Run(async () =>
        {{
            try
            {{
                while (!___activityCts.IsCancellationRequested)
                {{
                    // wacht op activiteit of ___timeout
                    if (!await ___activity.WaitAsync(___timeout, ___activityCts.Token))
                        throw new TimeoutException(""Client did not ACK"");

                    // activiteit gezien → reset timer
                }}
            }}
            catch (Exception ex)
            {{
                ___Logger.LogError(""{method} => Exception: {{ex}}"", ex);

                // Als hij stopt en de taak is al klaar zal hij hem niet vinden
                if (___PendingRequests.TryRemove(___requestId, out var pending))
                    pending.Writer.TryComplete(ex);
            }}
        }}, ___activityCts.Token);

        await ___clientConnection.TryConnectAsync(___activityCts.Token);
        await ___clientConnection.Send_InvokeRequest_ToServerAsync(new {ApiInvokeRequestDto}()
        {{
            RequestId = ___requestId,
            ServiceId = ___ServiceId,
            MethodId = new(""{method}""),
            SessionId = ___httpClient.SessionId,
            StateData = ___httpClient.IsStateChanged() ? await ___httpClient.GetStateDataAsync(false, ___activityCts.Token) : null,
            BinaryData = {Interface}_{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"{arg}"))})
        }}, ___activityCts.Token);

        try
        {{
            await foreach (var item in ___channel.Reader.ReadAllAsync())
            {{
                var ___offset = 0;
                var ___span = new Span<byte>(item.BinaryData);
                yield return {PropertyHelper.GenerateSpanReadCode(responseInnerType.Type, false, ref functions)};
            }}
        }}
        finally
        {{
            ___activityCts.Cancel();
            ___activity.Release();

            if (___PendingRequests.TryRemove(___requestId, out var pending))
                pending.Writer.TryComplete();
        }}
    }}";
}))}

    public async Task ReceiveResponseAsync({ApiInvokeResponseDto} invokeResponse)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
        {{
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" ReceiveResponseAsync({{invokeResponse}})"", invokeResponse);
        }}

        if (___PendingRequests.TryGetValue(invokeResponse.RequestId, out var ___channel))
            ___channel.Writer.TryWrite(invokeResponse);
    }}
    public async Task ReceiveResponseDoneAsync({ApiInvokeResponseDoneDto} invokeResponseDone)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
        {{
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" ReceiveResponseDoneAsync({{invokeResponseDone}})"", invokeResponseDone);
        }}

        if (___PendingRequests.TryRemove(invokeResponseDone.RequestId, out var ___channel))
            ___channel.Writer.TryComplete();
    }}
{string.Join("", Interface.Methods.Select(method => $@"
    public byte[] {Interface}_{method}_Serializer({string.Join(", ", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
        {arg.ParameterType} {arg}"))})
    {{{(method.Arguments.Any(a => a.ParameterType.IsCancellationToken == false) ? $@"
        var ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => PropertyHelper.GenerateLengthCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        var ___buffer = new byte[___offset];
        var ___span = new Span<byte>(___buffer);
        var ___length = ___offset;
        ___offset = 0;{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => PropertyHelper.GenerateSpanWriteCode(arg.ParameterSymbol.Type, arg.Name, "        ", false)))}
        if (___length != ___offset)
            throw new Exception($""Binary length doesn't match: {{___length}} != {{___offset}}"");
        return ___buffer;" : $@"
        return [];")}
    }}"))}{functions}

    public void Dispose()
    {{
        ___Cts.Cancel();
        ___Cts.Dispose();

        GC.SuppressFinalize(this);
    }}
}}";

        Code = $"{GetNamespacesCode()}{Code}";
    }
}