using gAPI.AutoWssClient.Models;
using System.Linq;

namespace gAPI.AutoWssClient.Generators;

public class AutoWssExtensionGenerator : BaseGenerator
{
    public AutoWssExtensionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "AutoWssClientExtension";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference ClientConnection => Context.ClientConnection;
    public SharedReference IClientConnection => Context.IClientConnection;
    public SharedReference IWssLoggerFactory => Context.SharedReferences.IWssLoggerFactory;
    public SharedReference IWssClientConnection => Context.SharedReferences.IWssClientConnection;
    public SharedReference FrontendConfig => Context.SharedReferences.FrontendConfig;

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.DependencyInjection");
        Reg(ClientConnection);
        Reg(IClientConnection);
        Reg(IWssLoggerFactory);
        Reg(IWssClientConnection);
        Reg(FrontendConfig);
        foreach (var api in Context.Apis)
        {
            Reg(api);
            Reg(api.Interface);
        }
        foreach (var api in Context.MinimalApis)
        {
            Reg(api);
            Reg(api.Interface);
        }
        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public static class {Name}
{{
    public static IServiceCollection AddAutoWssClient(this IServiceCollection services, string apiAddress, string wssAddress)
    {{
        // Set up authorization core
        services.AddAuthorizationCore();

        // Set up configuration
        var config = new {FrontendConfig}()
        {{
            ApiBackendUrl = apiAddress,
            WssBackendUrl = wssAddress
        }};
        services.AddSingleton(config);

        // Connection stuff
        services.AddScoped<{ClientConnection}>();
        services.AddScoped<{IClientConnection}>(sp => sp.GetRequiredService<{ClientConnection}>());
        services.AddScoped<{IWssLoggerFactory}>(sp => sp.GetRequiredService<{ClientConnection}>());

        // Api clients{string.Join("", Context.Apis.Select(api => $@"
        services.AddScoped<{api.Interface}>(sp => sp.GetRequiredService<{ClientConnection}>().{api});"))}
        
        // Minimal api clients{string.Join("", Context.MinimalApis.Select(api => $@"
        services.AddScoped<{api.Interface}, {api}>();"))}

        return services;
    }}
}}";
    }
}