using gAPI.AutoSerializer;
using gAPI.AutoWssClient.Helpers;
using gAPI.AutoWssClient.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace gAPI.AutoWssClient.Generators;

public class ClientConnectionGenerator : BaseGenerator
{
    public ClientConnectionGenerator(Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "ClientConnection";
        FileName = $"{Name}.g.cs";

        PropertyHelper = new GeneratePropertyHelper([], Context.CustomSpanSerializers, [], Reg, NeededSerializers);
    }

    public Generator Context { get; }
    public SharedReference WssClientConnection => Context.SharedReferences.WssClientConnection;
    public SharedReference IClientConnection => Context.IClientConnection;
    public SharedReference IClientAuthenticatedHttpClient => Context.SharedReferences.IClientAuthenticatedHttpClient;
    public SharedReference SubscribeDto => Context.SharedReferences.SubscribeDto;
    public SharedReference ApiInvokeResponseDto => Context.SharedReferences.ApiInvokeResponseDto;
    public SharedReference InvokeRequestDto => Context.SharedReferences.InvokeRequestDto;
    public SharedReference SendRequestDto => Context.SharedReferences.SendRequestDto;
    public SharedReference UnsubscribeDto => Context.SharedReferences.UnsubscribeDto;
    public SharedReference ServiceId => Context.SharedReferences.ServiceId;
    public SharedReference InvokeResponseDto => Context.SharedReferences.InvokeResponseDto;
    public SharedReference ApiInvokeResponseDoneDto => Context.SharedReferences.ApiInvokeResponseDoneDto;
    public SharedReference InvokeResponseDoneDto => Context.SharedReferences.InvokeResponseDoneDto;
    public SharedReference FrontendConfig => Context.SharedReferences.FrontendConfig;

    public List<INamedTypeSymbol> NeededSerializers { get; private set; } = new();
    public GeneratePropertyHelper PropertyHelper { get; }

    public override void GenerateCode()
    {
        Reg("Microsoft.Extensions.Logging");
        Reg("Microsoft.Extensions.Options");
        Reg("System");
        Reg("System.Text");
        Reg("System.Buffers.Binary");
        Reg("gAPI.Core.Attributes");
        Reg("gAPI.Core.Serializers");
        Reg(WssClientConnection);
        Reg(IClientConnection);
        Reg(IClientAuthenticatedHttpClient);
        Reg(SubscribeDto);
        Reg(ApiInvokeResponseDto);
        Reg(InvokeRequestDto);
        Reg(SendRequestDto);
        Reg(UnsubscribeDto);
        Reg(ServiceId);
        Reg(InvokeResponseDto);
        Reg(ApiInvokeResponseDoneDto);
        Reg(InvokeResponseDoneDto);
        foreach (var @interface in Context.ServiceContext.ApiInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        foreach (var @interface in Context.ServiceContext.HubInterfaces)
        {
            Reg(@interface);
            foreach (var method in @interface.Methods)
            {
                RegRecursive(method.ResponseType);
                foreach (var arg in method.Arguments)
                {
                    Reg(arg.ParameterType);
                }
            }
        }
        Reg(FrontendConfig);
        var functions = string.Empty;
        Code = @$"
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}
    : {WssClientConnection}, {IClientConnection}
{{
    public {Name}(
        {IClientAuthenticatedHttpClient} httpClient, 
        IOptions<{FrontendConfig}> options)
        : base(httpClient, options)
    {{
        ___Logger = ((IWssLoggerFactory)this).CreateLogger<{Name}>();{string.Join("", Context.Apis.Select(api => $@"
        {api} = new {api}(this, this, httpClient);"))}
    }}

    readonly ILogger ___Logger;
    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];{string.Join("", Context.Apis.Select(api => $@"
    
    public {api} {api} {{ get; }}
    {api.Interface} {IClientConnection}.{api} => {api};"))}{string.Join("", Context.ServiceContext.HubInterfaces.Select(hub => $@"

    readonly List<{hub}> {hub.CleanName.ToMultiple()} = [];
    readonly SemaphoreSlim {hub.CleanName.ToMultiple()}Lock = new(1, 1);
    
    private async Task<{hub}[]> Get{hub.CleanName.ToMultiple()}SnapshotAsync()
    {{
        await {hub.CleanName.ToMultiple()}Lock.WaitAsync();
        try
        {{
            return [.. {hub.CleanName.ToMultiple()}];
        }}
        finally
        {{
            {hub.CleanName.ToMultiple()}Lock.Release();
        }}
    }}"))}

    public async Task SubscribeAsync(object implementation, CancellationToken ___ct = default)
    {{
        await TryConnectAsync(___ct);{string.Join("", Context.ServiceContext.HubInterfaces.Select(hub => $@"

        if (implementation is {hub} {hub.CleanName.ToCamelCase()})
        {{
            if (___Logger.IsEnabled(LogLevel.Trace))
                ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" SubscribeAsync({{serviceId}})"", ""{hub}"");

            await {hub.CleanName.ToMultiple()}Lock.WaitAsync(___ct);
            try
            {{
                {hub.CleanName.ToMultiple()}.Add({hub.CleanName.ToCamelCase()});
            }}
            finally
            {{
                {hub.CleanName.ToMultiple()}Lock.Release();
            }}

            await Send_Subscribe_ToServerAsync(new {SubscribeDto}()
            {{
                ServiceId = new ServiceId(""{hub}""),
                SessionId = HttpClient.SessionId,
                UserId = HttpClient.UserId
            }}, ___ct);
        }}"))}
    }}
    public async Task UnsubscribeAsync(object implementation, CancellationToken ___ct = default)
    {{
        if (!Initialized)
            return;{string.Join("", Context.ServiceContext.HubInterfaces.Select(hub => $@"

        if (implementation is {hub} {hub.CleanName.ToCamelCase()})
        {{
            if (___Logger.IsEnabled(LogLevel.Trace))
                ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" UnsubscribeAsync({{serviceId}})"", ""{hub}"");

            await {hub.CleanName.ToMultiple()}Lock.WaitAsync(___ct);
            try
            {{
                {hub.CleanName.ToMultiple()}.Remove({hub.CleanName.ToCamelCase()});
            }}
            finally
            {{
                {hub.CleanName.ToMultiple()}Lock.Release();
            }}

            await Send_Unsubscribe_ToServerAsync(new {UnsubscribeDto}()
            {{
                ServiceId = new {ServiceId}(""{hub}""),
                SessionId = HttpClient.SessionId,
                UserId = HttpClient.UserId
            }}, ___ct);
        }}"))}
    }}

    protected override async Task Received_SendRequest_FromServerAsync({SendRequestDto} ___sendRequest, CancellationToken ___ct)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" Received_SendRequest_FromServerAsync({{___sendRequest}})"", ___sendRequest);
{(Context.ServiceContext.HubInterfaces.Any(hub => hub.Methods.Any(a => a.ResponseType.IsTask)) ? $@"
        switch (___sendRequest.ServiceId.Value)
        {{{string.Join("", Context.ServiceContext.HubInterfaces.Where(hub => hub.Methods.Any(a => a.ResponseType.IsTask)).Select(hub => $@"
            case ""{hub}"":
                {{
                    var clients = await Get{hub.CleanName.ToMultiple()}SnapshotAsync();
                    switch (___sendRequest.MethodId.Value)
                    {{{string.Join("", hub.Methods.Where(a => a.ResponseType.IsTask).Select(method => $@"
                        case ""{method}"":
                            {{
                                var ___offset = 0;
                                var ___span = new Span<byte>(___sendRequest.BinaryData);{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
                                var {arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(arg.ParameterType.Type, false, ref functions)};"))}
                                foreach (var client in clients)
                                {{
                                    await client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
                                        {arg.Name.ToCamelCase()}" : $@"
                                        ___ct"))});
                                }}
                                return;
                            }}"))}
                    }}
                    break;
                }}"))}
        }}" : "")}
        throw new Exception($""Service \""{{___sendRequest.ServiceId.Value}}\"" / Method \""{{___sendRequest.MethodId.Value}}\"" not found"");
    }}
    protected override async Task Received_InvokeRequest_FromServerAsync({InvokeRequestDto} ___invokeRequest, CancellationToken ___ct)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" Received_InvokeRequest_FromServerAsync({{___invokeRequest}})"", ___invokeRequest);
{(Context.ServiceContext.HubInterfaces.Any(@interface => @interface.Methods.Any(a => a.ResponseType.IsIAsyncEnumerable)) ? $@"
        switch (___invokeRequest.ServiceId.Value)
        {{{string.Join("", Context.ServiceContext.HubInterfaces.Where(@interface => @interface.Methods.Any(a => a.ResponseType.IsIAsyncEnumerable)).Select(@interface => $@"
            case ""{@interface}"":
                {{
                    var clients = await Get{@interface.CleanName.ToMultiple()}SnapshotAsync();
                    switch (___invokeRequest.MethodId.Value)
                    {{{string.Join("", @interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable).Select(method =>
        {
            var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
            return $@"
                        case ""{method}"":
                            {{
                                var ___offset = 0;
                                var ___span = new Span<byte>(___invokeRequest.BinaryData);{string.Join("", method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).Select(arg => $@"
                                var {arg.Name.ToCamelCase()} = {PropertyHelper.GenerateSpanReadCode(arg.ParameterType.Type, false, ref functions)};"))}
                                foreach (var client in clients)
                                {{
                                    var responses = client.{method}({string.Join(",", method.Arguments.Select(arg => arg.ParameterType.IsCancellationToken == false ? $@"
                                        {arg.Name.ToCamelCase()}" : $@"
                                        ___ct"))});
                                    await foreach (var response in responses)
                                    {{{(returnTypeInner.IsHubResultT ? $@"
                                        response.UserId = HttpClient.UserId;
                                        response.SessionId = HttpClient.SessionId;
" : "")}
                                        await Send_InvokeResponse_ToServerAsync(
                                            new {InvokeResponseDto}()
                                            {{
                                                RequestId = ___invokeRequest.RequestId,
                                                ServiceId = ___invokeRequest.ServiceId,
                                                MethodId = ___invokeRequest.MethodId,
                                                BinaryData = {@interface}_{method}_Serializer(response)
                                            }}, ___ct);
                                    }}
                                }}

                                await Send_InvokeResponseDone_ToServerAsync(
                                    new {InvokeResponseDoneDto}()
                                    {{
                                        RequestId = ___invokeRequest.RequestId,
                                        ServiceId = ___invokeRequest.ServiceId,
                                        MethodId = ___invokeRequest.MethodId
                                    }}, ___ct);
                            }}
                            return;";
        }))}
                    }}
                    break;
                }}"))}
        }}" : "")}
        throw new Exception($""Service \""{{___invokeRequest.ServiceId.Value}}\"" / Method \""{{___invokeRequest.MethodId.Value}}\"" not found"");
    }}
    protected override Task Received_InvokeResponse_FromServerAsync({ApiInvokeResponseDto} ___invokeResponse, CancellationToken ___ct)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" Received_InvokeResponse_FromServerAsync({{___invokeResponse}})"", ___invokeResponse);
{(Context.ServiceContext.ApiInterfaces.Any() ? $@"
        switch (___invokeResponse.ServiceId.Value)
        {{{string.Join("", Context.ServiceContext.ApiInterfaces.Select(api => $@"
            case ""{api}"":
                return {api.CleanName}.ReceiveResponseAsync(___invokeResponse);"))}
        }}" : "")}
        throw new Exception($""Service \""{{___invokeResponse.ServiceId.Value}}\"" / Method \""{{___invokeResponse.MethodId.Value}}\"" not found"");
    }}
    protected override Task Received_InvokeResponseDone_FromServerAsync({ApiInvokeResponseDoneDto} ___invokeResponseDone, CancellationToken ___ct)
    {{
        if (___Logger.IsEnabled(LogLevel.Trace))
            ___Logger.LogTrace(DateTime.Now.ToString(""HH:mm:ss.fff"") + "" Received_InvokeResponseDone_FromServerAsync({{___invokeResponseDone}})"", ___invokeResponseDone);
{(Context.ServiceContext.ApiInterfaces.Any() ? $@"
        switch (___invokeResponseDone.ServiceId.Value)
        {{{string.Join("", Context.ServiceContext.ApiInterfaces.Select(api => $@"
            case ""{api}"":
                return {api.CleanName}.ReceiveResponseDoneAsync(___invokeResponseDone);"))}
        }}" : "")}
        throw new Exception($""Service \""{{___invokeResponseDone.ServiceId.Value}}\"" / Method \""{{___invokeResponseDone.MethodId.Value}}\"" not found"");
    }}{string.Join("", Context.ServiceContext.HubInterfaces.Select(Interface => string.Join("", Interface.Methods.Where(a => a.ResponseType.IsIAsyncEnumerable).Select(method =>
{
    var returnTypeInner = method.ResponseType.UnderlayingTypes.Single();
    return $@"

    public byte[] {Interface}_{method}_Serializer({returnTypeInner} value)
    {{
        var ___offset = 0;
        var ___span = new Span<byte>(___Buffer);{PropertyHelper.GenerateSpanWriteCode(returnTypeInner.Type, "value", "        ", false)}
        return ___span.Slice(0, ___offset).ToArray();
    }}";
}))))}{functions}
}}";
        Code = $"{GetNamespacesCode()}{Code}";
    }

}