using gAPI.AutoWss.Client.Models;
using System.Linq;

namespace gAPI.AutoWss.Client.Generators;

public class IClientConnectionGenerator : _BaseGenerator
{
    public IClientConnectionGenerator(
        Generator context)
    {
        Context = context;

        Directory = "";
        Namespace = "gAPI.Generated";

        Name = "IClientConnection";
        FileName = $"{Name}.g.cs";
    }

    public Generator Context { get; }
    public SharedReference IWssClientConnection => Context.SharedReferences.IWssClientConnection;

    public override void GenerateCode()
    {
        Reg(IWssClientConnection);
        foreach (var api in Context.Apis)
        {
            Reg(api);
        }
        Code = @$"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public interface {Name} : {IWssClientConnection}
{{{string.Join("", Context.Apis.Select(api => $@"
    {api.Interface} {api} {{ get; }}"))}

    Task SubscribeAsync(object implementation, CancellationToken ___ct = default);
    Task UnsubscribeAsync(object implementation, CancellationToken ___ct = default);
}}";
    }
}