using gAPI.AutoWssClient.Models;
using gAPI.AutoSerializer;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace gAPI.AutoWssClient.Generators;

public class MinimalClientGenerator : BaseGenerator
{
    private readonly CustomObjectMethod[] CustomMultipartFormDataContentSerializers;

    public MinimalClientGenerator(Generator context, Interface @interface, CustomObjectMethod[] customMultipartFormDataContentSerializers)
    {
        Interface = @interface;
        Context = context;
        CustomMultipartFormDataContentSerializers = customMultipartFormDataContentSerializers;

        Directory = "";
        Namespace = @interface.Namespace;

        Name = Interface.CleanName;
        FileName = $"{Name}.g.cs";

        TypeSymbol = @interface.NamedTypeSymbol;
        WriteMethodName = "Write";
        IsRecord = TypeSymbol.IsRecord || TypeSymbol.TypeKind == TypeKind.Struct;
    }

    public Interface Interface { get; }
    public Generator Context { get; }

    public SharedReference BaseResponse => Context.SharedReferences.BaseResponse;
    public SharedReference BaseResponseT => Context.SharedReferences.BaseResponseT;

    public SharedReference IClientAuthenticatedHttpClient => Context.SharedReferences.IClientAuthenticatedHttpClient;

    public List<INamedTypeSymbol> NeededSerializers { get; } = [];
    public INamedTypeSymbol TypeSymbol { get; }
    public string WriteMethodName { get; }
    public bool IsRecord { get; }
    public int ItemNumber { get; private set; }

    public override void GenerateCode()
    {
        Reg(Interface);
        Reg("Microsoft.Extensions.Logging");
        Reg("System.Net.Http.Json");
        Reg("System.Net.Http.Headers");
        Reg("Microsoft.AspNetCore.Http");
        Reg("System.Globalization");
        Reg("gAPI.Core.Extensions");
        Reg("gAPI.Core.Dtos");

        var methods = string.Join("", Interface.Methods.Select(method => GenerateMethod(method)));

        Code = $@"{GetNamespacesCode()}
// <auto-generated />
#nullable enable
namespace {Namespace};

public class {Name}(
    {IClientAuthenticatedHttpClient.FullName} clientAuthenticationService) 
    : {Interface.Name}
    , IDisposable
{{
    private readonly CancellationTokenSource Cts = new();{methods}

    public void Dispose()
    {{
        Cts.Dispose();
    }}
}}";
    }

    private string GenerateMethod(InterfaceMethod method)
    {
        if (!method.ResponseType.IsTask && !method.ResponseType.IsTaskT) return "";

        Reg(method.ResponseType);
        foreach (var arg in method.Arguments)
        {
            Reg(arg.ParameterType);
        }

        var args = method.Arguments.Where(a => a.ParameterType.IsCancellationToken == false).ToArray();
        var cancellationToken = method.Arguments.FirstOrDefault(a => a.ParameterType.IsCancellationToken);

        var arguments = string.Join(",", method.Arguments.Select(arg => $@"
        {arg.ParameterType} {arg}"));
        var writeProps = string.Join(
            "",
            args.Select(arg =>
                GenerateWriteCode(
                    arg.ParameterType.Type,
                    arg.Name,
                    arg.Name,
                    "        ",
                    false
                )));
        var responseCode = GenerateResponse(method, args, cancellationToken);
        var returnCode = GenerateReturn(method, args, cancellationToken);

        return $@"

    public async {method.ResponseType} {method}({arguments})
    {{
        var ___content = new MultipartFormDataContent();{writeProps}

{responseCode}{returnCode}
    }}";
    }

    private string GenerateWriteCode(ITypeSymbol type, string propName, string fieldName, string indent, bool fromGeneric)
    {
        (var underlyingType, var isNullable, var isNullableT) = Helper.GetUnderlayingAndNullable(type);

        var customSerializer = CustomMultipartFormDataContentSerializers
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.Type, underlyingType));

        // CUSTOM SERIALIZER
        if (customSerializer != null)
        {
            Reg(customSerializer.StaticClass.ContainingNamespace.ToDisplayString());

            return isNullable
                ? $@"
{indent}if ({propName} != null)
{indent}    {customSerializer.StaticClass.Name}.{customSerializer.Method.Name}(___content, $""{fieldName}"", {propName}{(isNullableT ? ".Value" : "")});"
                : $@"
{indent}{customSerializer.StaticClass.Name}.{customSerializer.Method.Name}(___content, $""{fieldName}"", {propName});";
        }

        // ENUM
        if (underlyingType.TypeKind == TypeKind.Enum)
        {
            return isNullable
                ? $@"
{indent}if ({propName}.HasValue)
{indent}    ___content.Add(new StringContent(((int){propName}.Value).ToString()), $""{fieldName}"");"
                : $@"
{indent}___content.Add(new StringContent(((int){propName}).ToString()), $""{fieldName}"");";
        }

        switch (underlyingType.ToDisplayString())
        {
            case "int":
            case "long":
            case "float":
            case "double":
            case "bool":
                return isNullable
                    ? $@"
{indent}if ({propName}.HasValue)
{indent}    ___content.Add(new StringContent({propName}.Value.ToString()), $""{fieldName}"");"
                    : $@"
{indent}___content.Add(new StringContent({propName}.ToString()), $""{fieldName}"");";

            case "System.DateTime":
            case "System.DateTimeOffset":
                return isNullable
                    ? $@"
{indent}if ({propName}.HasValue)
{indent}    ___content.Add(new StringContent({propName}.Value.ToString(""O"")), $""{fieldName}"");"
                    : $@"
{indent}___content.Add(new StringContent({propName}.ToString(""O"")), $""{fieldName}"");";

            case "string":
                return $@"
{indent}___content.Add(new StringContent({propName}), $""{fieldName}"");";

            case "string?":
                return $@"
{indent}if ({propName} != null)
{indent}    ___content.Add(new StringContent({propName}), $""{fieldName}"");";
        }

        // Array !!!!! 
        if (underlyingType is IArrayTypeSymbol array)
        {
            // BYTE ARRAY (file upload)
            if (array.ElementType.Name == "Byte")
            {
                return isNullable
                    ? $@"
{indent}if ({propName} != null)
{indent}    ___content.Add(new ByteArrayContent({propName}), $""{fieldName}"", ""file"");"
                    : $@"
{indent}___content.Add(new ByteArrayContent({propName}), $""{fieldName}"", ""file"");";
            }

            var itemNumber = ++ItemNumber;

            return isNullable
                ? $@"
{indent}if ({propName} != null)
{indent}{{
{indent}    foreach (var item{itemNumber} in {propName}{(isNullableT ? ".Value" : "")})
{indent}    {{
{GenerateWriteCode(array.ElementType, $"item{itemNumber}", fieldName, indent + "        ", fromGeneric)}
{indent}    }}
{indent}}}"
                : $@"
{indent}foreach (var item{itemNumber} in {propName})
{indent}{{
{GenerateWriteCode(array.ElementType, $"item{itemNumber}", fieldName, indent + "    ", fromGeneric)}
{indent}}}";
        }

        // NESTED OBJECT
        if (underlyingType is INamedTypeSymbol named)
            NeededSerializers.Add(named);

        Reg(underlyingType.ContainingNamespace.ToDisplayString());

        return isNullable
            ? $@"
{indent}if ({propName} != null)
{indent}    {Helper.GetName(underlyingType)}MultipartFormDataContentSerializer.Write(___content, $""{fieldName}"", {propName}{(isNullableT ? ".Value" : "")});"
            : $@"
{indent}{Helper.GetName(underlyingType)}MultipartFormDataContentSerializer.Write(___content, $""{fieldName}"", {propName});";
    }

    private string GenerateResponse(InterfaceMethod method, InterfaceMethodArgument[] args, InterfaceMethodArgument cancellationToken)
    {

        var code = "";
        if (args.Length == 0)
        {
            code += $"        using var response = await clientAuthenticationService.GetAsync(\"/{Interface.CleanName}/{method.Name}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsList)
        {
            code += $"        var query = $\"{{(queryItems.Count > 0 ? \"?\" : \"\")}}{{string.Join(\"&\", queryItems)}}\";\r\n";
            code += $"        using var response = await clientAuthenticationService.GetAsync($\"/{Interface.CleanName}/{method.Name}{{query}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsListBy || method.IsListNotBy)
        {
            var idArg = method.Arguments
                .First(a => a.Name != "skip" && a.Name != "take" && a.Name != "orderby");
            code += $"        var query = $\"{{(queryItems.Count > 0 ? \"?\" : \"\")}}{{string.Join(\"&\", queryItems)}}\";\r\n";
            code += $"        using var response = await clientAuthenticationService.GetAsync($\"/{Interface.CleanName}/{method.Name}/{{{idArg.Name}}}{{query}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsRead)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.GetAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsDelete)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.DeleteAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsUpdate)
        {
            code += $"        using var response = await clientAuthenticationService.PutAsync($\"/{Interface.CleanName}/{method.Name}\", ___content{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsFileUpdate)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.PutAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\", ___content{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else if (method.IsFileDelete)
        {
            var arg = method.Arguments.First();
            code += $"        using var response = await clientAuthenticationService.DeleteAsync($\"/{Interface.CleanName}/{method.Name}/{{{arg.Name}}}\"{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        else
        {
            code += $"        using var response = await clientAuthenticationService.PostAsync(\"/{Interface.CleanName}/{method.Name}\", ___content{(cancellationToken != null ? $", {cancellationToken.Name}" : ", Cts.Token")});";
        }
        return code;
    }

    private string GenerateReturn(InterfaceMethod method, InterfaceMethodArgument[] args, InterfaceMethodArgument cancellationToken)
    {

        var orderByQueryItem = method.Arguments
            .Where(a => a.Name == "orderby")
            .FirstOrDefault();

        var skipTakeQueryItems = method.Arguments
            .Where(a => a.Name == "skip" || a.Name == "take");

        var underlaying = method.ResponseType.UnderlayingTypes.FirstOrDefault();

        var methodType =
            underlaying == null
            ? $"Task"
            : $"Task<{method.ResponseType.UnderlayingTypes[0].Name}>";

        var responseType =
            underlaying == null
            ? "BaseResponse"
            : (underlaying.IsBaseResponse || underlaying.IsBaseResponseT || underlaying.IsBaseListResponseT)
                ? underlaying.Name
                : $"BaseResponseT<{underlaying.Name}>";

        return $@"
        response.EnsureSuccessStatusCode();

        var responseData = await response.Content.ReadFromJsonAsync<{responseType}>({(cancellationToken != null ? $"{cancellationToken.Name}" : "Cts.Token")})
            ?? throw new Exception(""Could not cast response data"");{(
                underlaying == null
                ? ""
                :
                    underlaying.IsBaseResponse ||
                    underlaying.IsBaseResponseT ||
                    underlaying.IsBaseListResponseT
                    ? $@"
        return responseData;"
                    :
                        underlaying.IsNullable || underlaying.Name == "bool"
                        ? @"
        return responseData.Response;" :
                            underlaying.IsValueType
                            ? @"
        return responseData.Response!;"
                        : @"
        return responseData.Response
            ?? throw new Exception(""Could not cast response data"");")}";
    }







    //private static string SerializeToForm(TypeHelper dto, string? root = null)
    //{
    //    var code = string.Empty;
    //    foreach (var prop in dto.GetProperties())
    //    {
    //        if (!prop.IsReadOnly && !prop.IsForeignName && prop.PropertyType.IsCancellationToken == false)
    //        {
    //            var propertyName = root == null ? prop.Name : $"{root}.{prop.Name}";
    //            if (prop.PropertyType.IsProperty == false)
    //            {
    //                SerializeToForm(prop.PropertyType, propertyName);
    //            }
    //            else
    //            {
    //                code = AddProperty(code, prop.IsNullable, prop.PropertyType.IsValueType, prop.PropertyType.IsArray, prop.PropertyType.IsDateTime, prop.PropertyType.IsDateTimeOffset, propertyName);
    //            }
    //        }
    //    }
    //    return code;
    //}

    //private static string AddProperty(string code, bool isNulleble, bool isValueType, bool isArray, bool isDateTime, bool isDateTimeOffset, string propertyName)
    //{
    //    string toString;
    //    if (isDateTimeOffset)
    //    {
    //        toString = ".ToUnixTimeMilliseconds().ToString(CultureInfo.InvariantCulture)";
    //    }
    //    else if (isDateTime)
    //    {
    //        toString = ".ToUniversalTime().ToString(\"yyyy-MM-ddTHH:mm:ss.fffffffZ\", CultureInfo.InvariantCulture)";
    //    }
    //    else
    //    {
    //        if (isValueType)
    //            toString = ".ToString()";
    //        else
    //            toString = ".ToString(CultureInfo.InvariantCulture)";
    //    }

    //    if (isArray)
    //    {
    //        if (isNulleble)
    //        {
    //            if (isValueType)
    //            {
    //                return $@"
    //    if ({propertyName} != null)
    //        foreach(var item in {propertyName}) 
    //            content.Add(new StringContent(item.Value{toString}), ""{propertyName}"");";
    //            }
    //            else
    //            {
    //                code += $@"
    //    if ({propertyName} != null)
    //        foreach(var item in {propertyName}) 
    //            content.Add(new StringContent(item{toString}), ""{propertyName}"");";
    //            }
    //        }
    //        else
    //        {
    //            code += $@"
    //    foreach(var item in {propertyName}) 
    //        content.Add(new StringContent(item{toString}), ""{propertyName}"");";
    //        }
    //    }
    //    else if (isNulleble)
    //    {
    //        if (isValueType)
    //        {
    //            code += $@"
    //    if ({propertyName} != null)
    //        content.Add(new StringContent({propertyName}.Value{toString}), ""{propertyName}"");";
    //        }
    //        else
    //        {
    //            code += $@"
    //    if ({propertyName} != null)
    //        content.Add(new StringContent({propertyName}{toString}), ""{propertyName}"");";
    //        }
    //    }
    //    else
    //    {
    //        code += $@"
    //    content.Add(new StringContent({propertyName}{toString}), ""{propertyName}"");";
    //    }

    //    return code;
    //}
}